// Class: ReadBDTG_UF_v1
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTG_UF_v1
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.10/09       [395785]
Creator        : xzuo
Date           : Wed May 22 21:46:39 2019
Host           : Linux cmsbuild49.cern.ch 2.6.32-696.10.2.el6.x86_64 #1 SMP Thu Sep 14 16:35:02 CEST 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/x/xzuo/h2mm_944/src/H2MuAnalyzer/TrainMVA
Training events: 65096
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
nCuts: "10" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for GradBoost algorithm]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
dimu_mass                     dimu_mass                     dimu_mass                     M(#mu#mu)                     GeV                               'F'    [100.245376587,159.985855103]
dimu_pt                       dimu_pt                       dimu_pt                       p_{T}(#mu#mu)                 GeV                               'F'    [0.199431017041,1447.98535156]
dimu_dR                       dimu_dR                       dimu_dR                       dR(#mu#mu)                                                      'F'    [0.183524668217,5.25127029419]
dilep_mass                    dilep_mass                    dilep_mass                    M(ll)                         GeV                               'F'    [81.0000228882,100.997390747]
dilep_pt                      dilep_pt                      dilep_pt                      P_{T}(ll)                     GeV                               'F'    [0.0361974164844,1245.30322266]
dilep_abs_dPhi                dilep_abs_dPhi                dilep_abs_dPhi                |d#phi(ll)|                                                     'F'    [1.50203704834e-05,3.14156246185]
dilep_dR                      dilep_dR                      dilep_dR                      dR(ll)                                                          'F'    [0.174173697829,5.1896777153]
lep_ID                        lep_ID                        lep_ID                        lep_ID                                                          'I'    [11,13]
dipair_dEta_H                 dipair_dEta_H                 dipair_dEta_H                 d#eta((#mu#mu),(ll))                                            'F'    [-9.73767852783,9.95819950104]
cts_dipair_H                  cts_dipair_H                  cts_dipair_H                  cos(#theta*)((#mu#mu),(ll))                                     'F'    [-0.99999243021,0.999974668026]
mht_pt                        mht_pt                        mht_pt                        p_{T}(mht)                    GeV                               'F'    [0.0488994345069,1205.65710449]
NSpec 5
event_wgt                     event_wgt                     event_wgt                     event weight                                                    'F'    [-1.52057862282,3.92260169983]
xsec_norm                     xsec_norm                     xsec_norm                     xsec normal                                                     'F'    [2.90000007226e-05,0.0557130016387]
Sample_ID                     Sample_ID                     Sample_ID                     Sample ID                                                       'F'    [-23230000,1302325]
lep_ID                        lep_ID                        lep_ID                        the Z decays to                                                 'F'    [11,13]
dimu_mass                     dimu_mass                     dimu_mass                     mass(#mu#mu)                  GeV                               'F'    [100.245376587,159.985855103]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTG_UF_v1Node
   
#ifndef BDTG_UF_v1Node__def
#define BDTG_UF_v1Node__def
   
class BDTG_UF_v1Node {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTG_UF_v1Node ( BDTG_UF_v1Node* left,BDTG_UF_v1Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTG_UF_v1Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTG_UF_v1Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTG_UF_v1Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTG_UF_v1Node*   fLeft;     // pointer to the left daughter node
   BDTG_UF_v1Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTG_UF_v1Node::~BDTG_UF_v1Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTG_UF_v1Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTG_UF_v1Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTG_UF_v1 : public IClassifierReader {

 public:

   // constructor
   ReadBDTG_UF_v1( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDTG_UF_v1" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "dimu_mass", "dimu_pt", "dimu_dR", "dilep_mass", "dilep_pt", "dilep_abs_dPhi", "dilep_dR", "lep_ID", "dipair_dEta_H", "cts_dipair_H", "mht_pt" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'I';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTG_UF_v1() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTG_UF_v1Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTG_UF_v1::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTG_UF_v1Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTG_UF_v1Node*)current->GetRight();
         else current=(BDTG_UF_v1Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDTG_UF_v1::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.117685,-0.0422846) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00332247,-0.071037) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0498189,-0.0757592) , 
0, 110.61, 1, 0, 0.0229168,-0.477083) , 
5, 1.71455, 1, 0, 0.0533103,-0.44669) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.32484,-0.00341283) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.864267,0.0186629) , 
0, 120.844, 1, 0, 0.787574,0.287574) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.299195,-0.0100801) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0122677,-0.0212116) , 
0, 134.128, 1, 0, 0.103702,-0.396298) , 
0, 128.384, 1, 0, 0.624295,0.124295) , 
0, 116.535, 1, 0, 0.49507,-0.00492964)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0599106,-0.0432347) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0217271,-0.0609604) , 
2, 2.32637, 1, 0, 0.0345354,-0.434076) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.125648,-0.0401226) , 
0, 112.09, 1, 0, 0.0639278,-0.404461) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.348533,-0.0133957) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.868024,0.0184701) , 
0, 120.847, 1, 0, 0.80303,0.295081) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333333,-0.0082315) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0086174,-0.0681163) , 
0, 134.137, 1, 0, 0.117411,-0.373847) , 
0, 128.388, 1, 0, 0.637399,0.133483) , 
0, 116.538, 1, 0, 0.503778,0.00813975)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0444669,-0.0405456) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00459359,-0.0911539) , 
6, 2.29816, 1, 0, 0.0209015,-0.420701) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0529343,-0.0417498) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.158803,-0.0366354) , 
0, 114.172, 1, 0, 0.0978148,-0.353348) , 
0, 110.219, 1, 0, 0.0591858,-0.387176) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.337646,-0.0140576) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.860388,0.0188759) , 
0, 120.629, 1, 0, 0.809843,0.294807) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.198566,-0.00692421) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0117299,-0.0162445) , 
0, 134.684, 1, 0, 0.0737682,-0.392691) , 
0, 129.062, 1, 0, 0.635213,0.131702) , 
0, 117.466, 1, 0, 0.493564,0.00410567)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0518733,-0.0154737) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.017875,-0.0779498) , 
9, 0.454535, 1, 0, 0.0414362,-0.37079) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.156375,-0.0363247) , 
0, 113.326, 1, 0, 0.0731532,-0.347217) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.46029,-0.00127584) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.864848,0.0164641) , 
0, 121.859, 1, 0, 0.798686,0.276441) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.232064,-0.0118268) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00745734,-0.0147148) , 
0, 134.805, 1, 0, 0.0728707,-0.385393) , 
0, 129.205, 1, 0, 0.635476,0.127618) , 
0, 117.658, 1, 0, 0.500643,0.0137629)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0476544,-0.0330507) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.194689,-0.0280479) , 
0, 114.785, 1, 0, 0.0797028,-0.326486) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47422,-0.000853886) , 
0, 118.016, 1, 0, 0.181261,-0.249383) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.827796,0.0134115) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.929384,0.0204597) , 
1, 78.8732, 1, 0, 0.874729,0.339133) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.262544,-0.0221227) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00699922,-0.0183432) , 
0, 134.539, 1, 0, 0.0859346,-0.367326) , 
0, 128.883, 1, 0, 0.672302,0.157836) , 
0, 121.969, 1, 0, 0.502436,0.0169667)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0424784,-0.0555497) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00699543,-0.0741235) , 
3, 91.8933, 1, 0, 0.0303201,-0.346627) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.124311,-0.040309) , 
0, 112.091, 1, 0, 0.0594013,-0.323579) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.444395,-0.00368588) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.880605,0.0173625) , 
0, 121.918, 1, 0, 0.798581,0.264259) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.31732,-0.00813967) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0114993,-0.01819) , 
0, 134.125, 1, 0, 0.114536,-0.333378) , 
0, 128.38, 1, 0, 0.634162,0.120609) , 
0, 116.534, 1, 0, 0.502597,0.0189328)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0224636,-0.0363897) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0390575,-0.00690922) , 
9, -0.272654, 1, 0, 0.032924,-0.318508) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.15747,-0.0299268) , 
0, 113.329, 1, 0, 0.068134,-0.295691) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.376786,-0.00267805) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.856112,0.0153585) , 
0, 120.813, 1, 0, 0.80588,0.263447) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.167268,-0.0358186) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00495814,-0.0121591) , 
0, 137.605, 1, 0, 0.0681648,-0.365617) , 
0, 129.208, 1, 0, 0.642793,0.12438) , 
0, 117.658, 1, 0, 0.503583,0.0226185)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0268175,-0.0491656) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0426209,-0.0568501) , 
3, 90.1049, 1, 0, 0.035731,-0.308591) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.163407,-0.0295161) , 
0, 113.329, 1, 0, 0.0713034,-0.283046) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333446,-0.00234833) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.855873,0.0150474) , 
0, 120.81, 1, 0, 0.798769,0.2498) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.223349,-0.010958) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0143404,-0.0544687) , 
0, 134.805, 1, 0, 0.0788217,-0.345459) , 
0, 129.205, 1, 0, 0.641542,0.119804) , 
0, 117.658, 1, 0, 0.503666,0.0224002)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.148003,-0.0106092) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0281465,-0.0623378) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0506429,-0.0447922) , 
3, 90.0815, 1, 0, 0.040784,-0.284488) , 
6, 1.91992, 1, 0, 0.0696627,-0.262529) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.384645,-0.00727361) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.863606,0.0166581) , 
0, 120.629, 1, 0, 0.814577,0.25911) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.190741,-0.0284077) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.000943814,-0.0119769) , 
0, 137.49, 1, 0, 0.0757792,-0.328925) , 
0, 129.059, 1, 0, 0.648682,0.127068) , 
0, 117.464, 1, 0, 0.506385,0.0313229)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.128519,-0.0285708) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0273632,-0.0348497) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0427372,-0.0383804) , 
2, 2.97171, 1, 0, 0.0334431,-0.272709) , 
2, 2.31691, 1, 0, 0.0654361,-0.249095) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.422645,-0.00141053) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.870026,0.0164389) , 
0, 121.684, 1, 0, 0.799022,0.237711) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.239105,-0.0133751) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0102915,-0.0161806) , 
0, 134.687, 1, 0, 0.078273,-0.317597) , 
0, 129.064, 1, 0, 0.633405,0.11011) , 
0, 117.468, 1, 0, 0.494644,0.0223518)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0293168,-0.023421) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0155157,-0.0625352) , 
5, 2.28535, 1, 0, 0.0225326,-0.262411) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.153685,-0.0199369) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.081361,-0.0316068) , 
6, 2.37326, 1, 0, 0.116034,-0.203003) , 
0, 110.442, 1, 0, 0.0690766,-0.232838) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481414,-0.00155438) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.868259,0.0150141) , 
0, 121.865, 1, 0, 0.809877,0.239482) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.180898,-0.0196066) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00258206,-0.0538284) , 
0, 137.605, 1, 0, 0.0747175,-0.312696) , 
0, 129.209, 1, 0, 0.645553,0.116059) , 
0, 117.658, 1, 0, 0.501505,0.0288776)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.165218,-0.0117193) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0615665,-0.0460944) , 
5, 1.42814, 1, 0, 0.0859293,-0.216544) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.831298,0.0121463) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.382423,-0.0060361) , 
0, 128.279, 1, 0, 0.786869,0.218206) , 
0, 119.097, 1, 0, 0.568652,0.0828595) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0270004,-0.0537776) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.0477) , 
0, 143.144, 1, 0, 0.012134,-0.34217) , 
0, 133.525, 1, 0, 0.497767,0.0287226)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0183015,-0.0328283) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0678465,-0.0398807) , 
0, 110.304, 1, 0, 0.0332567,-0.22707) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.146088,-0.025133) , 
0, 113.447, 1, 0, 0.0640365,-0.209961) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469913,-0.00256823) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.863762,0.0141535) , 
0, 121.952, 1, 0, 0.80086,0.220823) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.160228,-0.0282041) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00398271,-0.0319674) , 
0, 137.652, 1, 0, 0.0649485,-0.284948) , 
0, 129.279, 1, 0, 0.633172,0.105575) , 
0, 117.765, 1, 0, 0.487268,0.0246841)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.251876,-0.00994119) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0884838,-0.011691) , 
6, 1.88706, 1, 0, 0.130344,-0.174337) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.922087,0.0152111) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.807261,0.0121918) , 
5, 1.71368, 1, 0, 0.863892,0.262587) , 
0, 121.023, 1, 0, 0.574928,0.0904708) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.279983,-0.0103549) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0278277,-0.0190709) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0014138,-0.0493591) , 
0, 143.455, 1, 0, 0.0136318,-0.303565) , 
0, 134.01, 1, 0, 0.105011,-0.252751) , 
0, 128.238, 1, 0, 0.488355,0.0272391)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.31045,-0.00261152) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.087585,-0.0236348) , 
5, 1.14333, 1, 0, 0.13098,-0.167878) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.875212,0.0142466) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.514566,0.000916383) , 
0, 127.437, 1, 0, 0.82273,0.231007) , 
0, 120.975, 1, 0, 0.574243,0.0877213) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00278518,-0.0320354) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0346688,-0.016737) , 
4, 64.0746, 1, 0, 0.0166637,-0.290013) , 
0, 132.828, 1, 0, 0.500156,0.0375306)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.332463,-0.00132596) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.100236,-0.00926018) , 
5, 1.14241, 1, 0, 0.143679,-0.152808) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.874325,0.0149307) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.503588,0.000592534) , 
0, 127.44, 1, 0, 0.820206,0.223409) , 
0, 120.978, 1, 0, 0.569466,0.0839723) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00539255,-0.0182284) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0264308,-0.0283493) , 
9, -0.272628, 1, 0, 0.0183738,-0.278216) , 
0, 132.825, 1, 0, 0.495785,0.035548)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0318522,-0.02262) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0141848,-0.0564429) , 
5, 2.2849, 1, 0, 0.023544,-0.204495) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.185978,-0.0129625) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.057369,-0.0414283) , 
5, 1.99921, 1, 0, 0.112823,-0.14828) , 
0, 110.219, 1, 0, 0.0681293,-0.176422) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.308205,-0.00349453) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.854177,0.0138709) , 
0, 120.63, 1, 0, 0.798659,0.19928) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.21718,-0.00911925) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00785386,-0.0461498) , 
0, 134.687, 1, 0, 0.0732376,-0.238742) , 
0, 129.064, 1, 0, 0.637833,0.10217) , 
0, 117.468, 1, 0, 0.496392,0.0330036)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0237614,-0.0101012) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0665399,-0.017999) , 
0, 109.952, 1, 0, 0.0385564,-0.182324) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.147935,-0.0186019) , 
0, 113.113, 1, 0, 0.0703434,-0.162912) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.337607,-0.00266818) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.855303,0.0135365) , 
0, 120.624, 1, 0, 0.801961,0.197203) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.193204,-0.00889567) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0372838,-0.0302224) , 
5, 1.71508, 1, 0, 0.0919485,-0.208426) , 
0, 129.056, 1, 0, 0.637844,0.103443) , 
0, 117.463, 1, 0, 0.500125,0.038805)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0449637,-0.0146135) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0251782,-0.0234964) , 
6, 2.29816, 1, 0, 0.0334522,-0.183013) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.151461,-0.018378) , 
0, 113.329, 1, 0, 0.0674234,-0.162242) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461246,-0.00107093) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.871807,0.0140868) , 
0, 121.863, 1, 0, 0.804262,0.194125) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.150062,-0.0191545) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0259853,-0.0271838) , 
5, 1.71354, 1, 0, 0.0688354,-0.217392) , 
0, 129.208, 1, 0, 0.636924,0.100489) , 
0, 117.658, 1, 0, 0.491457,0.0333797)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0435722,-0.0135176) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.1736,-0.0160278) , 
0, 114.784, 1, 0, 0.0706674,-0.157543) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.510087,0.00038226) , 
0, 118.018, 1, 0, 0.189911,-0.113408) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.924716,0.0159067) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.81295,0.0108321) , 
6, 2.28941, 1, 0, 0.876584,0.235335) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0396983,-0.0327215) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.17594,-0.0136719) , 
4, 81.5036, 1, 0, 0.0851507,-0.200623) , 
0, 128.88, 1, 0, 0.665625,0.119129) , 
0, 121.967, 1, 0, 0.500627,0.0384752)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.250393,-0.0032365) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.100589,-0.0227638) , 
2, 2.1182, 1, 0, 0.139975,-0.125953) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.817208,0.00806128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.935798,0.0163042) , 
1, 89.9952, 1, 0, 0.864493,0.218917) , 
0, 121.021, 1, 0, 0.585815,0.0862665) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.336769,-0.0068551) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00388674,-0.00748442) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0236689,-0.0173154) , 
9, -0.272664, 1, 0, 0.0156848,-0.222527) , 
0, 134.01, 1, 0, 0.120106,-0.176368) , 
0, 128.238, 1, 0, 0.495215,0.035173)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.413755,0.00161219) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.166118,-0.0164351) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0821082,-0.00190784) , 
3, 93.7173, 1, 0, 0.151277,-0.132187) , 
6, 1.48846, 1, 0, 0.192174,-0.105944) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.927292,0.0154138) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.825169,0.0110086) , 
5, 1.7136, 1, 0, 0.875189,0.222522) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.272245,-0.00808327) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00778218,-0.0306687) , 
0, 134.536, 1, 0, 0.0947733,-0.176747) , 
0, 128.88, 1, 0, 0.666891,0.115955) , 
0, 121.967, 1, 0, 0.500323,0.0380953)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0258745,-0.0116487) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.106882,-0.0221059) , 
0, 109.937, 1, 0, 0.070296,-0.141426) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.514434,0.00159759) , 
0, 118.014, 1, 0, 0.187197,-0.0983491) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.831816,0.0100675) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943972,0.0159699) , 
4, 82.798, 1, 0, 0.881952,0.223235) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.187047,-0.00477468) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0369861,-0.0383897) , 
2, 2.42138, 1, 0, 0.084091,-0.177586) , 
0, 128.875, 1, 0, 0.673295,0.118412) , 
0, 121.964, 1, 0, 0.511391,0.0462157)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417643,0.00383954) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.185108,-0.00531239) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0984469,-0.0121662) , 
7, 12, 1, 0, 0.12597,-0.0132191) , 
5, 1.14254, 1, 0, 0.184462,-0.101722) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.917481,0.0132002) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.807244,0.00941864) , 
5, 1.99922, 1, 0, 0.873396,0.209163) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.216981,-0.0114768) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00219825,-0.00961685) , 
0, 137.355, 1, 0, 0.0863862,-0.160791) , 
0, 128.874, 1, 0, 0.654611,0.106317) , 
0, 121.964, 1, 0, 0.490271,0.0335975)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0372446,-0.0248675) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0281397,-0.0218514) , 
5, 2.28486, 1, 0, 0.0328291,-0.156359) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520243,0.00726842) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.253833,-0.00426454) , 
5, 1.71361, 1, 0, 0.359913,-0.0281053) , 
0, 114.066, 1, 0, 0.177464,-0.0996459) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.930852,0.0152908) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.840014,0.0108228) , 
7, 12, 1, 0, 0.878314,0.0528296) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.269153,-0.00558314) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00783577,-0.031103) , 
0, 134.532, 1, 0, 0.0907353,-0.157041) , 
0, 128.874, 1, 0, 0.672045,0.112998) , 
0, 121.964, 1, 0, 0.501316,0.0395937)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0512746,-0.0175166) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0266396,-0.043262) , 
5, 2.28486, 1, 0, 0.0399148,-0.142405) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.139084,-0.0141886) , 
0, 113.119, 1, 0, 0.0682005,-0.12538) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574043,0.00275206) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.87799,0.0119232) , 
0, 122.738, 1, 0, 0.806072,0.164646) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.196514,-0.0114969) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00405034,-0.0446033) , 
0, 137.499, 1, 0, 0.0812831,-0.151232) , 
0, 129.065, 1, 0, 0.643577,0.093827) , 
0, 117.468, 1, 0, 0.497154,0.0380425)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0410905,-0.0138941) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0227362,-0.0267236) , 
6, 2.25666, 1, 0, 0.0302093,-0.145173) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.184415,-0.00712064) , 
0, 113.326, 1, 0, 0.0760892,-0.113811) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396456,-0.00322159) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.852317,0.0095509) , 
0, 120.809, 1, 0, 0.80565,0.158283) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0202319,-0.0303557) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.145416,-0.00833027) , 
1, 75.5285, 1, 0, 0.0694887,-0.151674) , 
0, 129.204, 1, 0, 0.643461,0.0899944) , 
0, 117.657, 1, 0, 0.501275,0.03892)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0447164,-0.0307456) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0171417,-0.0470288) , 
5, 2.28475, 1, 0, 0.0321093,-0.137283) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.158045,-0.0104119) , 
0, 113.448, 1, 0, 0.0678387,-0.117119) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501694,0.00054452) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.874106,0.0120819) , 
0, 121.957, 1, 0, 0.814869,0.163853) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0157312,-0.0245373) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0962137,-0.0210677) , 
9, -0.272751, 1, 0, 0.0653618,-0.148974) , 
0, 129.285, 1, 0, 0.648732,0.0945115) , 
0, 117.767, 1, 0, 0.50323,0.0415024)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501467,0.00405129) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0669703,-0.0194931) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.551825,-0.000453122) , 
0, 119.519, 1, 0, 0.192194,-0.0959409) , 
6, 1.48846, 1, 0, 0.243093,-0.0650492) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.936357,0.0148921) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.826007,0.00964617) , 
5, 1.42805, 1, 0, 0.867573,0.185195) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.155113,-0.00570993) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0266586,-0.0244372) , 
5, 1.7138, 1, 0, 0.0720852,-0.133029) , 
0, 129.545, 1, 0, 0.649201,0.0978381) , 
0, 122.781, 1, 0, 0.485397,0.0321373)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.442671,0.00565568) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.191269,-0.00826474) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.121403,-0.00809029) , 
7, 12, 1, 0, 0.141985,-0.0107979) , 
6, 1.45571, 1, 0, 0.186247,-0.0746734) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.913332,0.0132921) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.819517,0.00663321) , 
2, 2.56353, 1, 0, 0.868294,0.174541) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.281457,-0.00293853) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00856068,-0.0122612) , 
0, 134.54, 1, 0, 0.0917345,-0.118706) , 
0, 128.885, 1, 0, 0.661192,0.0963347) , 
0, 121.969, 1, 0, 0.492714,0.0356725)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0441176,-0.0165153) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.317036,-0.00219857) , 
0, 114.143, 1, 0, 0.151384,-0.075831) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.925352,0.0136999) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.821529,0.00884947) , 
5, 1.71368, 1, 0, 0.872818,0.1791) , 
0, 121.12, 1, 0, 0.5869,0.0780656) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.326486,-0.00416032) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.00580713) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0207175,-0.0388882) , 
9, -0.272668, 1, 0, 0.0121729,-0.155606) , 
0, 134.078, 1, 0, 0.116441,-0.121155) , 
0, 128.319, 1, 0, 0.498082,0.0404548)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.103996,-0.00392689) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.536124,0.00837338) , 
0, 114.533, 1, 0, 0.322518,0.00833444) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0581995,-0.0408692) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.126407,-0.0154402) , 
9, -0.454554, 1, 0, 0.106551,-0.112604) , 
5, 1.71432, 1, 0, 0.181516,-0.0706246) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.921036,0.0134255) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.817419,0.0083268) , 
5, 1.99954, 1, 0, 0.87896,0.176392) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266135,-0.00512162) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00823614,-0.0404203) , 
0, 134.537, 1, 0, 0.0909299,-0.114856) , 
0, 128.882, 1, 0, 0.671007,0.0995349) , 
0, 121.969, 1, 0, 0.503366,0.0412585)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405073,0.00439684) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.111828,-0.00963289) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.196021,-0.00356241) , 
10, 56.4374, 1, 0, 0.129275,-0.0969798) , 
6, 1.51896, 1, 0, 0.170224,-0.0735423) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.938304,0.0153233) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.806495,0.00918879) , 
6, 1.59484, 1, 0, 0.842716,0.162974) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.00704954) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0365827,-0.0347067) , 
9, -0.272915, 1, 0, 0.0222635,-0.134555) , 
0, 132.334, 1, 0, 0.671266,0.100799) , 
0, 121.965, 1, 0, 0.498631,0.0407294)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44736,0.00715143) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.108744,-0.0249186) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.219479,-0.00258033) , 
10, 52.7075, 1, 0, 0.135792,-0.0904757) , 
6, 1.4954, 1, 0, 0.182131,-0.0644506) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.909075,0.0126717) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.790833,0.00525403) , 
5, 2.28405, 1, 0, 0.873361,0.162155) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0462401,-0.0334686) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.199511,-0.00381872) , 
1, 86.4341, 1, 0, 0.0939044,-0.0990984) , 
0, 128.883, 1, 0, 0.664325,0.0920921) , 
0, 121.969, 1, 0, 0.496505,0.0376099)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0463729,-0.0207436) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0172272,-0.0171991) , 
5, 2.28539, 1, 0, 0.0325706,-0.105114) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.110984,-0.0115753) , 
0, 110.613, 1, 0, 0.0667911,-0.0832349) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.875684,0.0127731) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.713281,0.00635603) , 
6, 1.88088, 1, 0, 0.774733,0.132529) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00597013,-0.0129101) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0229631,-0.034968) , 
9, -0.272889, 1, 0, 0.0163974,-0.131416) , 
0, 132.338, 1, 0, 0.64278,0.0866012) , 
0, 116.538, 1, 0, 0.509668,0.0473518)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385168,0.00377583) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.192672,-0.00214028) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.105668,-0.0194435) , 
7, 12, 1, 0, 0.135979,-0.00875967) , 
5, 1.14259, 1, 0, 0.184851,-0.0572836) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.924479,0.0129911) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.843273,0.00864562) , 
7, 12, 1, 0, 0.877606,0.035061) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0298454,-0.0114517) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.207571,-0.000374263) , 
1, 86.0401, 1, 0, 0.0901244,-0.0939069) , 
0, 128.88, 1, 0, 0.663733,0.0897197) , 
0, 121.967, 1, 0, 0.499203,0.0392134)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385747,0.00362249) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.150789,-0.00874181) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0649843,-0.00253526) , 
3, 93.7183, 1, 0, 0.134225,-0.0816453) , 
5, 1.14243, 1, 0, 0.181666,-0.0581876) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.899487,0.0116999) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.790432,0.0030046) , 
2, 2.96019, 1, 0, 0.871851,0.148171) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0355743,-0.0168744) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.201069,-0.0020771) , 
1, 86.368, 1, 0, 0.0858766,-0.0924122) , 
0, 128.874, 1, 0, 0.671713,0.0869097) , 
0, 121.963, 1, 0, 0.500723,0.0362815)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.350107,0.00237187) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.18129,-0.00538886) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0923781,-0.00712716) , 
7, 12, 1, 0, 0.119226,-0.00720862) , 
6, 1.87018, 1, 0, 0.184899,-0.0503696) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.922852,0.012502) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.815333,0.0061995) , 
5, 1.99917, 1, 0, 0.878753,0.15116) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0422359,-0.0366771) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.209259,-0.00112526) , 
4, 81.8672, 1, 0, 0.0958568,-0.0825947) , 
0, 128.873, 1, 0, 0.675904,0.0905938) , 
0, 121.963, 1, 0, 0.5086,0.0425621)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0545529,-0.0225867) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00952771,-0.0477119) , 
5, 2.28513, 1, 0, 0.0334003,-0.0953351) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0824746,-0.0112336) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.150883,-0.00341905) , 
9, -0.0908322, 1, 0, 0.119474,-0.0461549) , 
0, 110.22, 1, 0, 0.0759189,-0.0710412) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.312821,-0.00187057) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.822685,0.00960739) , 
0, 120.279, 1, 0, 0.78016,0.121109) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00861069,-0.0361277) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0205587,-0.0154595) , 
9, -0.0908642, 1, 0, 0.015191,-0.109376) , 
0, 132.93, 1, 0, 0.647563,0.081158) , 
0, 117.468, 1, 0, 0.505456,0.0433223)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0582596,-0.0181942) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0270256,-0.0356064) , 
5, 2.28512, 1, 0, 0.0434248,-0.082766) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.139296,-0.00814404) , 
0, 113.119, 1, 0, 0.0708444,-0.0710538) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.881876,0.0119314) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.747481,0.00525255) , 
6, 2.0442, 1, 0, 0.806314,0.119881) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.194105,-0.0058329) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00602876,-0.0152982) , 
0, 137.498, 1, 0, 0.0811606,-0.0770654) , 
0, 129.064, 1, 0, 0.641138,0.07502) , 
0, 117.468, 1, 0, 0.500853,0.0390876)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.303766,0.000852148) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.106265,-0.00977522) , 
5, 1.14243, 1, 0, 0.141863,-0.0559451) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661539,-0.00107046) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.838756,0.00916134) , 
3, 86.4602, 1, 0, 0.817334,0.11819) , 
0, 120.973, 1, 0, 0.575669,0.0558889) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.0048565) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0229352,-0.0210461) , 
9, -0.272892, 1, 0, 0.0138267,-0.105546) , 
0, 132.823, 1, 0, 0.499421,0.0339806)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418682,0.00324153) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.114519,-0.0175579) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.216585,-0.00177506) , 
10, 56.3777, 1, 0, 0.136681,-0.0693332) , 
6, 1.49616, 1, 0, 0.180792,-0.0493494) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.931264,0.0127075) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.844111,0.00692241) , 
7, 12, 1, 0, 0.880323,0.0288197) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0210286,-0.00920912) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.107248,-0.00985859) , 
9, -0.454319, 1, 0, 0.0809105,-0.0812642) , 
0, 128.879, 1, 0, 0.668145,0.0805068) , 
0, 121.965, 1, 0, 0.501122,0.0360033)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0522315,-0.01374) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0245912,-0.0170862) , 
5, 2.28535, 1, 0, 0.0390453,-0.0785318) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191277,0.000864219) , 
0, 113.444, 1, 0, 0.0819979,-0.0550145) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.864341,0.00941641) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.708854,0.00219785) , 
5, 1.99886, 1, 0, 0.800156,0.104582) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0142413,-0.0330965) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.10277,-0.00867664) , 
9, -0.272579, 1, 0, 0.0699303,-0.0799827) , 
0, 129.277, 1, 0, 0.644123,0.0651445) , 
0, 117.764, 1, 0, 0.500692,0.0344848)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0381424,-0.00611206) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0153783,-0.0158834) , 
5, 2.28539, 1, 0, 0.0266233,-0.0832848) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0738194,-0.00875262) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.144077,-0.00385072) , 
0, 113.304, 1, 0, 0.109751,-0.035641) , 
0, 110.61, 1, 0, 0.0640091,-0.0618574) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.838821,0.00836724) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.674915,0.00177019) , 
5, 2.28478, 1, 0, 0.788743,0.101598) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0604681,-0.0136911) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.244122,0.000735734) , 
1, 86.0401, 1, 0, 0.119772,-0.0664472) , 
0, 128.387, 1, 0, 0.627258,0.0610332) , 
0, 116.537, 1, 0, 0.499362,0.0331286)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0484922,-0.00517336) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00716956,-0.0114111) , 
5, 2.28557, 1, 0, 0.0275678,-0.0811901) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0801613,-0.0176693) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.150545,-0.00167585) , 
9, -0.0906965, 1, 0, 0.119218,-0.0355814) , 
0, 110.442, 1, 0, 0.0728997,-0.0586312) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.627096,-0.00285417) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.82752,0.00830556) , 
3, 86.4499, 1, 0, 0.80512,0.102962) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0111739,-0.0187958) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0916469,-0.0134922) , 
9, -0.272664, 1, 0, 0.0624015,-0.0787056) , 
0, 129.2, 1, 0, 0.642974,0.0633016) , 
0, 117.657, 1, 0, 0.498654,0.0324331)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0427783,-0.00681714) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0144776,-0.0162532) , 
5, 2.28564, 1, 0, 0.0284735,-0.0778203) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0804556,-0.00947242) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.130139,-0.00720092) , 
9, -0.0908232, 1, 0, 0.1081,-0.0452715) , 
0, 110.568, 1, 0, 0.0667146,-0.0621885) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.884817,0.0101634) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.756037,0.00369544) , 
7, 12, 1, 0, 0.807935,-0.00218183) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0317529,-0.0160285) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.102558,-0.0100175) , 
9, -0.0910115, 1, 0, 0.0708511,-0.066862) , 
0, 129.276, 1, 0, 0.64686,0.067135) , 
0, 117.764, 1, 0, 0.502492,0.0349532)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.162817,-0.0024779) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.711914,0.00685487) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.851748,0.0140175) , 
1, 134.375, 1, 0, 0.773139,0.135244) , 
0, 117.464, 1, 0, 0.657367,0.104496) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0705657,-0.014222) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.72964,0.00913454) , 
0, 116.534, 1, 0, 0.56443,0.0758353) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.458072,-0.00074378) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0517834,-0.0171749) , 
0, 128.238, 1, 0, 0.358266,-0.0338486) , 
7, 12, 1, 0, 0.424939,-0.0127757) , 
6, 1.86741, 1, 0, 0.500592,0.0351069)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.293635,0.000572568) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0859256,-0.00440495) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.14146,-0.0118247) , 
9, -0.454449, 1, 0, 0.122849,-0.0770329) , 
2, 2.11201, 1, 0, 0.166462,-0.0562763) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.910825,0.00974567) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.802905,0.00502076) , 
5, 2.28479, 1, 0, 0.878208,0.121423) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0129256,-0.0072813) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.103805,-0.0106698) , 
9, -0.454585, 1, 0, 0.0758485,-0.0714207) , 
0, 128.885, 1, 0, 0.661026,0.0692242) , 
0, 121.967, 1, 0, 0.492203,0.0263836)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.170902,-0.00494816) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.110249,-0.0134501) , 
7, 12, 1, 0, 0.128257,-0.00600139) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.347435,0.00195333) , 
1, 96.8161, 1, 0, 0.182119,-0.0412527) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.890677,0.00880606) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.485619,-0.000197739) , 
0, 127.614, 1, 0, 0.838809,0.111495) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00771413,-0.0383427) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0302992,-0.0285) , 
9, 0.0910203, 1, 0, 0.0187186,-0.0841522) , 
0, 132.33, 1, 0, 0.673869,0.072146) , 
0, 121.964, 1, 0, 0.502774,0.0326912)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0535282,-0.0196093) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.839227,0.0120638) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505024,0.00580093) , 
0, 126.419, 1, 0, 0.752412,0.135587) , 
0, 113.847, 1, 0, 0.636489,0.102751) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.69489,0.00957049) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.185832,-0.0266373) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413006,-0.000627191) , 
3, 86.4534, 1, 0, 0.375475,-0.0270194) , 
6, 1.56977, 1, 0, 0.434266,8.12001e-06) , 
7, 12, 1, 0, 0.507009,-0.0113058)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529224,0.00585614) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.351083,-0.000770981) , 
5, 1.04586, 1, 0, 0.439698,0.0347343) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.263408,0.000143896) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.139149,-0.00680543) , 
7, 12, 1, 0, 0.175642,-0.0112375) , 
6, 1.92058, 1, 0, 0.259179,-0.0327967) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.932581,0.0126078) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.836419,0.00715738) , 
7, 12, 1, 0, 0.87564,0.0567248) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00390502,-0.0339951) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.075425,-0.00802657) , 
9, -0.272664, 1, 0, 0.0495171,-0.0690299) , 
0, 129.677, 1, 0, 0.648109,0.0713104) , 
0, 122.944, 1, 0, 0.490904,0.0292304)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0435283,-0.0257959) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0197153,-0.0351663) , 
5, 2.28514, 1, 0, 0.0320603,-0.0676363) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.059791,-0.017526) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.165442,-0.00103344) , 
0, 114.173, 1, 0, 0.106855,-0.0322894) , 
0, 110.22, 1, 0, 0.068781,-0.0502825) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.718932,0.00210278) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.867187,0.00991766) , 
1, 63.8576, 1, 0, 0.806262,0.0903528) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00488445,-0.00744304) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.104458,-0.00459062) , 
9, -0.454365, 1, 0, 0.0759916,-0.0521415) , 
0, 129.065, 1, 0, 0.633889,0.0567185) , 
0, 117.468, 1, 0, 0.49388,0.0302083)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0388879,-0.00906469) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0117985,-0.0434852) , 
6, 2.24618, 1, 0, 0.02235,-0.0734241) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0837669,-0.0156578) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.149203,0.000131949) , 
9, -0.0907154, 1, 0, 0.120104,-0.02346) , 
0, 110.442, 1, 0, 0.0699013,-0.0491196) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.361888,-0.00129959) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.861204,0.00817036) , 
0, 120.809, 1, 0, 0.806692,0.0906752) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0152171,-0.030386) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0874118,-0.0103312) , 
9, -0.272508, 1, 0, 0.0609324,-0.0596388) , 
0, 129.205, 1, 0, 0.647904,0.0586702) , 
0, 117.658, 1, 0, 0.502266,0.0315106)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0840342,-0.0123783) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0430215,-0.0186919) , 
7, 12, 1, 0, 0.0550447,-0.0126807) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.793776,0.00457299) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.285928,-0.00459859) , 
0, 126.238, 1, 0, 0.585539,0.028762) , 
0, 118.737, 1, 0, 0.43191,0.00234471) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.760144,0.0121232) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536537,0.00301888) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.515633,0.00422345) , 
2, 1.94522, 1, 0, 0.527163,0.0332518) , 
6, 1.58959, 1, 0, 0.66665,0.0989519) , 
1, 100.329, 1, 0, 0.497231,0.0292274)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0998025,-0.00406091) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0576767,-0.00743153) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.491734,0.00476) , 
0, 116.039, 1, 0, 0.216959,-0.0114493) , 
9, -0.454471, 1, 0, 0.182998,-0.0349531) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.766726,0.00327911) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.896015,0.010309) , 
1, 78.3792, 1, 0, 0.829025,0.0923977) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00526521,-0.00700087) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0189917,-0.0215369) , 
9, -0.0913338, 1, 0, 0.012546,-0.076016) , 
0, 132.33, 1, 0, 0.658988,0.0573245) , 
0, 121.963, 1, 0, 0.493994,0.0253381)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0201473,-0.0466887) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0602265,-0.0180309) , 
3, 88.2525, 1, 0, 0.0491797,-0.0569146) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.145023,-0.000603877) , 
10, 71.1163, 1, 0, 0.0683821,-0.0470811) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.376937,-0.00431302) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.858513,0.00719914) , 
0, 121.03, 1, 0, 0.81104,0.0826909) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0220631,-0.0362374) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.145103,-0.000628579) , 
4, 81.6803, 1, 0, 0.0614679,-0.0528069) , 
0, 129.378, 1, 0, 0.64487,0.052653) , 
0, 117.9, 1, 0, 0.496875,0.0270493)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.150987,-0.00277958) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.714752,0.00499193) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.857272,0.0132852) , 
1, 127.483, 1, 0, 0.782558,0.117153) , 
0, 117.76, 1, 0, 0.660666,0.0898683) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0771448,-0.0169317) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.747291,0.00876076) , 
0, 119.963, 1, 0, 0.560469,0.0629505) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.370394,-0.0015287) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.145478,-0.00466718) , 
3, 95.5446, 1, 0, 0.342235,-0.0326963) , 
7, 12, 1, 0, 0.412231,-0.0206441) , 
6, 1.88772, 1, 0, 0.490514,0.0269353)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.137787,-0.00743701) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.633113,0.00367008) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.827011,0.0105449) , 
1, 88.5515, 1, 0, 0.781487,0.115006) , 
0, 117.464, 1, 0, 0.665922,0.0879267) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.104995,-0.0070112) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.760476,0.00879669) , 
0, 119.995, 1, 0, 0.567598,0.0673201) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.383085,-0.00151626) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.121539,-0.00504686) , 
3, 95.5432, 1, 0, 0.350716,-0.0331513) , 
7, 12, 1, 0, 0.420261,-0.0147982) , 
6, 1.89776, 1, 0, 0.502511,0.0288174)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0966313,-0.00347519) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.838889,0.00866443) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0218834,-0.0101543) , 
0, 132.924, 1, 0, 0.726112,0.0867946) , 
0, 117.465, 1, 0, 0.606052,0.0606182) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0662993,-0.0179674) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.720481,0.007689) , 
0, 119.963, 1, 0, 0.504351,0.0430006) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.130991,-0.00879699) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344724,-0.00193483) , 
3, 86.4535, 1, 0, 0.306838,-0.0429081) , 
7, 12, 1, 0, 0.369789,-0.0103544) , 
5, 1.99917, 1, 0, 0.493193,0.0242446)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.148457,-0.00180038) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.877241,0.0123163) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.723047,0.00661158) , 
2, 1.86184, 1, 0, 0.792205,0.114258) , 
0, 117.462, 1, 0, 0.673978,0.0894059) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.110659,-0.00366909) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.734623,0.00701419) , 
0, 119.997, 1, 0, 0.556165,0.0614169) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.160267,-0.0111912) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.383277,-0.00096595) , 
3, 84.6384, 1, 0, 0.358529,-0.0250123) , 
7, 12, 1, 0, 0.42318,-0.0124106) , 
6, 1.88099, 1, 0, 0.505074,0.0313899)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0881584,-0.0135467) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.254044,0.000990101) , 
4, 78.0622, 1, 0, 0.144264,-0.0275814) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.818656,0.00424133) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.919421,0.0101223) , 
1, 69.5893, 1, 0, 0.872968,0.0951709) , 
0, 121.121, 1, 0, 0.586677,0.0469444) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0471196,-0.00946648) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.344029,0.00468162) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0114265,-0.017304) , 
0, 136.947, 1, 0, 0.161481,-0.0154904) , 
9, -0.272628, 1, 0, 0.120118,-0.0467291) , 
0, 128.322, 1, 0, 0.499203,0.0293817)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.80893,0.0131894) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.646643,0.00303071) , 
2, 1.67744, 1, 0, 0.728521,0.109473) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0460806,-0.0204308) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.712466,0.00773178) , 
0, 114.996, 1, 0, 0.574777,0.0654979) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.403669,-0.000797349) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.17219,-0.00364245) , 
3, 95.5438, 1, 0, 0.377249,-0.0223482) , 
7, 12, 1, 0, 0.443993,-0.011626) , 
6, 1.48846, 1, 0, 0.497547,0.0265592)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.341511,0.00346461) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.203671,0.000842131) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.117991,-0.0127719) , 
7, 12, 1, 0, 0.143589,-0.00531286) , 
2, 1.97765, 1, 0, 0.185365,-0.0248114) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.893476,0.00831262) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499582,-0.000562297) , 
0, 127.617, 1, 0, 0.841256,0.0875633) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.010259,-0.0318411) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0414859,-0.00841899) , 
9, 0.0908556, 1, 0, 0.0258438,-0.0569363) , 
0, 132.329, 1, 0, 0.67225,0.0576136) , 
0, 121.963, 1, 0, 0.504846,0.0292737)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.130409,-0.0032783) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.657915,0.00466736) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.834595,0.0118177) , 
1, 88.5515, 1, 0, 0.792028,0.113423) , 
0, 117.451, 1, 0, 0.668637,0.0853799) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.159929,-0.00314299) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.766742,0.0083486) , 
0, 121.964, 1, 0, 0.561192,0.0543078) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.384827,-0.0013493) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.128005,-0.00487831) , 
3, 95.5385, 1, 0, 0.354039,-0.0300665) , 
7, 12, 1, 0, 0.419728,-0.00876658) , 
6, 1.89842, 1, 0, 0.501765,0.0259202)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.342338,0.00388763) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.200472,-0.000714012) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.121303,-0.0118109) , 
7, 12, 1, 0, 0.144314,-0.00343441) , 
2, 1.91263, 1, 0, 0.180067,-0.0278315) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.909465,0.0104515) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.787819,0.00389234) , 
7, 12, 1, 0, 0.838289,0.0433715) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0366342,-0.0241985) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.035023) , 
0, 144.907, 1, 0, 0.0208183,-0.0597306) , 
0, 132.336, 1, 0, 0.671192,0.0526761) , 
0, 121.967, 1, 0, 0.500608,0.0247131)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.628142,0.00383861) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.778588,0.0114815) , 
1, 127.673, 1, 0, 0.726502,0.101262) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0989157,-0.00858893) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.776508,0.00822964) , 
0, 119.995, 1, 0, 0.595796,0.0649626) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.169618,-0.0078295) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392432,-0.000591787) , 
3, 84.6366, 1, 0, 0.368297,-0.0227965) , 
7, 12, 1, 0, 0.443502,-0.012133) , 
6, 1.54204, 1, 0, 0.500571,0.0253812)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.775209,0.0098628) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.630025,0.00373738) , 
5, 0.998052, 1, 0, 0.725669,0.0972616) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0558472,-0.0123159) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.739159,0.00858128) , 
0, 114.996, 1, 0, 0.596625,0.0670613) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.390509,-0.000561657) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.136298,-0.00514572) , 
3, 95.5383, 1, 0, 0.360895,-0.0211497) , 
7, 12, 1, 0, 0.438281,-0.00942201) , 
6, 1.56977, 1, 0, 0.499533,0.0268742)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.781331,0.0116055) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51758,0.00405445) , 
6, 1.64984, 1, 0, 0.703878,0.0962759) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.110329,-0.00857208) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.847803,0.00521782) , 
0, 121.12, 1, 0, 0.550174,0.0253748) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0374388,-0.00350489) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.121864,-0.00652524) , 
9, -0.272531, 1, 0, 0.0849325,-0.0609252) , 
0, 128.319, 1, 0, 0.450535,0.00689224) , 
2, 1.87282, 1, 0, 0.496223,0.0230119)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.700567,0.00591201) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.759203,0.00945941) , 
9, -0.0953866, 1, 0, 0.731642,0.101021) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0923392,-0.00553636) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.82895,0.00511135) , 
0, 119.993, 1, 0, 0.53696,0.0277652) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0988695,-0.0296893) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191831,-0.00924176) , 
9, -0.0908857, 1, 0, 0.152333,-0.0658391) , 
0, 127.4, 1, 0, 0.453071,0.00734968) , 
6, 1.46072, 1, 0, 0.504371,0.0245995)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0739844,-0.0124514) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.061587,-0.000548374) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0201912,-0.0174811) , 
6, 2.75395, 1, 0, 0.0372042,-0.0266674) , 
6, 2.29816, 1, 0, 0.0521107,-0.03943) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.610563,-0.00329564) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.790129,0.00636494) , 
3, 86.4541, 1, 0, 0.768714,0.0630789) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00464051,-0.0114294) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.027065,-0.0161243) , 
9, -0.0907572, 1, 0, 0.0168861,-0.0566517) , 
0, 132.338, 1, 0, 0.637369,0.0421619) , 
0, 116.538, 1, 0, 0.509732,0.0243677)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.28936,-0.00607578) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0845224,-0.00202567) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.787425,0.00864052) , 
0, 116.488, 1, 0, 0.645577,0.0725016) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.240116,-0.00937263) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.477156,0.00191491) , 
3, 86.4534, 1, 0, 0.440193,0.000516576) , 
7, 12, 1, 0, 0.514291,-0.0076293) , 
9, -0.818161, 1, 0, 0.494138,0.0142458)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.206837,-0.00962278) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.290876,-0.00753992) , 
3, 83.9743, 1, 0, 0.251095,-0.082507) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0770285,-0.00380159) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.647272,0.00396891) , 
0, 119.889, 1, 0, 0.47256,0.0161881) , 
3, 86.4525, 1, 0, 0.438375,0.000953804) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.215779,-0.000429969) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.885872,0.0123221) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.673947,0.00592304) , 
6, 1.58676, 1, 0, 0.807918,0.107933) , 
0, 119.503, 1, 0, 0.688687,0.0848462) , 
1, 100.328, 1, 0, 0.508395,0.0244211)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0648496,-0.00386615) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.782357,0.00806658) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0227181,-0.0210659) , 
0, 133.891, 1, 0, 0.697461,0.0755053) , 
0, 112.151, 1, 0, 0.619524,0.0592112) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.234491,-0.00706623) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.431656,0.00146306) , 
3, 84.9637, 1, 0, 0.407641,-0.00194098) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.184346,-0.00389475) , 
3, 95.5385, 1, 0, 0.383915,-0.0159294) , 
5, 1.99921, 1, 0, 0.506931,0.0233031)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.771999,0.00959449) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.621532,0.00290847) , 
5, 0.981017, 1, 0, 0.722367,0.0850782) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.308805,-0.0069736) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505393,0.00375313) , 
3, 87.6111, 1, 0, 0.461756,0.0103995) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.223558,-0.00455019) , 
3, 95.5403, 1, 0, 0.438714,-0.0012729) , 
6, 1.54204, 1, 0, 0.495702,0.0160757)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55822,0.00560141) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.304955,0.00260059) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.154306,-0.0126198) , 
7, 12, 1, 0, 0.202796,-0.0088195) , 
6, 1.45571, 1, 0, 0.258044,-0.0200647) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.949441,0.0109477) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.869841,0.00703393) , 
6, 2.27032, 1, 0, 0.914749,0.103838) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.691544,0.00248839) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0146795,-0.0170531) , 
0, 132.313, 1, 0, 0.369868,-0.0123765) , 
0, 126.163, 1, 0, 0.657608,0.048994) , 
0, 122.781, 1, 0, 0.503051,0.0222811)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.081858,-0.00208881) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.824666,0.00850226) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502408,0.00379048) , 
0, 126.371, 1, 0, 0.734926,0.0756065) , 
0, 113.828, 1, 0, 0.623667,0.061799) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.749528,0.00903237) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.477994,0.00173178) , 
5, 1.14245, 1, 0, 0.616367,0.0556472) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.394239,-0.00152133) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.170368,-0.00925071) , 
3, 95.5436, 1, 0, 0.370385,-0.0245875) , 
2, 2.14392, 1, 0, 0.435307,-0.00341113) , 
7, 12, 1, 0, 0.500663,-0.00601372)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.252716,-0.00790928) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485296,-0.000371185) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372987,-0.00245309) , 
2, 2.7961, 1, 0, 0.429183,-0.0281397) , 
9, -0.867759, 1, 0, 0.364539,-0.0576783) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0217882,-0.00656038) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.123986,-0.000236635) , 
0, 110.441, 1, 0, 0.0725624,-0.0293227) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.797453,0.00601724) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0188761,-0.0242472) , 
0, 133.042, 1, 0, 0.67077,0.0477014) , 
0, 117.654, 1, 0, 0.530383,0.0296253) , 
9, -0.636343, 1, 0, 0.501472,0.0144061)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492146,0.00258389) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.132623,-0.0144744) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.257536,-0.00331451) , 
4, 38.6338, 1, 0, 0.211206,-0.0359027) , 
5, 1.1425, 1, 0, 0.274666,-0.0213058) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.943709,0.0103568) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.877932,0.00674616) , 
2, 2.49148, 1, 0, 0.909551,0.0921418) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553263,0.00574152) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.27043,-0.00810711) , 
6, 1.88326, 1, 0, 0.354576,-0.0177582) , 
0, 126.315, 1, 0, 0.655899,0.041912) , 
0, 122.947, 1, 0, 0.499636,0.0159997)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.2834,-0.00579363) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554884,0.00492852) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.867842,0.0121891) , 
0, 123.036, 1, 0, 0.755776,0.0973721) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622723,0.00718101) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391404,-0.000908323) , 
7, 12, 1, 0, 0.469665,-0.00739698) , 
6, 1.54204, 1, 0, 0.530062,0.032541) , 
9, -0.818161, 1, 0, 0.507057,0.0220579)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.397291,0.00256525) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.19127,0.000562959) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.11332,-0.0133704) , 
7, 12, 1, 0, 0.136904,-0.00415918) , 
5, 1.14244, 1, 0, 0.189862,-0.0221284) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.895014,0.00656969) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.636065,0.000747222) , 
0, 126.676, 1, 0, 0.837543,0.0620935) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0434891,-0.0174778) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00519085,-0.0164294) , 
0, 144.899, 1, 0, 0.0265119,-0.041542) , 
0, 132.33, 1, 0, 0.67498,0.0413208) , 
0, 121.964, 1, 0, 0.508731,0.0195769)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.165687,-0.0133118) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293437,0.00034957) , 
3, 87.9397, 1, 0, 0.257448,-0.0153895) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.167198,-0.00366745) , 
3, 93.7256, 1, 0, 0.240977,-0.0294399) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.869469,0.00627818) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.946519,0.00990878) , 
4, 68.2017, 1, 0, 0.910707,0.0889207) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.181876,-0.00718629) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413577,0.000591382) , 
9, -0.454558, 1, 0, 0.350032,-0.0210638) , 
0, 126.166, 1, 0, 0.650008,0.0377807) , 
0, 122.783, 1, 0, 0.490052,0.0114933)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.247733,-0.0202943) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393577,-0.00338056) , 
3, 83.704, 1, 0, 0.346906,-0.0458265) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626643,0.00478301) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.138933,-0.00301462) , 
0, 128.315, 1, 0, 0.54381,0.0324237) , 
3, 86.9495, 1, 0, 0.51034,0.0191228) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.222476,-0.00170289) , 
3, 97.3615, 1, 0, 0.493566,0.0101493)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0816932,-0.00571331) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.827794,0.00970341) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.678766,0.00489778) , 
5, 2.28481, 1, 0, 0.7831,0.0829943) , 
0, 116.534, 1, 0, 0.63492,0.0616961) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.274377,-0.00630589) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.516854,0.00368834) , 
3, 87.6102, 1, 0, 0.456633,0.00629852) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208794,-0.00618277) , 
3, 95.5436, 1, 0, 0.433362,-0.00619231) , 
7, 12, 1, 0, 0.505905,-0.0070247)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.108088,-0.00479279) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.803359,0.00564506) , 
0, 119.202, 1, 0, 0.584426,0.0373616) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0194021,-0.0237216) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0122489,-0.013614) , 
2, 2.78477, 1, 0, 0.0157831,-0.0444162) , 
0, 133.596, 1, 0, 0.518212,0.0278391) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.306827,-0.00233548) , 
3, 95.5425, 1, 0, 0.497564,0.0160287)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0979539,-0.000136135) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.824755,0.00927588) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.682689,0.00507253) , 
5, 2.28473, 1, 0, 0.778627,0.0797977) , 
0, 116.522, 1, 0, 0.637749,0.0631933) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.182692,-0.00635499) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302457,-0.00958422) , 
3, 83.9743, 1, 0, 0.242393,-0.0884136) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.513827,0.00308904) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.230115,-0.021103) , 
3, 95.7096, 1, 0, 0.480148,0.0123269) , 
3, 86.4544, 1, 0, 0.442484,-0.00363204) , 
7, 12, 1, 0, 0.511707,-0.00538248)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.113449,-0.00589448) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.845215,0.00409939) , 
0, 121.119, 1, 0, 0.543079,0.0138312) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0440954,-0.00684162) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0934168,-0.0108202) , 
9, -0.0913055, 1, 0, 0.0699078,-0.0587905) , 
0, 128.319, 1, 0, 0.451924,-0.000159069) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.793172,0.0114432) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505793,0.00025588) , 
5, 1.14161, 1, 0, 0.70358,0.0797815) , 
1, 131.816, 1, 0, 0.4975,0.0143184)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.106223,-0.0177608) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0222812,-0.0172882) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304059,0.00136231) , 
0, 110.118, 1, 0, 0.203917,-0.0118156) , 
3, 88.2728, 1, 0, 0.18018,-0.0251525) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897409,0.00675515) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.635159,0.000663704) , 
0, 126.675, 1, 0, 0.837493,0.0570872) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.0105814) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0252663,-0.0224181) , 
9, -0.272628, 1, 0, 0.0153386,-0.0468569) , 
0, 132.335, 1, 0, 0.662947,0.0350196) , 
0, 121.967, 1, 0, 0.494891,0.0140731)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.211205,0.0030502) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.777493,0.00532967) , 
0, 121.969, 1, 0, 0.601406,0.0432188) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402978,-0.00124355) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.148926,-0.0358712) , 
3, 95.539, 1, 0, 0.376287,-0.0224786) , 
7, 12, 1, 0, 0.451958,-0.00641053) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.782384,0.0098633) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565046,0.00102435) , 
5, 1.14229, 1, 0, 0.715944,0.0687176) , 
1, 131.862, 1, 0, 0.499083,0.0119423)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333146,-0.00248141) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.395229,-0.0048618) , 
9, -0.272714, 1, 0, 0.371401,-0.0523177) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693039,0.00935367) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.482616,0.00229596) , 
7, 12, 1, 0, 0.557999,-0.0014233) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.384092,-0.00571002) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302825,-0.0101551) , 
8, 2.15903, 1, 0, 0.343542,-0.052685) , 
8, 1.48808, 1, 0, 0.528763,0.028745) , 
8, -1.28032, 1, 0, 0.50407,0.0160248)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.110756,-0.00305063) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0188677,-0.00696849) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.301507,0.00190151) , 
0, 110.12, 1, 0, 0.207276,-0.00831207) , 
9, -0.454547, 1, 0, 0.179289,-0.0233662) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.916371,0.00914622) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.797198,0.00323017) , 
7, 12, 1, 0, 0.845601,0.0277302) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00547784,-0.00580983) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0353783,-0.0165663) , 
9, -0.272753, 1, 0, 0.0234546,-0.0374995) , 
0, 132.339, 1, 0, 0.678438,0.0382808) , 
0, 121.969, 1, 0, 0.509369,0.0174001)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.243642,-0.00770861) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.365853,-0.00514847) , 
3, 83.4743, 1, 0, 0.320813,-0.0568266) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.306844,-0.000799761) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.705189,0.00529535) , 
0, 122.949, 1, 0, 0.550545,0.0309112) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.26451,-0.00342225) , 
3, 97.006, 1, 0, 0.531436,0.0223779) , 
3, 86.4453, 1, 0, 0.502943,0.0116628)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0725051,-0.00641209) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.820582,0.00737762) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0591367,-0.0100225) , 
0, 129.757, 1, 0, 0.712233,0.0568704) , 
0, 112.483, 1, 0, 0.627468,0.0419434) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500918,0.0015621) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0776479,-0.0074951) , 
0, 128.233, 1, 0, 0.414848,0.000412106) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.21691,-0.00352973) , 
3, 95.5427, 1, 0, 0.393778,-0.00958882) , 
5, 1.71359, 1, 0, 0.490085,0.0116483)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.193015,-0.0027454) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.881639,0.00567027) , 
0, 122.459, 1, 0, 0.547369,0.0221318) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.107586,-0.00764738) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.164175,-0.0106509) , 
9, -0.0908406, 1, 0, 0.137178,-0.0567068) , 
0, 127.398, 1, 0, 0.4572,0.00480117) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.825841,0.0120508) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.569694,0.00257752) , 
6, 1.24779, 1, 0, 0.718619,0.07365) , 
1, 131.862, 1, 0, 0.502484,0.0167275)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0509462,-0.0196528) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0188387,-0.0109333) , 
5, 2.285, 1, 0, 0.035281,-0.0365417) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632339,0.00504888) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.41726,-0.00514345) , 
8, 1.58056, 1, 0, 0.609998,0.0331036) , 
0, 112.15, 1, 0, 0.519958,0.0221925) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.327871,-0.00330682) , 
3, 95.5436, 1, 0, 0.501664,0.0138805)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.279257,-0.0076071) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0802725,-0.00576473) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.026767,-0.00471867) , 
8, 0.788395, 1, 0, 0.0658759,-0.0301424) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.792131,0.00417402) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00911279,-0.0145556) , 
0, 132.922, 1, 0, 0.664527,0.0298554) , 
0, 117.464, 1, 0, 0.520209,0.0153916) , 
3, 84.6359, 1, 0, 0.50117,0.0079033)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.773873,0.00819176) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.26281,-0.00186033) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.222385,-0.00257686) , 
3, 93.7318, 1, 0, 0.25514,-0.0207463) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.905323,0.00698536) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.311411,-0.00459582) , 
0, 126.397, 1, 0, 0.632264,0.0270934) , 
0, 123.039, 1, 0, 0.472607,0.00684023) , 
6, 1.1251, 1, 0, 0.500804,0.0147395)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.154079,-0.0207992) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.346409,-0.00881471) , 
0, 123.864, 1, 0, 0.248705,-0.0660366) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492006,0.00194375) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.224635,-0.0170131) , 
3, 95.7102, 1, 0, 0.463648,0.00503704) , 
3, 86.4538, 1, 0, 0.430624,-0.0058827) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.771735,0.00879561) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507912,-0.000184167) , 
6, 1.56958, 1, 0, 0.672362,0.0529113) , 
1, 100.659, 1, 0, 0.49848,0.0106207)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.34746,-0.00415463) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266866,-0.00869482) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.478409,-0.00117733) , 
0, 123.815, 1, 0, 0.376191,-0.0300192) , 
8, -0.662568, 1, 0, 0.365219,-0.0611814) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0454306,-0.00673065) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.633806,0.0047344) , 
0, 112.487, 1, 0, 0.540191,0.0299336) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.325854,-0.0123561) , 
3, 95.5395, 1, 0, 0.521246,0.0215456) , 
9, -0.636378, 1, 0, 0.492673,0.00639586)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4135,-0.00250414) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.316264,-0.012645) , 
9, 0.636344, 1, 0, 0.378388,-0.0408453) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.571953,0.00448002) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.339895,-0.0102356) , 
3, 95.5431, 1, 0, 0.551344,0.0291797) , 
8, -1.09423, 1, 0, 0.517572,0.0155067) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.275735,-0.00762959) , 
8, 1.63147, 1, 0, 0.493456,0.00692194)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.275056,-0.00552472) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477017,-0.00206077) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28925,-0.00114876) , 
2, 2.90406, 1, 0, 0.392199,-0.0291612) , 
9, -0.867766, 1, 0, 0.3496,-0.0534071) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0270901,-0.0198759) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0141912,-0.00992681) , 
5, 2.28506, 1, 0, 0.0212246,-0.0492817) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.701123,0.00635291) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487175,0.000173436) , 
5, 1.99917, 1, 0, 0.608752,0.0322185) , 
0, 111.104, 1, 0, 0.527791,0.0209878) , 
9, -0.636362, 1, 0, 0.494567,0.00711673)    );
   return;
};
 
// Clean up
inline void ReadBDTG_UF_v1::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDTG_UF_v1::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
