// Class: ReadBDTG_UF_v1
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTG_UF_v1
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.10/09       [395785]
Creator        : xzuo
Date           : Wed May 22 21:32:32 2019
Host           : Linux cmsbuild49.cern.ch 2.6.32-696.10.2.el6.x86_64 #1 SMP Thu Sep 14 16:35:02 CEST 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/x/xzuo/h2mm_944/src/H2MuAnalyzer/TrainMVA
Training events: 65096
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
nCuts: "10" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for GradBoost algorithm]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 3
dimu_mass                     dimu_mass                     dimu_mass                     M(#mu#mu)                     GeV                               'F'    [100.245376587,159.985855103]
BDT_noMass_v3                 BDT_noMass_v3                 BDT_noMass_v3                 BDT v3 score                                                    'F'    [-0.895937144756,0.794644117355]
lep_ID                        lep_ID                        lep_ID                        lep_ID                                                          'I'    [11,13]
NSpec 5
event_wgt                     event_wgt                     event_wgt                     event weight                                                    'F'    [-1.52057862282,3.92260169983]
xsec_norm                     xsec_norm                     xsec_norm                     xsec normal                                                     'F'    [2.90000007226e-05,0.0557130016387]
Sample_ID                     Sample_ID                     Sample_ID                     Sample ID                                                       'F'    [-23230000,1302325]
lep_ID                        lep_ID                        lep_ID                        the Z decays to                                                 'F'    [11,13]
dimu_mass                     dimu_mass                     dimu_mass                     mass(#mu#mu)                  GeV                               'F'    [100.245376587,159.985855103]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTG_UF_v1Node
   
#ifndef BDTG_UF_v1Node__def
#define BDTG_UF_v1Node__def
   
class BDTG_UF_v1Node {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTG_UF_v1Node ( BDTG_UF_v1Node* left,BDTG_UF_v1Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTG_UF_v1Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTG_UF_v1Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTG_UF_v1Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTG_UF_v1Node*   fLeft;     // pointer to the left daughter node
   BDTG_UF_v1Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTG_UF_v1Node::~BDTG_UF_v1Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTG_UF_v1Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTG_UF_v1Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTG_UF_v1 : public IClassifierReader {

 public:

   // constructor
   ReadBDTG_UF_v1( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDTG_UF_v1" ),
        fNvars( 3 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "dimu_mass", "BDT_noMass_v3", "lep_ID" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'I';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTG_UF_v1() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[3];
   double fVmax[3];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[3];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTG_UF_v1Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTG_UF_v1::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTG_UF_v1Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTG_UF_v1Node*)current->GetRight();
         else current=(BDTG_UF_v1Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDTG_UF_v1::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00656914,-0.0711505) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0442767,-0.0658903) , 
0, 110.61, 1, 0, 0.0229514,-0.477049) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.139082,-0.0422601) , 
1, 0.1733, 1, 0, 0.0533103,-0.44669) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.32484,-0.00341283) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.864267,0.0186629) , 
0, 120.844, 1, 0, 0.787574,0.287574) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.299195,-0.0100801) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0122677,-0.0212116) , 
0, 134.128, 1, 0, 0.103702,-0.396298) , 
0, 128.384, 1, 0, 0.624295,0.124295) , 
0, 116.535, 1, 0, 0.49507,-0.00492964)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0125995,-0.056165) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.057516,-0.0515468) , 
1, -0.134542, 1, 0, 0.0345354,-0.433965) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.125648,-0.040365) , 
0, 112.09, 1, 0, 0.0639278,-0.405098) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.348533,-0.0133957) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.868024,0.0184701) , 
0, 120.847, 1, 0, 0.80303,0.295081) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333333,-0.0082315) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0086174,-0.0681163) , 
0, 134.137, 1, 0, 0.117411,-0.373847) , 
0, 128.388, 1, 0, 0.637399,0.133483) , 
0, 116.538, 1, 0, 0.503778,0.00799125)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0145855,-0.0591587) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0799372,-0.0529437) , 
0, 113.189, 1, 0, 0.0325029,-0.411081) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.134256,-0.0325795) , 
1, 0.167602, 1, 0, 0.0591858,-0.388033) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.337646,-0.0140576) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.860388,0.0188759) , 
0, 120.629, 1, 0, 0.809843,0.294807) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0232902,-0.0108279) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.200115,-0.0258556) , 
1, 0.0300679, 1, 0, 0.0737682,-0.392691) , 
0, 129.062, 1, 0, 0.635213,0.131702) , 
0, 117.466, 1, 0, 0.493564,0.00389478)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0230038,-0.0158215) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0737135,-0.0582992) , 
1, 0.0211174, 1, 0, 0.0414362,-0.375619) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.156375,-0.0359477) , 
0, 113.326, 1, 0, 0.0731532,-0.349771) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552018,0.00106677) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.897721,0.0199767) , 
1, -0.11898, 1, 0, 0.798686,0.276465) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.232064,-0.01161) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00745734,-0.0147231) , 
0, 134.805, 1, 0, 0.0728707,-0.384462) , 
0, 129.205, 1, 0, 0.635476,0.127846) , 
0, 117.658, 1, 0, 0.500643,0.0133236)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0476544,-0.0334024) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.194689,-0.0277536) , 
0, 114.785, 1, 0, 0.0797028,-0.329665) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47422,-0.00105193) , 
0, 118.016, 1, 0, 0.181261,-0.253352) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636831,0.00537422) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.924784,0.0187925) , 
1, -0.273786, 1, 0, 0.874729,0.339882) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.262544,-0.0216845) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00699922,-0.0183513) , 
0, 134.539, 1, 0, 0.0859346,-0.36634) , 
0, 128.883, 1, 0, 0.672302,0.158646) , 
0, 121.969, 1, 0, 0.502436,0.0161229)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.013478,-0.0785338) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0281923,-0.0589174) , 
1, -0.282509, 1, 0, 0.0221072,-0.362575) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.10982,-0.0419383) , 
0, 110.61, 1, 0, 0.0594013,-0.328365) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.444395,-0.00408684) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.880605,0.0173949) , 
0, 121.918, 1, 0, 0.798581,0.26387) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.31732,-0.00792819) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0114993,-0.0181968) , 
0, 134.125, 1, 0, 0.114536,-0.332299) , 
0, 128.38, 1, 0, 0.634162,0.120573) , 
0, 116.534, 1, 0, 0.502597,0.0178093)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00955364,-0.0714948) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0392844,-0.00487881) , 
1, -0.393518, 1, 0, 0.0241353,-0.340581) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.141788,-0.0287812) , 
1, 0.0190564, 1, 0, 0.068134,-0.29972) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483834,-0.0013168) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.881722,0.0170585) , 
1, -0.277275, 1, 0, 0.80588,0.263049) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.167268,-0.0354655) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00495814,-0.01217) , 
0, 137.605, 1, 0, 0.0681648,-0.364953) , 
0, 129.208, 1, 0, 0.642793,0.124217) , 
0, 117.658, 1, 0, 0.503583,0.021519)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0600352,-0.0133146) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.720707,0.00793975) , 
0, 121.021, 1, 0, 0.381269,-0.0787527) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.108884,-0.0203259) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.0645277) , 
0, 139.784, 1, 0, 0.0537595,-0.377468) , 
0, 128.238, 1, 0, 0.300429,-0.152486) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.137568,-0.0318308) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.916184,0.0190692) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.182916,-0.021876) , 
0, 129.285, 1, 0, 0.826011,0.286044) , 
0, 117.767, 1, 0, 0.703734,0.195906) , 
1, 0.0227113, 1, 0, 0.503666,0.0230795)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0292016,-0.0299541) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0661215,-0.0413715) , 
1, -0.114384, 1, 0, 0.0396366,-0.298145) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.158288,-0.0214555) , 
1, 0.176092, 1, 0, 0.0696627,-0.271181) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.384645,-0.00842263) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.863606,0.0167244) , 
0, 120.629, 1, 0, 0.814577,0.258622) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0165378,-0.0133438) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.206491,-0.0210417) , 
1, 0.0300679, 1, 0, 0.0757792,-0.329636) , 
0, 129.059, 1, 0, 0.648682,0.12653) , 
0, 117.464, 1, 0, 0.506385,0.0287907)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0809552,-0.0117238) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.750296,0.0115747) , 
0, 121.97, 1, 0, 0.373358,-0.079383) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0036985,-0.0109636) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0523287,-0.0267429) , 
1, -0.391041, 1, 0, 0.0258604,-0.370962) , 
0, 129.01, 1, 0, 0.289964,-0.149358) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.133886,-0.02982) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.905481,0.018008) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.188828,-0.0217084) , 
0, 129.064, 1, 0, 0.809489,0.259242) , 
0, 117.468, 1, 0, 0.691813,0.179856) , 
1, 0.0252653, 1, 0, 0.494644,0.0183259)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0692002,-0.0298595) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.732646,0.00855004) , 
0, 121.021, 1, 0, 0.387952,-0.0654314) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0187621,-0.0661796) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0589863,-0.0330596) , 
1, -0.472762, 1, 0, 0.0408246,-0.354012) , 
0, 128.235, 1, 0, 0.300746,-0.137929) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.102624,-0.033386) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.276943,-0.00885366) , 
1, 0.303242, 1, 0, 0.186596,-0.159423) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.940021,0.0188307) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.460516,-0.000312587) , 
0, 127.277, 1, 0, 0.838939,0.277476) , 
0, 119.998, 1, 0, 0.700751,0.184926) , 
1, 0.0279667, 1, 0, 0.501505,0.0241094)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0569878,-0.0375114) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.710711,0.00557682) , 
0, 121.021, 1, 0, 0.377493,-0.0721396) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.107214,-0.0364962) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.0515871) , 
0, 139.779, 1, 0, 0.0522032,-0.321089) , 
0, 128.235, 1, 0, 0.294951,-0.135311) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.136321,-0.0251659) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.912924,0.0173829) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.17654,-0.0232476) , 
0, 129.281, 1, 0, 0.82323,0.258508) , 
0, 117.763, 1, 0, 0.697169,0.179295) , 
1, 0.0260997, 1, 0, 0.497767,0.0233274)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0529071,-0.0378601) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.671432,0.00534491) , 
0, 121.986, 1, 0, 0.310554,-0.114888) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0130255,-0.0353253) , 
0, 129.024, 1, 0, 0.234189,-0.170483) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0324769,-0.0455701) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197133,-0.0159135) , 
0, 110.567, 1, 0, 0.110644,-0.189936) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.874025,0.0160747) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0348691,-0.04114) , 
0, 133.111, 1, 0, 0.783442,0.222528) , 
0, 117.762, 1, 0, 0.648505,0.139804) , 
1, -0.127491, 1, 0, 0.487268,0.0190511)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0637139,-0.0116183) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.713095,0.00703511) , 
0, 121.023, 1, 0, 0.369965,-0.06404) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.110413,-0.0114689) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.0587005) , 
0, 136.897, 1, 0, 0.0462445,-0.294257) , 
0, 128.238, 1, 0, 0.288726,-0.121814) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.113532,-0.0271265) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.911374,0.0166995) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.688294,0.00983746) , 
0, 125.438, 1, 0, 0.821039,0.244736) , 
0, 117.762, 1, 0, 0.687801,0.166197) , 
1, 0.0244913, 1, 0, 0.488355,0.0222577)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0132908,-0.0194413) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.205251,-0.0235951) , 
0, 114.067, 1, 0, 0.0908055,-0.226825) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.741771,0.008665) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0219417,-0.0196971) , 
0, 128.884, 1, 0, 0.440543,-0.027141) , 
0, 121.967, 1, 0, 0.293706,-0.110978) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.131121,-0.0216936) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.90963,0.0163173) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.707216,0.0104329) , 
0, 125.443, 1, 0, 0.826934,0.243122) , 
0, 117.76, 1, 0, 0.702697,0.173608) , 
1, 0.0279667, 1, 0, 0.500156,0.0326748)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0639575,-0.00909762) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.693547,0.00773371) , 
0, 121.986, 1, 0, 0.320317,-0.0930641) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0131264,-0.0332081) , 
0, 129.021, 1, 0, 0.244154,-0.14152) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.244621,-0.00980504) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.901549,0.0163673) , 
0, 120.967, 1, 0, 0.714691,0.183248) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0441864,-0.0183399) , 
0, 132.819, 1, 0, 0.654645,0.140157) , 
1, -0.128268, 1, 0, 0.495785,0.0311483)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0225203,-0.031246) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0354738,-0.0514113) , 
1, -0.399225, 1, 0, 0.0273932,-0.238379) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.577634,0.00147639) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00929702,-0.0580408) , 
0, 129.964, 1, 0, 0.372808,-0.0773411) , 
0, 118.702, 1, 0, 0.248122,-0.135472) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0377879,-0.0410006) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.193849,-0.0118189) , 
0, 110.218, 1, 0, 0.114729,-0.149857) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.870845,0.0149884) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0306038,-0.0170326) , 
0, 132.929, 1, 0, 0.782119,0.200768) , 
0, 117.468, 1, 0, 0.654456,0.133698) , 
1, -0.121548, 1, 0, 0.496392,0.0289911)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0152233,-0.0100125) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0690701,-0.00612412) , 
1, -0.399542, 1, 0, 0.0354325,-0.229663) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.676626,0.00701291) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0624604,-0.0240512) , 
0, 127.254, 1, 0, 0.387202,-0.0547783) , 
0, 119.987, 1, 0, 0.251875,-0.122057) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0375729,-0.0384747) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.213651,-0.00610037) , 
0, 110.215, 1, 0, 0.124644,-0.13062) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.870101,0.0146463) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0541462,-0.0293806) , 
0, 132.92, 1, 0, 0.783671,0.19797) , 
0, 117.463, 1, 0, 0.657981,0.1353) , 
1, -0.124837, 1, 0, 0.500125,0.0352638)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0169412,-0.0136841) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0308347,-0.0536099) , 
0, 110.259, 1, 0, 0.0243283,-0.224081) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.579933,0.00159565) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0023585,-0.0556335) , 
0, 129.959, 1, 0, 0.36834,-0.0675299) , 
0, 118.702, 1, 0, 0.243079,-0.124533) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0249909,-0.0424633) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204555,-0.00568918) , 
0, 110.442, 1, 0, 0.116626,-0.133951) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.896472,0.0152792) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.138889,-0.0143887) , 
0, 129.208, 1, 0, 0.780691,0.191676) , 
0, 117.658, 1, 0, 0.647847,0.126535) , 
1, -0.128216, 1, 0, 0.491457,0.0295302)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0497707,-0.0432686) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.153972,-0.0080238) , 
1, -0.406197, 1, 0, 0.111576,-0.177723) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374655,-0.000565848) , 
1, 0.172717, 1, 0, 0.189911,-0.12647) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.630588,0.00369446) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.926523,0.0159696) , 
1, -0.271485, 1, 0, 0.876584,0.241897) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.244443,-0.0133902) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00846504,-0.032131) , 
0, 134.535, 1, 0, 0.0851507,-0.202742) , 
0, 128.88, 1, 0, 0.665625,0.123377) , 
0, 121.967, 1, 0, 0.500627,0.0367189)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0804434,-0.0225268) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.764099,0.00652891) , 
0, 121.018, 1, 0, 0.433218,-0.00980857) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.13168,-0.00662393) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00231855,-0.0210913) , 
0, 136.895, 1, 0, 0.0561075,-0.214871) , 
0, 128.238, 1, 0, 0.3404,-0.0602804) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.225218,-0.00670623) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9464,0.016341) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59918,0.00646663) , 
0, 126.864, 1, 0, 0.865399,0.242695) , 
0, 119.503, 1, 0, 0.74536,0.186526) , 
1, 0.182598, 1, 0, 0.495215,0.0340725)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0396282,-0.00490247) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.160492,-0.00493808) , 
1, -0.495074, 1, 0, 0.120175,-0.155799) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.370908,-0.0012844) , 
1, 0.179099, 1, 0, 0.192174,-0.114583) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.623698,0.0031182) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.924836,0.0153113) , 
1, -0.271887, 1, 0, 0.875189,0.228765) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.272245,-0.0078168) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00778218,-0.0315759) , 
0, 134.536, 1, 0, 0.0947733,-0.180012) , 
0, 128.88, 1, 0, 0.666891,0.11966) , 
0, 121.967, 1, 0, 0.500323,0.0374687)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0713141,-0.0151536) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.245543,-0.0102601) , 
1, -0.00258376, 1, 0, 0.124334,-0.155599) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.452535,0.00601904) , 
1, 0.326558, 1, 0, 0.187197,-0.113514) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.643289,0.0029593) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.930218,0.0154155) , 
1, -0.27389, 1, 0, 0.881952,0.230037) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.243669,-0.00507456) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00996507,-0.0411829) , 
0, 134.53, 1, 0, 0.084091,-0.18126) , 
0, 128.875, 1, 0, 0.673295,0.122474) , 
0, 121.964, 1, 0, 0.511391,0.0438736)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.030105,-0.00948766) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.114468,-0.0121975) , 
1, -0.471203, 1, 0, 0.0798705,-0.175002) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.738732,0.0065973) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0254008,-0.0103805) , 
0, 128.878, 1, 0, 0.428404,-0.0111686) , 
0, 121.964, 1, 0, 0.28217,-0.0799081) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.122641,-0.0191357) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.913136,0.0145646) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.192562,-0.0157715) , 
0, 129.248, 1, 0, 0.824198,0.19836) , 
0, 117.745, 1, 0, 0.700363,0.144265) , 
1, 0.0295865, 1, 0, 0.490271,0.0316451)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0163721,-0.0205359) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.063795,-0.0341567) , 
1, 0.0248511, 1, 0, 0.0328291,-0.170542) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.188649,-0.00520468) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.570107,0.00575575) , 
1, 0.0211551, 1, 0, 0.359913,-0.0397075) , 
0, 114.066, 1, 0, 0.177464,-0.112688) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.641587,0.0038299) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.926581,0.0147985) , 
1, -0.27389, 1, 0, 0.878314,0.215171) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.269153,-0.00634646) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00783577,-0.0317591) , 
0, 134.532, 1, 0, 0.0907353,-0.160431) , 
0, 128.874, 1, 0, 0.672045,0.1168) , 
0, 121.964, 1, 0, 0.501316,0.0375806)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0203522,-0.0244907) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0778172,-0.0289493) , 
0, 113.073, 1, 0, 0.0395908,-0.169395) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647144,0.00418207) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0155166,-0.0469783) , 
0, 129.958, 1, 0, 0.436891,-0.0121589) , 
0, 118.702, 1, 0, 0.296751,-0.0676211) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.133851,-0.0143539) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.911339,0.0142447) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.19374,-0.0134718) , 
0, 129.065, 1, 0, 0.821569,0.187994) , 
0, 117.468, 1, 0, 0.696977,0.139164) , 
1, 0.0252653, 1, 0, 0.497154,0.0359214)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0664636,-0.0161916) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.14776,-0.0229805) , 
1, -0.712816, 1, 0, 0.119696,-0.168815) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0588124,-0.0146451) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.563555,0.00307376) , 
0, 117.655, 1, 0, 0.420185,-0.00165889) , 
1, -0.500163, 1, 0, 0.343645,-0.0442364) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.168353,-0.00976847) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.813818,0.0112377) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.91676,0.0156438) , 
1, 0.460561, 1, 0, 0.8639,0.213442) , 
0, 117.896, 1, 0, 0.751921,0.168749) , 
1, 0.182048, 1, 0, 0.501275,0.0379947)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0143239,-0.0423251) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0625114,-0.0293875) , 
1, 0.0234287, 1, 0, 0.0321093,-0.151774) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.158045,-0.0108331) , 
0, 113.448, 1, 0, 0.0678387,-0.12875) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.46592,-0.00451776) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.861622,0.0124367) , 
1, -0.42723, 1, 0, 0.814869,0.167302) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.157,-0.0125236) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00357395,-0.0405813) , 
0, 137.659, 1, 0, 0.0653618,-0.156214) , 
0, 129.285, 1, 0, 0.648732,0.095591) , 
0, 117.767, 1, 0, 0.50323,0.039398)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00694687,-0.0130515) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.094555,-0.00347606) , 
0, 111.685, 1, 0, 0.0497042,-0.15147) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.706557,0.00682795) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0809902,-0.0166407) , 
0, 127.177, 1, 0, 0.428604,-0.0114913) , 
0, 119.887, 1, 0, 0.279302,-0.0666485) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.144211,-0.0101031) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.903234,0.0127699) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.238144,-0.00802233) , 
0, 129.058, 1, 0, 0.815949,0.170395) , 
0, 117.464, 1, 0, 0.698929,0.131028) , 
1, 0.0280812, 1, 0, 0.485397,0.0304382)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0628467,-0.0082733) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191143,-0.0116015) , 
1, -0.227073, 1, 0, 0.123342,-0.126685) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437227,0.00523533) , 
1, 0.324317, 1, 0, 0.186247,-0.0909428) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673714,0.00280358) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.93699,0.0141455) , 
1, -0.123526, 1, 0, 0.868294,0.185034) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.281457,-0.00362583) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00856068,-0.0140385) , 
0, 134.54, 1, 0, 0.0917345,-0.126004) , 
0, 128.885, 1, 0, 0.661192,0.102083) , 
0, 121.969, 1, 0, 0.492714,0.0336105)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00425183,-0.0206771) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0926472,-0.0174766) , 
0, 110.318, 1, 0, 0.054181,-0.136477) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.715169,0.00692059) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.091344,-0.0091528) , 
0, 127.181, 1, 0, 0.430857,-0.00718733) , 
0, 119.887, 1, 0, 0.291147,-0.0551409) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.151758,-0.00955596) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.909735,0.0127626) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.190165,-0.0117106) , 
0, 129.275, 1, 0, 0.822293,0.165952) , 
0, 117.763, 1, 0, 0.703258,0.128144) , 
1, 0.0288994, 1, 0, 0.498082,0.0368925)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0444242,-0.0288911) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137469,-0.00476583) , 
1, -0.30563, 1, 0, 0.0814163,-0.137511) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0781702,-0.0257763) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51973,0.0035088) , 
0, 112.675, 1, 0, 0.32892,-0.0157085) , 
1, 0.0255744, 1, 0, 0.181516,-0.0882492) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.623189,0.00228573) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.927748,0.0137002) , 
1, -0.275489, 1, 0, 0.87896,0.185746) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266135,-0.00600513) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00823614,-0.0418913) , 
0, 134.537, 1, 0, 0.0909299,-0.125341) , 
0, 128.882, 1, 0, 0.671007,0.103653) , 
0, 121.969, 1, 0, 0.503366,0.0379303)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0834237,-0.0105139) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.257356,-0.00756229) , 
1, 0.10825, 1, 0, 0.116249,-0.117317) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404145,0.00377425) , 
1, 0.329113, 1, 0, 0.170224,-0.0879687) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.50318,-0.00265223) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.887368,0.0130261) , 
1, -0.426175, 1, 0, 0.842716,0.171001) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.010564) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0589502,-0.0294908) , 
1, -0.118122, 1, 0, 0.0222635,-0.142665) , 
0, 132.334, 1, 0, 0.671266,0.105454) , 
0, 121.965, 1, 0, 0.498631,0.03881)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0405575,-0.0406663) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137313,-0.01377) , 
1, -0.407422, 1, 0, 0.0991954,-0.120156) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.778669,0.00687325) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0394192,-0.0354919) , 
0, 128.883, 1, 0, 0.498947,0.021209) , 
0, 121.969, 1, 0, 0.33655,-0.0362198) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.160071,-0.00778011) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.80718,0.0102718) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.902194,0.0144789) , 
1, 0.458065, 1, 0, 0.852804,0.176362) , 
0, 117.464, 1, 0, 0.743211,0.142118) , 
1, 0.178872, 1, 0, 0.496505,0.0339275)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0824443,-0.0172325) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.236123,-0.00884316) , 
1, -0.0108614, 1, 0, 0.127874,-0.0993288) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447245,0.0049428) , 
1, 0.32111, 1, 0, 0.195269,-0.0670493) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.645312,0.00335284) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.930242,0.0132002) , 
1, -0.271785, 1, 0, 0.884884,0.177637) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.247255,-0.00315031) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0109147,-0.0373024) , 
0, 134.542, 1, 0, 0.0886692,-0.108906) , 
0, 128.883, 1, 0, 0.675356,0.102232) , 
0, 121.969, 1, 0, 0.509668,0.0438093)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0666414,-0.0143362) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.224216,-0.0073393) , 
1, -0.0113535, 1, 0, 0.0988779,-0.108324) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.797713,0.00864887) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0244007,-0.00802767) , 
0, 128.88, 1, 0, 0.508142,0.0298717) , 
0, 121.967, 1, 0, 0.345211,-0.0251449) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.179857,-0.00341163) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.798999,0.0095503) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.904348,0.0138832) , 
1, 0.461095, 1, 0, 0.849183,0.167941) , 
0, 117.464, 1, 0, 0.744408,0.138578) , 
1, 0.182983, 1, 0, 0.499203,0.0380117)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0692946,-0.00297679) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.154423,-0.0201867) , 
1, -0.718117, 1, 0, 0.109833,-0.146595) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.036761,-0.0136664) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447672,0.000772033) , 
0, 118.721, 1, 0, 0.305274,-0.0302397) , 
1, -0.616504, 1, 0, 0.252147,-0.0618684) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.212025,-0.0103154) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459936,0.0060941) , 
1, 0.36993, 1, 0, 0.293861,-0.0248819) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.918985,0.0130279) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.056816,-0.027381) , 
0, 132.329, 1, 0, 0.818761,0.152412) , 
0, 121.963, 1, 0, 0.665346,0.100593) , 
1, -0.127491, 1, 0, 0.500723,0.0358667)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0228448,-0.00580073) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.215629,-0.0110301) , 
0, 114.064, 1, 0, 0.101364,-0.0984029) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.789821,0.00685965) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0399798,-0.0325986) , 
0, 128.873, 1, 0, 0.514192,0.0298097) , 
0, 121.963, 1, 0, 0.348938,-0.0215135) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.190078,-0.0017981) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.806061,0.00945791) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.904833,0.0136684) , 
1, 0.457986, 1, 0, 0.852559,0.159101) , 
0, 117.757, 1, 0, 0.74598,0.131843) , 
1, 0.178799, 1, 0, 0.5086,0.0401557)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0966943,-0.00938195) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25939,-0.00359005) , 
1, -0.13738, 1, 0, 0.133104,-0.0956799) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.816479,0.0100301) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.174017,-0.0098133) , 
0, 126.302, 1, 0, 0.432871,0.0119691) , 
0, 122.936, 1, 0, 0.29312,-0.0382167) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.145384,-0.00630444) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.918609,0.01225) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.220237,-0.00568024) , 
0, 129.065, 1, 0, 0.829556,0.149458) , 
0, 117.468, 1, 0, 0.709865,0.117546) , 
1, 0.0295865, 1, 0, 0.505456,0.0411458)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0796342,-0.0123755) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.125255,-0.0231142) , 
1, -0.718307, 1, 0, 0.102586,-0.142062) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0248427,-0.0421708) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.383753,8.43655e-06) , 
0, 118.964, 1, 0, 0.25404,-0.0401574) , 
1, -0.616791, 1, 0, 0.199521,-0.0768405) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0545641,-0.0183736) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.19249,-0.00177917) , 
0, 111.67, 1, 0, 0.10739,-0.0622092) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.87749,0.0111452) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.132048,-0.0137969) , 
0, 129.064, 1, 0, 0.75793,0.119376) , 
0, 117.468, 1, 0, 0.623666,0.0818992) , 
1, -0.281802, 1, 0, 0.500853,0.0359355)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.084907,-0.0121139) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.122314,-0.00671976) , 
1, -0.718373, 1, 0, 0.104055,-0.133401) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0349342,-0.00798139) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439791,0.000625844) , 
0, 118.734, 1, 0, 0.299608,-0.0294982) , 
1, -0.616816, 1, 0, 0.243028,-0.0595604) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228926,-0.006412) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.905928,0.0121128) , 
0, 120.969, 1, 0, 0.716523,0.109711) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0340897,-0.0119148) , 
0, 132.823, 1, 0, 0.656017,0.0877958) , 
1, -0.128268, 1, 0, 0.499421,0.0319218)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0722999,-0.0145204) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.177805,-0.0106207) , 
1, -0.674394, 1, 0, 0.139899,-0.103089) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0572225,-0.0181715) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.517143,0.0042516) , 
0, 120.002, 1, 0, 0.35836,-0.00110353) , 
1, -0.408539, 1, 0, 0.238132,-0.0572303) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0718577,-0.0111607) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.519441,0.00340419) , 
0, 114.064, 1, 0, 0.291774,-0.0220705) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.920282,0.0123375) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0468118,-0.0115885) , 
0, 132.332, 1, 0, 0.808646,0.134327) , 
0, 121.963, 1, 0, 0.660692,0.0895581) , 
1, -0.130004, 1, 0, 0.501122,0.0341269)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.069388,-0.00614234) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.172499,-0.014157) , 
1, -0.707916, 1, 0, 0.12798,-0.112902) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.053973,-0.0123744) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525041,0.00272695) , 
0, 119.999, 1, 0, 0.361132,-0.0100732) , 
1, -0.556171, 1, 0, 0.298304,-0.0377826) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0766747,-0.0175152) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.711248,0.00712049) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.864482,0.0121963) , 
1, 0.375848, 1, 0, 0.785988,0.124887) , 
0, 112.487, 1, 0, 0.702146,0.102135) , 
1, 0.0280292, 1, 0, 0.500692,0.0323376)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.109542,-0.00722432) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.750862,0.00343532) , 
0, 122.459, 1, 0, 0.374397,-0.0126252) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.159898,-0.00777584) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00131386,-0.0226427) , 
0, 136.284, 1, 0, 0.0683496,-0.112851) , 
0, 127.398, 1, 0, 0.29071,-0.0400317) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.137323,-0.00748751) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.911476,0.0110745) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.188129,-0.0079856) , 
0, 129.276, 1, 0, 0.821721,0.125541) , 
0, 117.762, 1, 0, 0.702759,0.0973641) , 
1, 0.0280292, 1, 0, 0.499362,0.0295424)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0461156,-0.00871455) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.532964,5.72329e-05) , 
0, 119.098, 1, 0, 0.166817,-0.0703166) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.826882,0.00607669) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.203142,-0.0107028) , 
0, 126.315, 1, 0, 0.493279,0.0224868) , 
0, 122.947, 1, 0, 0.346944,-0.0191118) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.177054,-0.00288712) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.777882,0.00694421) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.902759,0.0124852) , 
1, 0.402211, 1, 0, 0.851403,0.132146) , 
0, 117.893, 1, 0, 0.73853,0.107539) , 
1, 0.178872, 1, 0, 0.498654,0.0299557)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.085354,-0.0062091) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0374733,-0.00683135) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421231,0.000370523) , 
0, 118.983, 1, 0, 0.283108,-0.0283057) , 
1, -0.681196, 1, 0, 0.245288,-0.0481543) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0441323,-0.0318298) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.181629,-0.00267356) , 
0, 110.55, 1, 0, 0.109768,-0.0535122) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.898694,0.0107072) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.136402,-0.0124665) , 
0, 129.253, 1, 0, 0.793183,0.113051) , 
0, 117.75, 1, 0, 0.660719,0.0807663) , 
1, -0.12425, 1, 0, 0.502492,0.0316639)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0379617,-0.034871) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.12445,-0.00286079) , 
1, -0.471891, 1, 0, 0.0879381,-0.0803858) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.742489,0.00585371) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0289076,-0.0140579) , 
0, 128.88, 1, 0, 0.447544,0.00904641) , 
0, 121.967, 1, 0, 0.301751,-0.0272116) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.272077,-0.00119387) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.945188,0.0121444) , 
0, 120.837, 1, 0, 0.755008,0.111301) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.260373,-0.0067015) , 
0, 128.091, 1, 0, 0.694749,0.0911494) , 
1, 0.0280292, 1, 0, 0.500592,0.0326742)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0292008,-0.00637862) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.160407,-0.0115064) , 
1, -0.446084, 1, 0, 0.118414,-0.0801402) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.382842,0.000698403) , 
1, 0.328174, 1, 0, 0.166462,-0.0645099) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.682102,0.00275549) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.942694,0.0120217) , 
1, -0.122438, 1, 0, 0.878208,0.13029) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.22753,-0.00749836) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00829056,-0.0136617) , 
0, 134.539, 1, 0, 0.0758485,-0.0895234) , 
0, 128.885, 1, 0, 0.661026,0.0707911) , 
0, 121.967, 1, 0, 0.492203,0.024605)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0325521,-0.00969422) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335032,-0.00493171) , 
0, 118.013, 1, 0, 0.101252,-0.0785363) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.785985,0.00545854) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0403426,-0.0283767) , 
0, 128.875, 1, 0, 0.511409,0.0234438) , 
0, 121.964, 1, 0, 0.345097,-0.0179074) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.182917,0.000344343) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.796445,0.00737617) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.90107,0.0119028) , 
1, 0.403502, 1, 0, 0.859011,0.126022) , 
0, 117.762, 1, 0, 0.744646,0.105034) , 
1, 0.179887, 1, 0, 0.502774,0.03061)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0630934,-0.0358431) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.143252,-0.00698717) , 
1, -0.713059, 1, 0, 0.111618,-0.0997673) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0241696,-0.0349551) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.427546,0.00132991) , 
0, 118.734, 1, 0, 0.283158,-0.0218356) , 
1, -0.560616, 1, 0, 0.202881,-0.0583057) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0484923,-0.00679589) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.813808,0.00966274) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0997355,-0.0126011) , 
0, 129.753, 1, 0, 0.715891,0.0929213) , 
0, 112.486, 1, 0, 0.628694,0.070503) , 
1, -0.28118, 1, 0, 0.507009,0.0336934)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0907039,-0.00787349) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.27484,-0.00485361) , 
1, -0.112137, 1, 0, 0.150361,-0.073167) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.847853,0.00978815) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.194795,-0.00886062) , 
0, 126.311, 1, 0, 0.487189,0.0276678) , 
0, 122.944, 1, 0, 0.335704,-0.0176815) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.160648,-0.00338108) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.80184,0.0076342) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.905105,0.0119383) , 
1, 0.456448, 1, 0, 0.851296,0.119319) , 
0, 117.763, 1, 0, 0.737316,0.0962418) , 
1, 0.179081, 1, 0, 0.490904,0.0263432)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.110153,-0.0146838) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.784118,0.00521373) , 
0, 122.018, 1, 0, 0.431323,0.00690123) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0771426,-0.00582754) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.0172872) , 
0, 137.495, 1, 0, 0.0298174,-0.0883636) , 
0, 129.05, 1, 0, 0.338618,-0.0150948) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.139537,-0.00664619) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.788744,0.00691284) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.896191,0.0113985) , 
1, 0.403622, 1, 0, 0.849786,0.114353) , 
0, 117.464, 1, 0, 0.739901,0.0915246) , 
1, 0.181033, 1, 0, 0.49388,0.0261578)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0866558,-0.00665707) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.178287,-0.0102962) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.294479,-0.000615917) , 
1, -0.455174, 1, 0, 0.237107,-0.0290517) , 
1, -0.6668, 1, 0, 0.195591,-0.0538093) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0322647,-0.0355484) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.170042,-0.00235842) , 
0, 110.442, 1, 0, 0.10046,-0.0482357) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.860803,0.00936916) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0258904,-0.0258559) , 
0, 133.052, 1, 0, 0.766781,0.0920622) , 
0, 117.658, 1, 0, 0.627504,0.0627366) , 
1, -0.278761, 1, 0, 0.502266,0.0289429)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0972132,-0.00636504) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.190293,-0.0044197) , 
1, -0.629223, 1, 0, 0.147826,-0.0685088) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0364361,-0.0110479) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.52173,0.00310691) , 
0, 118.983, 1, 0, 0.362944,0.00323687) , 
1, -0.406955, 1, 0, 0.243349,-0.0366502) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.288672,-0.00246007) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.90559,0.010393) , 
0, 121.79, 1, 0, 0.71688,0.0828587) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0284191,-0.0308407) , 
0, 133.379, 1, 0, 0.656533,0.0658535) , 
1, -0.127491, 1, 0, 0.497231,0.0263334)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0766252,-0.00611307) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0426428,-0.00893449) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.415035,-9.77717e-06) , 
0, 119.984, 1, 0, 0.276398,-0.0263623) , 
1, -0.681137, 1, 0, 0.24136,-0.0425159) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.223882,-0.00393647) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.905625,0.0103895) , 
0, 120.974, 1, 0, 0.71295,0.0814556) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0200367,-0.0294218) , 
0, 132.823, 1, 0, 0.654402,0.0651868) , 
1, -0.124837, 1, 0, 0.493994,0.0233597)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0147113,-0.0180921) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0986357,-0.0168595) , 
0, 113.836, 1, 0, 0.0409221,-0.0756873) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.753887,0.00525479) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.149185,-0.0154963) , 
0, 126.761, 1, 0, 0.497547,0.0158364) , 
0, 119.376, 1, 0, 0.342697,-0.0152011) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.171679,-0.000331323) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.810468,0.00705051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.902379,0.0118122) , 
1, 0.45482, 1, 0, 0.854947,0.106229) , 
0, 117.896, 1, 0, 0.739009,0.0878993) , 
1, 0.177825, 1, 0, 0.496875,0.0249082)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0228869,-0.0256499) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.1504,-0.010863) , 
0, 113.997, 1, 0, 0.0622564,-0.065971) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.784365,0.00472448) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.175199,-0.00534576) , 
0, 126.878, 1, 0, 0.541571,0.0274955) , 
0, 119.515, 1, 0, 0.390468,-0.00196977) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.729269,0.00702729) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.84044,0.0131841) , 
1, 0.544057, 1, 0, 0.776075,0.10351) , 
1, 0.335197, 1, 0, 0.490514,0.0253972)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.10001,-0.00422448) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0269198,-0.0277178) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.276246,-0.00322316) , 
0, 119.985, 1, 0, 0.174231,-0.0497544) , 
1, -0.686561, 1, 0, 0.148,-0.0722306) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0228836,-0.0215668) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.146211,-0.00241099) , 
0, 110.218, 1, 0, 0.0841382,-0.0431214) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.858736,0.00858611) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.114801,-0.00907425) , 
0, 129.059, 1, 0, 0.726784,0.0762345) , 
0, 117.465, 1, 0, 0.590293,0.0508846) , 
1, -0.435305, 1, 0, 0.502511,0.02645)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0725664,-0.00711872) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.122877,-0.0053961) , 
1, -0.695269, 1, 0, 0.0968535,-0.100803) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.227257,-0.0043023) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.575637,0.00673006) , 
1, 0.41122, 1, 0, 0.294939,-0.0204225) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.898146,0.00994758) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0737701,-0.010339) , 
0, 129.542, 1, 0, 0.708229,0.0766541) , 
0, 122.779, 1, 0, 0.5491,0.0392766) , 
1, -0.583986, 1, 0, 0.493193,0.0219601)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0960217,-0.00939387) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.200602,-0.00374198) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.165192,-0.00605046) , 
0, 124.982, 1, 0, 0.185598,-0.0393139) , 
1, -0.680952, 1, 0, 0.155672,-0.0613211) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0389569,-0.00301952) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.17112,0.00159993) , 
0, 111.669, 1, 0, 0.0937672,-0.0306767) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.864828,0.00867759) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.106379,-0.00687984) , 
0, 129.064, 1, 0, 0.731055,0.075954) , 
0, 117.468, 1, 0, 0.594869,0.0531674) , 
1, -0.430364, 1, 0, 0.505074,0.0297599)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0828273,-0.0265702) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.162852,-0.011324) , 
1, -0.70074, 1, 0, 0.135649,-0.0665505) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0614015,-0.00769313) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489529,0.00121483) , 
0, 119.995, 1, 0, 0.335144,-0.00535763) , 
1, -0.473929, 1, 0, 0.245948,-0.0327173) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.155785,-0.00421841) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.886744,0.00921599) , 
0, 119.196, 1, 0, 0.714545,0.0757925) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0341446,-0.00947396) , 
0, 133.599, 1, 0, 0.654579,0.0619003) , 
1, -0.127391, 1, 0, 0.499203,0.0259232)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.130214,-0.00397713) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.828104,0.00686214) , 
0, 122.017, 1, 0, 0.487486,0.0191742) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0161761,-0.00914091) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0867434,-0.0075816) , 
1, -0.222096, 1, 0, 0.0448492,-0.0722207) , 
0, 129.048, 1, 0, 0.396635,0.000415448) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.731708,0.00670991) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.857178,0.0124771) , 
1, 0.544043, 1, 0, 0.788624,0.0970801) , 
1, 0.335197, 1, 0, 0.497547,0.0253004)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0123795,-0.0181909) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191549,-0.00600397) , 
0, 110.117, 1, 0, 0.124004,-0.0459592) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.431828,0.00266557) , 
1, 0.32111, 1, 0, 0.185365,-0.032181) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475596,-0.00261938) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.887245,0.00902791) , 
1, -0.429144, 1, 0, 0.841256,0.0920993) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0478085,-0.0248783) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.0134986) , 
0, 144.897, 1, 0, 0.0258438,-0.0709136) , 
0, 132.329, 1, 0, 0.67225,0.0583124) , 
0, 121.963, 1, 0, 0.504846,0.0271984)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0702173,-0.0048872) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0222122,-0.0298957) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.287973,-0.00181982) , 
0, 119.994, 1, 0, 0.181805,-0.0364072) , 
1, -0.68658, 1, 0, 0.141992,-0.0670543) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.033427,-0.0135379) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.348664,0.000238527) , 
0, 110.117, 1, 0, 0.243467,-0.0180667) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.887366,0.0093422) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0353289,-0.0260016) , 
0, 132.331, 1, 0, 0.753948,0.0780873) , 
0, 121.964, 1, 0, 0.592423,0.0476625) , 
1, -0.435336, 1, 0, 0.501765,0.0245735)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0232929,-0.0194008) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0861316,-0.0112513) , 
1, 0.0190564, 1, 0, 0.0455496,-0.0528805) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.188081,-0.0061802) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.597453,0.00186549) , 
1, -0.119834, 1, 0, 0.425646,-0.00245873) , 
0, 116.042, 1, 0, 0.180067,-0.0350361) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491647,-0.000818423) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.886889,0.00885892) , 
1, -0.427452, 1, 0, 0.838289,0.086537) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0366342,-0.0267579) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.0344503) , 
0, 144.907, 1, 0, 0.0208183,-0.068552) , 
0, 132.336, 1, 0, 0.671192,0.0548355) , 
0, 121.967, 1, 0, 0.500608,0.0236201)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0948133,-0.00332897) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.371983,0.00106303) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0108496,-0.00458654) , 
0, 129.231, 1, 0, 0.278144,-0.00988535) , 
1, -0.681164, 1, 0, 0.242383,-0.0277157) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0404361,-0.0240175) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.840609,0.00819409) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.13898,-0.00483327) , 
0, 129.752, 1, 0, 0.756924,0.0743946) , 
0, 112.486, 1, 0, 0.665794,0.057409) , 
1, -0.12425, 1, 0, 0.500571,0.0241917)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0962728,-0.0056124) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428046,0.00209544) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0612987,-0.00697971) , 
0, 128.235, 1, 0, 0.339449,0.000219454) , 
1, -0.644447, 1, 0, 0.295069,-0.014658) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.076942,-0.00908618) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.466653,0.00168754) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.846694,0.00903527) , 
0, 121.122, 1, 0, 0.788521,0.0780558) , 
0, 112.487, 1, 0, 0.703808,0.0657896) , 
1, 0.0261981, 1, 0, 0.499533,0.0255846)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0448869,-0.0164347) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.685694,0.00278056) , 
0, 119.642, 1, 0, 0.381972,-0.00232625) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0467343,-0.00513042) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.00392614) , 
0, 140.281, 1, 0, 0.0211906,-0.0643043) , 
0, 129.024, 1, 0, 0.289636,-0.0181885) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0701622,-0.0112917) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.729531,0.00519838) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.886336,0.0107826) , 
1, 0.445384, 1, 0, 0.789303,0.0743945) , 
0, 112.486, 1, 0, 0.702776,0.0617603) , 
1, 0.0261981, 1, 0, 0.496223,0.0217893)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0807177,-0.00792776) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.123039,-0.016354) , 
1, -0.718147, 1, 0, 0.101893,-0.0843242) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0221353,-0.0124589) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.339476,0.000271721) , 
0, 113.57, 1, 0, 0.25482,-0.00972627) , 
1, -0.616503, 1, 0, 0.201055,-0.0359532) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.205458,-0.00237352) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.894689,0.00874143) , 
0, 120.975, 1, 0, 0.691619,0.05988) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.025524,-0.0218678) , 
0, 132.831, 1, 0, 0.628681,0.0473513) , 
1, -0.28118, 1, 0, 0.504371,0.0231348)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.155244,-0.0064093) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.852458,0.00625166) , 
0, 122.461, 1, 0, 0.494375,0.0197983) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0557323,-0.0112674) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.238041,-0.00612318) , 
1, -0.22477, 1, 0, 0.136286,-0.0609268) , 
0, 127.4, 1, 0, 0.405478,-0.000241966) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587144,0.00474491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.888037,0.0103682) , 
0, 123.039, 1, 0, 0.79123,0.0818424) , 
1, 0.329742, 1, 0, 0.509732,0.0219422)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.267509,-0.0026976) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.12056,-0.00521078) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.287429,-0.00107226) , 
1, -0.616507, 1, 0, 0.232936,-0.0259956) , 
2, 12, 1, 0, 0.238571,-0.0170061) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.194723,-0.00711516) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.467774,0.00422493) , 
1, 0.364977, 1, 0, 0.286073,-0.0136633) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.936466,0.00920443) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166665,-0.00753233) , 
0, 128.847, 1, 0, 0.808908,0.0685741) , 
0, 121.943, 1, 0, 0.660681,0.0452593) , 
1, -0.127491, 1, 0, 0.494138,0.0132761)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0735444,-0.00365644) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.170773,-0.00685868) , 
1, -0.702938, 1, 0, 0.135491,-0.0582688) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529476,0.00218666) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0448083,-0.0107504) , 
0, 129.236, 1, 0, 0.437364,0.0108626) , 
1, -0.491933, 1, 0, 0.355359,-0.0079172) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.217263,-0.00238267) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.950081,0.0102413) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.602322,0.00453428) , 
0, 126.864, 1, 0, 0.874412,0.088987) , 
0, 119.503, 1, 0, 0.749566,0.0693234) , 
1, 0.185118, 1, 0, 0.508395,0.0220685)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.143191,-0.00277548) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.822004,0.00547484) , 
0, 122.461, 1, 0, 0.440861,0.0185908) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.270489,-0.0127197) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00260957,-0.0389466) , 
0, 133.339, 1, 0, 0.0909967,-0.0704331) , 
0, 127.4, 1, 0, 0.352747,-0.00382994) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429318,-0.000501907) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.545199,0.006205) , 
2, 12, 1, 0, 0.480041,0.000256634) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.973142,0.0115555) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.713092,0.00679504) , 
0, 126.139, 1, 0, 0.880481,0.0933522) , 
0, 122.76, 1, 0, 0.751992,0.0702463) , 
1, 0.181033, 1, 0, 0.506931,0.0247775)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0767337,-0.00331654) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.12848,-0.0129828) , 
1, -0.713059, 1, 0, 0.106146,-0.0735758) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.441269,0.00184365) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0915944,-0.0203979) , 
0, 127.384, 1, 0, 0.354045,-0.00463455) , 
1, -0.560616, 1, 0, 0.289963,-0.0224558) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.321262,-0.0045307) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.7842,0.00595462) , 
0, 122.777, 1, 0, 0.626019,0.0248556) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.813497,0.0101235) , 
1, 0.445366, 1, 0, 0.694907,0.0506336) , 
1, 0.0261981, 1, 0, 0.495702,0.0146785)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0512842,-0.0261498) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.229914,-0.00465255) , 
1, -0.454017, 1, 0, 0.174917,-0.0385028) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.548254,0.00371233) , 
1, 0.319536, 1, 0, 0.258044,-0.0230775) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.911184,0.0091818) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.782968,0.00445494) , 
0, 126.469, 1, 0, 0.881273,0.0850891) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.142565,-0.0034651) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.0408486) , 
0, 137.846, 1, 0, 0.0587852,-0.0515665) , 
0, 129.545, 1, 0, 0.657608,0.0479274) , 
0, 122.781, 1, 0, 0.503051,0.0204616)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.127485,-0.00617549) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.312181,-0.00159143) , 
1, -0.0119251, 1, 0, 0.168707,-0.0354075) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.847408,0.00717403) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.193309,-0.00739554) , 
0, 126.314, 1, 0, 0.489371,0.0156861) , 
0, 122.944, 1, 0, 0.349299,-0.00663249) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.388377,-0.0015549) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.559948,0.00432029) , 
1, 0.397919, 1, 0, 0.482617,0.0153563) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.970277,0.011115) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.67123,0.00512909) , 
0, 126.155, 1, 0, 0.858319,0.0795172) , 
0, 122.774, 1, 0, 0.740606,0.0594147) , 
1, 0.18214, 1, 0, 0.500663,0.0189157)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0706701,-0.00607319) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.362134,9.04592e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00895757,-0.0179491) , 
0, 129.989, 1, 0, 0.281461,-0.012051) , 
1, -0.681196, 1, 0, 0.242399,-0.0297153) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.142987,-0.00548182) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.893117,0.00787363) , 
0, 119.098, 1, 0, 0.717995,0.0521629) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0292413,-0.0206489) , 
0, 133.531, 1, 0, 0.661578,0.0426981) , 
1, -0.12425, 1, 0, 0.501472,0.0150396)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0649576,-0.0114257) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.602722,-0.00051997) , 
0, 119.098, 1, 0, 0.216217,-0.0330198) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.841485,0.00597765) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0310917,-0.0210268) , 
0, 129.681, 1, 0, 0.59446,0.0292381) , 
0, 122.947, 1, 0, 0.432511,0.00258157) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.833089,0.00999347) , 
1, 0.48596, 1, 0, 0.499636,0.016248)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0739261,-0.00626006) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.629539,0.00111244) , 
0, 119.1, 1, 0, 0.232568,-0.0209767) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.837541,0.00480163) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0398952,-0.00965626) , 
0, 129.684, 1, 0, 0.593353,0.031364) , 
0, 122.949, 1, 0, 0.445705,0.00994413) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.830834,0.0103795) , 
1, 0.482743, 1, 0, 0.507057,0.0230906)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.01884,-0.0353675) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.217803,-0.00365085) , 
0, 116.039, 1, 0, 0.0811751,-0.0406809) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.743933,0.00267233) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.026684,-0.0167111) , 
0, 128.88, 1, 0, 0.457624,0.00738591) , 
0, 121.964, 1, 0, 0.302835,-0.0123783) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.361928,-0.00240656) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.618451,0.00566409) , 
1, 0.367995, 1, 0, 0.477657,0.0142076) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.966476,0.0105916) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.589906,0.00382246) , 
0, 126.405, 1, 0, 0.833843,0.0711204) , 
0, 123.039, 1, 0, 0.705626,0.0506334) , 
1, 0.0252653, 1, 0, 0.508731,0.0198316)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0517326,-0.00456152) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.213305,-0.00506366) , 
1, -0.454074, 1, 0, 0.163387,-0.0400386) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526646,0.00340624) , 
1, 0.319304, 1, 0, 0.240977,-0.0256232) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.907422,0.008202) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.755898,0.00275364) , 
0, 126.471, 1, 0, 0.8732,0.0710466) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.131041,-0.00515363) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00190037,-0.0121812) , 
0, 137.851, 1, 0, 0.0514942,-0.0433867) , 
0, 129.548, 1, 0, 0.650008,0.0399642) , 
0, 122.783, 1, 0, 0.490052,0.0143155)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0647537,-0.00214864) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.109466,-0.00736466) , 
1, -0.695269, 1, 0, 0.0856619,-0.0768482) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0989798,-0.00613612) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.862298,0.00586717) , 
0, 118.72, 1, 0, 0.634021,0.0389633) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.36332,-0.000998948) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00963884,-0.0150568) , 
0, 134.076, 1, 0, 0.14319,-0.0383924) , 
0, 128.315, 1, 0, 0.553219,0.0262289) , 
1, -0.583986, 1, 0, 0.493566,0.0130778)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0281319,-0.00501916) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299736,-0.00224578) , 
0, 114.063, 1, 0, 0.145586,-0.0312073) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.849865,0.00481707) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0534107,-0.0103658) , 
0, 128.874, 1, 0, 0.613972,0.0275699) , 
0, 121.964, 1, 0, 0.443985,0.00623848) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.822257,0.0102365) , 
1, 0.48387, 1, 0, 0.505905,0.0190045)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0502957,-0.00270829) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.135681,-0.0113362) , 
1, -0.72157, 1, 0, 0.0983929,-0.0691715) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.23948,-0.00114692) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.856484,0.00679746) , 
0, 122.078, 1, 0, 0.620661,0.0382817) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0165786,-0.0194246) , 
0, 133.591, 1, 0, 0.554873,0.0291025) , 
1, -0.58246, 1, 0, 0.497564,0.0167646)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0640263,-0.00505938) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.147311,-0.00741473) , 
1, -0.72157, 1, 0, 0.111844,-0.0667685) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.130545,-0.00450638) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.89936,0.00808844) , 
0, 119.986, 1, 0, 0.644077,0.0470818) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.398482,-0.00125415) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00180398,-0.0192583) , 
0, 139.236, 1, 0, 0.240142,-0.0274392) , 
0, 127.39, 1, 0, 0.565536,0.0325919) , 
1, -0.58246, 1, 0, 0.511707,0.0208032)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0854442,-0.0212629) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.26507,-0.00306905) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.428601,0.00357345) , 
1, -0.211954, 1, 0, 0.298927,-0.0119465) , 
1, -0.610286, 1, 0, 0.243126,-0.027162) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.669432,0.00441017) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.152303,-0.00374391) , 
0, 128.09, 1, 0, 0.58658,0.0232199) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.817662,0.00968985) , 
1, 0.460861, 1, 0, 0.653404,0.0396288) , 
1, -0.123425, 1, 0, 0.4975,0.0142485)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0119549,-0.0290294) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0271547,-0.0137302) , 
1, -0.276715, 1, 0, 0.0208004,-0.0433486) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.153385,-0.00637501) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.588631,0.00130377) , 
0, 119.812, 1, 0, 0.267896,-0.0156738) , 
0, 110.118, 1, 0, 0.18018,-0.025498) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897409,0.00710147) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.635159,0.00190848) , 
0, 126.675, 1, 0, 0.837493,0.0582138) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.0416318) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0374591,-0.0095803) , 
1, -0.126625, 1, 0, 0.0153386,-0.0440964) , 
0, 132.335, 1, 0, 0.662947,0.036493) , 
0, 121.967, 1, 0, 0.494891,0.0149134)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.172158,-0.00408437) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.867436,0.00531447) , 
0, 122.462, 1, 0, 0.515759,0.0133459) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.328977,-0.00472073) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00330288,-0.0376602) , 
0, 136.289, 1, 0, 0.155491,-0.0416325) , 
0, 127.4, 1, 0, 0.432531,0.000644866) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.818961,0.00878644) , 
1, 0.47611, 1, 0, 0.499083,0.01245)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0704812,-0.00418904) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0274654,-0.00592057) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372541,0.000923) , 
0, 119.994, 1, 0, 0.240006,-0.00920201) , 
1, -0.721588, 1, 0, 0.209122,-0.0219199) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0447546,-0.0111698) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.780675,0.00541304) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0293637,-0.0162378) , 
0, 133.325, 1, 0, 0.703992,0.0438116) , 
0, 111.107, 1, 0, 0.626093,0.0347136) , 
1, -0.276437, 1, 0, 0.50407,0.0181404)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.013774,-0.00353389) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.027062,-0.0251118) , 
1, -0.126002, 1, 0, 0.0204989,-0.0403747) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0531796,-0.00242907) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.337091,4.13589e-05) , 
1, -0.424954, 1, 0, 0.260841,-0.0106696) , 
0, 110.12, 1, 0, 0.179289,-0.020749) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498771,-0.00138072) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.890613,0.00703429) , 
1, -0.427452, 1, 0, 0.845601,0.0556553) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0418287,-0.0140835) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00241392,-0.00881212) , 
0, 144.909, 1, 0, 0.0234546,-0.0316309) , 
0, 132.339, 1, 0, 0.678438,0.0379078) , 
0, 121.969, 1, 0, 0.509369,0.0180399)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0969435,-0.0032972) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266861,-0.00395781) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.272322,-0.00137044) , 
2, 12, 1, 0, 0.271323,-0.0106004) , 
1, -0.681381, 1, 0, 0.23847,-0.0282424) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0811108,-0.00593251) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.690838,0.00187987) , 
0, 115.251, 1, 0, 0.420888,0.00135486) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.916059,0.00817834) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0515903,-0.00979772) , 
0, 133.057, 1, 0, 0.805127,0.0582187) , 
0, 122.949, 1, 0, 0.668474,0.0379953) , 
1, -0.125027, 1, 0, 0.502943,0.0124969)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0604818,-0.0040837) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.161629,-0.00248312) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.183821,-0.00788394) , 
1, -0.537224, 1, 0, 0.169182,-0.0228206) , 
1, -0.723103, 1, 0, 0.141992,-0.0369103) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0207089,-0.00658773) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0674552,-0.00795568) , 
1, 0.00115989, 1, 0, 0.0450809,-0.0290497) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.784309,0.00558173) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0495879,-0.0146068) , 
0, 129.678, 1, 0, 0.672616,0.0352093) , 
0, 112.365, 1, 0, 0.579056,0.0256289) , 
1, -0.430983, 1, 0, 0.490085,0.0128981)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.163053,-0.00349783) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.852258,0.00496759) , 
0, 122.459, 1, 0, 0.488559,0.0149004) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.2704,-0.00779198) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00239091,-0.0110228) , 
0, 136.284, 1, 0, 0.115419,-0.0427262) , 
0, 127.398, 1, 0, 0.397995,0.000913979) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.70977,0.00453777) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.825815,0.00971918) , 
1, 0.459479, 1, 0, 0.787947,0.0618958) , 
1, 0.334106, 1, 0, 0.502484,0.0172543)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0852316,-0.00425722) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.030186,-0.0157205) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.428747,0.00131469) , 
0, 119.999, 1, 0, 0.276893,-0.00858358) , 
1, -0.686583, 1, 0, 0.24248,-0.0186614) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.234667,-0.000233736) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.933711,0.00729969) , 
0, 120.844, 1, 0, 0.731045,0.0430792) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231762,-0.00309771) , 
0, 128.09, 1, 0, 0.662496,0.0349483) , 
1, -0.128268, 1, 0, 0.501664,0.0144201)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0602123,-0.0220836) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.236328,-0.00222342) , 
1, -0.302035, 1, 0, 0.15213,-0.036961) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.829572,0.00271023) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.206211,-0.00538135) , 
0, 126.312, 1, 0, 0.492493,0.006509) , 
0, 122.944, 1, 0, 0.344622,-0.0123766) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.400582,-0.00120807) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.839344,0.00616548) , 
0, 122.73, 1, 0, 0.696545,0.029017) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.839333,0.00923586) , 
1, 0.517025, 1, 0, 0.747305,0.0435214) , 
1, 0.18385, 1, 0, 0.50117,0.00935444)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0495713,-0.00286494) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.257748,-0.00221953) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.592384,0.00451139) , 
1, 0.409497, 1, 0, 0.323424,-0.00354696) , 
1, -0.590418, 1, 0, 0.28348,-0.00942555) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.91425,0.00753649) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.731743,0.00236235) , 
0, 126.701, 1, 0, 0.875789,0.0590164) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00138371,-0.0417756) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.117135,-0.00448668) , 
1, -0.120885, 1, 0, 0.0488466,-0.0303326) , 
0, 129.754, 1, 0, 0.65836,0.0355238) , 
0, 123.039, 1, 0, 0.500804,0.0166323)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0769528,-0.0210425) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.176312,-0.00232378) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.646428,0.00259279) , 
0, 121.969, 1, 0, 0.477751,0.00905926) , 
1, -0.639418, 1, 0, 0.434392,0.00165949) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.825599,0.0090338) , 
1, 0.487087, 1, 0, 0.49848,0.012331)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0894868,-0.00482127) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.224657,-0.00252311) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.422686,0.00201355) , 
1, -0.224592, 1, 0, 0.263241,-0.0160804) , 
1, -0.679835, 1, 0, 0.229739,-0.0286331) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0424187,-0.0147996) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421273,0.00050626) , 
0, 110.116, 1, 0, 0.29543,-0.00588064) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.920157,0.00718694) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0626656,-0.00323685) , 
0, 132.33, 1, 0, 0.808886,0.0475483) , 
0, 121.964, 1, 0, 0.659332,0.0319861) , 
1, -0.123425, 1, 0, 0.492673,0.00846912)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.131134,-0.00736364) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30433,-0.00166949) , 
1, 0.0985323, 1, 0, 0.16785,-0.0260538) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.537713,0.000110867) , 
1, 0.318176, 1, 0, 0.254065,-0.0197861) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.899189,0.00600256) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.915356,0.00763893) , 
0, 124.626, 1, 0, 0.90689,0.0596279) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.130123,-0.00534375) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.551498,0.00233065) , 
1, -0.12425, 1, 0, 0.361823,-0.0115506) , 
0, 126.165, 1, 0, 0.645455,0.0254879) , 
0, 122.783, 1, 0, 0.493456,0.00790544)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0774038,-0.00401924) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0307052,-0.00995687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.40089,-0.000143729) , 
0, 118.735, 1, 0, 0.271932,-0.010719) , 
1, -0.686363, 1, 0, 0.239236,-0.0185551) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.215856,-0.00400469) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.476389,0.00279282) , 
1, 0.367056, 1, 0, 0.305413,-0.00723147) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.917557,0.00647785) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0550027,-0.0100022) , 
0, 132.342, 1, 0, 0.808175,0.041771) , 
0, 121.969, 1, 0, 0.660768,0.0274037) , 
1, -0.127491, 1, 0, 0.494567,0.00928321)    );
   return;
};
 
// Clean up
inline void ReadBDTG_UF_v1::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDTG_UF_v1::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
