
pwd_cmd="/bin/pwd"
run_dir=`${pwd_cmd}`
out_dir="/afs/cern.ch/work/x/xzuo/public/H2Mu/2018/Histograms/MC_data_comparison_2017_v4_v2"

bsub -q 1nh -o ${out_dir}/log/sub_0_H2Mu_gg.log -e ${out_dir}/err/sub_0_H2Mu_gg.err ${run_dir}/batch/launchers/sub_0_H2Mu_gg.sh
bsub -q 1nh -o ${out_dir}/log/sub_1_H2Mu_VBF.log -e ${out_dir}/err/sub_1_H2Mu_VBF.err ${run_dir}/batch/launchers/sub_1_H2Mu_VBF.sh
bsub -q 1nh -o ${out_dir}/log/sub_2_H2Mu_VBF.log -e ${out_dir}/err/sub_2_H2Mu_VBF.err ${run_dir}/batch/launchers/sub_2_H2Mu_VBF.sh
bsub -q 1nh -o ${out_dir}/log/sub_3_H2Mu_ZH.log -e ${out_dir}/err/sub_3_H2Mu_ZH.err ${run_dir}/batch/launchers/sub_3_H2Mu_ZH.sh
bsub -q 1nh -o ${out_dir}/log/sub_4_H2Mu_ZH.log -e ${out_dir}/err/sub_4_H2Mu_ZH.err ${run_dir}/batch/launchers/sub_4_H2Mu_ZH.sh
bsub -q 1nh -o ${out_dir}/log/sub_5_H2Mu_WH_pos.log -e ${out_dir}/err/sub_5_H2Mu_WH_pos.err ${run_dir}/batch/launchers/sub_5_H2Mu_WH_pos.sh
bsub -q 1nh -o ${out_dir}/log/sub_6_H2Mu_WH_pos.log -e ${out_dir}/err/sub_6_H2Mu_WH_pos.err ${run_dir}/batch/launchers/sub_6_H2Mu_WH_pos.sh
bsub -q 1nh -o ${out_dir}/log/sub_7_H2Mu_WH_neg.log -e ${out_dir}/err/sub_7_H2Mu_WH_neg.err ${run_dir}/batch/launchers/sub_7_H2Mu_WH_neg.sh
bsub -q 1nh -o ${out_dir}/log/sub_8_H2Mu_WH_neg.log -e ${out_dir}/err/sub_8_H2Mu_WH_neg.err ${run_dir}/batch/launchers/sub_8_H2Mu_WH_neg.sh
bsub -q 1nh -o ${out_dir}/log/sub_9_ZJets_AMC.log -e ${out_dir}/err/sub_9_ZJets_AMC.err ${run_dir}/batch/launchers/sub_9_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_10_ZJets_AMC.log -e ${out_dir}/err/sub_10_ZJets_AMC.err ${run_dir}/batch/launchers/sub_10_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_11_ZJets_AMC.log -e ${out_dir}/err/sub_11_ZJets_AMC.err ${run_dir}/batch/launchers/sub_11_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_12_ZJets_AMC.log -e ${out_dir}/err/sub_12_ZJets_AMC.err ${run_dir}/batch/launchers/sub_12_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_13_ZJets_AMC.log -e ${out_dir}/err/sub_13_ZJets_AMC.err ${run_dir}/batch/launchers/sub_13_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_14_ZJets_AMC.log -e ${out_dir}/err/sub_14_ZJets_AMC.err ${run_dir}/batch/launchers/sub_14_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_15_ZJets_AMC.log -e ${out_dir}/err/sub_15_ZJets_AMC.err ${run_dir}/batch/launchers/sub_15_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_16_ZJets_AMC.log -e ${out_dir}/err/sub_16_ZJets_AMC.err ${run_dir}/batch/launchers/sub_16_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_17_ZJets_AMC.log -e ${out_dir}/err/sub_17_ZJets_AMC.err ${run_dir}/batch/launchers/sub_17_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_18_ZJets_AMC.log -e ${out_dir}/err/sub_18_ZJets_AMC.err ${run_dir}/batch/launchers/sub_18_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_19_ZJets_AMC.log -e ${out_dir}/err/sub_19_ZJets_AMC.err ${run_dir}/batch/launchers/sub_19_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_20_ZJets_AMC.log -e ${out_dir}/err/sub_20_ZJets_AMC.err ${run_dir}/batch/launchers/sub_20_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_21_ZJets_AMC.log -e ${out_dir}/err/sub_21_ZJets_AMC.err ${run_dir}/batch/launchers/sub_21_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_22_ZJets_AMC.log -e ${out_dir}/err/sub_22_ZJets_AMC.err ${run_dir}/batch/launchers/sub_22_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_23_ZJets_AMC.log -e ${out_dir}/err/sub_23_ZJets_AMC.err ${run_dir}/batch/launchers/sub_23_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_24_ZJets_AMC.log -e ${out_dir}/err/sub_24_ZJets_AMC.err ${run_dir}/batch/launchers/sub_24_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_25_ZJets_AMC.log -e ${out_dir}/err/sub_25_ZJets_AMC.err ${run_dir}/batch/launchers/sub_25_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_26_ZJets_AMC.log -e ${out_dir}/err/sub_26_ZJets_AMC.err ${run_dir}/batch/launchers/sub_26_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_27_ZJets_AMC.log -e ${out_dir}/err/sub_27_ZJets_AMC.err ${run_dir}/batch/launchers/sub_27_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_28_ZJets_AMC.log -e ${out_dir}/err/sub_28_ZJets_AMC.err ${run_dir}/batch/launchers/sub_28_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_29_ZJets_AMC.log -e ${out_dir}/err/sub_29_ZJets_AMC.err ${run_dir}/batch/launchers/sub_29_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_30_ZJets_AMC.log -e ${out_dir}/err/sub_30_ZJets_AMC.err ${run_dir}/batch/launchers/sub_30_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_31_ZJets_AMC.log -e ${out_dir}/err/sub_31_ZJets_AMC.err ${run_dir}/batch/launchers/sub_31_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_32_ZJets_AMC.log -e ${out_dir}/err/sub_32_ZJets_AMC.err ${run_dir}/batch/launchers/sub_32_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_33_ZJets_AMC.log -e ${out_dir}/err/sub_33_ZJets_AMC.err ${run_dir}/batch/launchers/sub_33_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_34_ZJets_AMC.log -e ${out_dir}/err/sub_34_ZJets_AMC.err ${run_dir}/batch/launchers/sub_34_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_35_ZJets_AMC.log -e ${out_dir}/err/sub_35_ZJets_AMC.err ${run_dir}/batch/launchers/sub_35_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_36_ZJets_AMC.log -e ${out_dir}/err/sub_36_ZJets_AMC.err ${run_dir}/batch/launchers/sub_36_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_37_ZJets_AMC.log -e ${out_dir}/err/sub_37_ZJets_AMC.err ${run_dir}/batch/launchers/sub_37_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_38_ZJets_AMC.log -e ${out_dir}/err/sub_38_ZJets_AMC.err ${run_dir}/batch/launchers/sub_38_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_39_ZJets_AMC.log -e ${out_dir}/err/sub_39_ZJets_AMC.err ${run_dir}/batch/launchers/sub_39_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_40_ZJets_AMC.log -e ${out_dir}/err/sub_40_ZJets_AMC.err ${run_dir}/batch/launchers/sub_40_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_41_ZJets_AMC.log -e ${out_dir}/err/sub_41_ZJets_AMC.err ${run_dir}/batch/launchers/sub_41_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_42_ZJets_AMC.log -e ${out_dir}/err/sub_42_ZJets_AMC.err ${run_dir}/batch/launchers/sub_42_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_43_ZJets_AMC.log -e ${out_dir}/err/sub_43_ZJets_AMC.err ${run_dir}/batch/launchers/sub_43_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_44_ZJets_AMC.log -e ${out_dir}/err/sub_44_ZJets_AMC.err ${run_dir}/batch/launchers/sub_44_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_45_ZJets_AMC.log -e ${out_dir}/err/sub_45_ZJets_AMC.err ${run_dir}/batch/launchers/sub_45_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_46_ZJets_AMC.log -e ${out_dir}/err/sub_46_ZJets_AMC.err ${run_dir}/batch/launchers/sub_46_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_47_ZJets_AMC.log -e ${out_dir}/err/sub_47_ZJets_AMC.err ${run_dir}/batch/launchers/sub_47_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_48_ZJets_AMC.log -e ${out_dir}/err/sub_48_ZJets_AMC.err ${run_dir}/batch/launchers/sub_48_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_49_ZJets_AMC.log -e ${out_dir}/err/sub_49_ZJets_AMC.err ${run_dir}/batch/launchers/sub_49_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_50_ZJets_AMC.log -e ${out_dir}/err/sub_50_ZJets_AMC.err ${run_dir}/batch/launchers/sub_50_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_51_ZJets_AMC.log -e ${out_dir}/err/sub_51_ZJets_AMC.err ${run_dir}/batch/launchers/sub_51_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_52_ZJets_AMC.log -e ${out_dir}/err/sub_52_ZJets_AMC.err ${run_dir}/batch/launchers/sub_52_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_53_ZJets_AMC.log -e ${out_dir}/err/sub_53_ZJets_AMC.err ${run_dir}/batch/launchers/sub_53_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_54_ZJets_AMC.log -e ${out_dir}/err/sub_54_ZJets_AMC.err ${run_dir}/batch/launchers/sub_54_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_55_ZJets_AMC.log -e ${out_dir}/err/sub_55_ZJets_AMC.err ${run_dir}/batch/launchers/sub_55_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_56_ZJets_AMC.log -e ${out_dir}/err/sub_56_ZJets_AMC.err ${run_dir}/batch/launchers/sub_56_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_57_ZJets_AMC.log -e ${out_dir}/err/sub_57_ZJets_AMC.err ${run_dir}/batch/launchers/sub_57_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_58_ZJets_AMC.log -e ${out_dir}/err/sub_58_ZJets_AMC.err ${run_dir}/batch/launchers/sub_58_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_59_ZJets_AMC.log -e ${out_dir}/err/sub_59_ZJets_AMC.err ${run_dir}/batch/launchers/sub_59_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_60_ZJets_AMC.log -e ${out_dir}/err/sub_60_ZJets_AMC.err ${run_dir}/batch/launchers/sub_60_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_61_ZJets_AMC.log -e ${out_dir}/err/sub_61_ZJets_AMC.err ${run_dir}/batch/launchers/sub_61_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_62_ZJets_AMC.log -e ${out_dir}/err/sub_62_ZJets_AMC.err ${run_dir}/batch/launchers/sub_62_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_63_ZJets_AMC.log -e ${out_dir}/err/sub_63_ZJets_AMC.err ${run_dir}/batch/launchers/sub_63_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_64_ZJets_AMC.log -e ${out_dir}/err/sub_64_ZJets_AMC.err ${run_dir}/batch/launchers/sub_64_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_65_ZJets_AMC.log -e ${out_dir}/err/sub_65_ZJets_AMC.err ${run_dir}/batch/launchers/sub_65_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_66_ZJets_AMC.log -e ${out_dir}/err/sub_66_ZJets_AMC.err ${run_dir}/batch/launchers/sub_66_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_67_ZJets_AMC.log -e ${out_dir}/err/sub_67_ZJets_AMC.err ${run_dir}/batch/launchers/sub_67_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_68_ZJets_AMC.log -e ${out_dir}/err/sub_68_ZJets_AMC.err ${run_dir}/batch/launchers/sub_68_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_69_ZJets_AMC.log -e ${out_dir}/err/sub_69_ZJets_AMC.err ${run_dir}/batch/launchers/sub_69_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_70_ZJets_AMC.log -e ${out_dir}/err/sub_70_ZJets_AMC.err ${run_dir}/batch/launchers/sub_70_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_71_ZJets_AMC.log -e ${out_dir}/err/sub_71_ZJets_AMC.err ${run_dir}/batch/launchers/sub_71_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_72_ZJets_AMC.log -e ${out_dir}/err/sub_72_ZJets_AMC.err ${run_dir}/batch/launchers/sub_72_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_73_ZJets_AMC.log -e ${out_dir}/err/sub_73_ZJets_AMC.err ${run_dir}/batch/launchers/sub_73_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_74_ZJets_AMC.log -e ${out_dir}/err/sub_74_ZJets_AMC.err ${run_dir}/batch/launchers/sub_74_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_75_ZJets_AMC.log -e ${out_dir}/err/sub_75_ZJets_AMC.err ${run_dir}/batch/launchers/sub_75_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_76_ZJets_AMC.log -e ${out_dir}/err/sub_76_ZJets_AMC.err ${run_dir}/batch/launchers/sub_76_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_77_ZJets_AMC.log -e ${out_dir}/err/sub_77_ZJets_AMC.err ${run_dir}/batch/launchers/sub_77_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_78_ZJets_AMC.log -e ${out_dir}/err/sub_78_ZJets_AMC.err ${run_dir}/batch/launchers/sub_78_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_79_ZJets_AMC.log -e ${out_dir}/err/sub_79_ZJets_AMC.err ${run_dir}/batch/launchers/sub_79_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_80_ZJets_AMC.log -e ${out_dir}/err/sub_80_ZJets_AMC.err ${run_dir}/batch/launchers/sub_80_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_81_ZJets_AMC.log -e ${out_dir}/err/sub_81_ZJets_AMC.err ${run_dir}/batch/launchers/sub_81_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_82_ZJets_AMC.log -e ${out_dir}/err/sub_82_ZJets_AMC.err ${run_dir}/batch/launchers/sub_82_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_83_ZJets_AMC.log -e ${out_dir}/err/sub_83_ZJets_AMC.err ${run_dir}/batch/launchers/sub_83_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_84_ZJets_AMC.log -e ${out_dir}/err/sub_84_ZJets_AMC.err ${run_dir}/batch/launchers/sub_84_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_85_ZJets_AMC.log -e ${out_dir}/err/sub_85_ZJets_AMC.err ${run_dir}/batch/launchers/sub_85_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_86_ZJets_AMC.log -e ${out_dir}/err/sub_86_ZJets_AMC.err ${run_dir}/batch/launchers/sub_86_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_87_ZJets_AMC.log -e ${out_dir}/err/sub_87_ZJets_AMC.err ${run_dir}/batch/launchers/sub_87_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_88_ZJets_AMC.log -e ${out_dir}/err/sub_88_ZJets_AMC.err ${run_dir}/batch/launchers/sub_88_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_89_ZJets_AMC.log -e ${out_dir}/err/sub_89_ZJets_AMC.err ${run_dir}/batch/launchers/sub_89_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_90_ZJets_AMC.log -e ${out_dir}/err/sub_90_ZJets_AMC.err ${run_dir}/batch/launchers/sub_90_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_91_ZJets_AMC.log -e ${out_dir}/err/sub_91_ZJets_AMC.err ${run_dir}/batch/launchers/sub_91_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_92_ZJets_AMC.log -e ${out_dir}/err/sub_92_ZJets_AMC.err ${run_dir}/batch/launchers/sub_92_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_93_ZJets_AMC.log -e ${out_dir}/err/sub_93_ZJets_AMC.err ${run_dir}/batch/launchers/sub_93_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_94_ZJets_AMC.log -e ${out_dir}/err/sub_94_ZJets_AMC.err ${run_dir}/batch/launchers/sub_94_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_95_ZJets_AMC.log -e ${out_dir}/err/sub_95_ZJets_AMC.err ${run_dir}/batch/launchers/sub_95_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_96_ZJets_AMC.log -e ${out_dir}/err/sub_96_ZJets_AMC.err ${run_dir}/batch/launchers/sub_96_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_97_ZJets_AMC.log -e ${out_dir}/err/sub_97_ZJets_AMC.err ${run_dir}/batch/launchers/sub_97_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_98_ZJets_AMC.log -e ${out_dir}/err/sub_98_ZJets_AMC.err ${run_dir}/batch/launchers/sub_98_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_99_ZJets_AMC.log -e ${out_dir}/err/sub_99_ZJets_AMC.err ${run_dir}/batch/launchers/sub_99_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_100_ZJets_AMC.log -e ${out_dir}/err/sub_100_ZJets_AMC.err ${run_dir}/batch/launchers/sub_100_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_101_ZJets_AMC.log -e ${out_dir}/err/sub_101_ZJets_AMC.err ${run_dir}/batch/launchers/sub_101_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_102_ZJets_AMC.log -e ${out_dir}/err/sub_102_ZJets_AMC.err ${run_dir}/batch/launchers/sub_102_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_103_ZJets_AMC.log -e ${out_dir}/err/sub_103_ZJets_AMC.err ${run_dir}/batch/launchers/sub_103_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_104_ZJets_AMC.log -e ${out_dir}/err/sub_104_ZJets_AMC.err ${run_dir}/batch/launchers/sub_104_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_105_ZJets_AMC.log -e ${out_dir}/err/sub_105_ZJets_AMC.err ${run_dir}/batch/launchers/sub_105_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_106_ZJets_AMC.log -e ${out_dir}/err/sub_106_ZJets_AMC.err ${run_dir}/batch/launchers/sub_106_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_107_ZJets_AMC.log -e ${out_dir}/err/sub_107_ZJets_AMC.err ${run_dir}/batch/launchers/sub_107_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_108_ZJets_AMC.log -e ${out_dir}/err/sub_108_ZJets_AMC.err ${run_dir}/batch/launchers/sub_108_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_109_ZJets_AMC.log -e ${out_dir}/err/sub_109_ZJets_AMC.err ${run_dir}/batch/launchers/sub_109_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_110_ZJets_AMC.log -e ${out_dir}/err/sub_110_ZJets_AMC.err ${run_dir}/batch/launchers/sub_110_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_111_ZJets_AMC.log -e ${out_dir}/err/sub_111_ZJets_AMC.err ${run_dir}/batch/launchers/sub_111_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_112_ZJets_AMC.log -e ${out_dir}/err/sub_112_ZJets_AMC.err ${run_dir}/batch/launchers/sub_112_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_113_ZJets_AMC.log -e ${out_dir}/err/sub_113_ZJets_AMC.err ${run_dir}/batch/launchers/sub_113_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_114_ZJets_AMC.log -e ${out_dir}/err/sub_114_ZJets_AMC.err ${run_dir}/batch/launchers/sub_114_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_115_ZJets_AMC.log -e ${out_dir}/err/sub_115_ZJets_AMC.err ${run_dir}/batch/launchers/sub_115_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_116_ZJets_AMC.log -e ${out_dir}/err/sub_116_ZJets_AMC.err ${run_dir}/batch/launchers/sub_116_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_117_ZJets_AMC.log -e ${out_dir}/err/sub_117_ZJets_AMC.err ${run_dir}/batch/launchers/sub_117_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_118_ZJets_AMC.log -e ${out_dir}/err/sub_118_ZJets_AMC.err ${run_dir}/batch/launchers/sub_118_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_119_ZJets_AMC.log -e ${out_dir}/err/sub_119_ZJets_AMC.err ${run_dir}/batch/launchers/sub_119_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_120_ZJets_AMC.log -e ${out_dir}/err/sub_120_ZJets_AMC.err ${run_dir}/batch/launchers/sub_120_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_121_ZJets_AMC.log -e ${out_dir}/err/sub_121_ZJets_AMC.err ${run_dir}/batch/launchers/sub_121_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_122_ZJets_AMC.log -e ${out_dir}/err/sub_122_ZJets_AMC.err ${run_dir}/batch/launchers/sub_122_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_123_ZJets_AMC.log -e ${out_dir}/err/sub_123_ZJets_AMC.err ${run_dir}/batch/launchers/sub_123_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_124_ZJets_AMC.log -e ${out_dir}/err/sub_124_ZJets_AMC.err ${run_dir}/batch/launchers/sub_124_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_125_ZJets_AMC.log -e ${out_dir}/err/sub_125_ZJets_AMC.err ${run_dir}/batch/launchers/sub_125_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_126_ZJets_AMC.log -e ${out_dir}/err/sub_126_ZJets_AMC.err ${run_dir}/batch/launchers/sub_126_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_127_ZJets_AMC.log -e ${out_dir}/err/sub_127_ZJets_AMC.err ${run_dir}/batch/launchers/sub_127_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_128_ZJets_AMC.log -e ${out_dir}/err/sub_128_ZJets_AMC.err ${run_dir}/batch/launchers/sub_128_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_129_ZJets_AMC.log -e ${out_dir}/err/sub_129_ZJets_AMC.err ${run_dir}/batch/launchers/sub_129_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_130_ZJets_AMC.log -e ${out_dir}/err/sub_130_ZJets_AMC.err ${run_dir}/batch/launchers/sub_130_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_131_ZJets_AMC.log -e ${out_dir}/err/sub_131_ZJets_AMC.err ${run_dir}/batch/launchers/sub_131_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_132_ZJets_AMC.log -e ${out_dir}/err/sub_132_ZJets_AMC.err ${run_dir}/batch/launchers/sub_132_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_133_ZJets_AMC.log -e ${out_dir}/err/sub_133_ZJets_AMC.err ${run_dir}/batch/launchers/sub_133_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_134_ZJets_AMC.log -e ${out_dir}/err/sub_134_ZJets_AMC.err ${run_dir}/batch/launchers/sub_134_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_135_ZJets_AMC.log -e ${out_dir}/err/sub_135_ZJets_AMC.err ${run_dir}/batch/launchers/sub_135_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_136_ZJets_AMC.log -e ${out_dir}/err/sub_136_ZJets_AMC.err ${run_dir}/batch/launchers/sub_136_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_137_ZJets_AMC.log -e ${out_dir}/err/sub_137_ZJets_AMC.err ${run_dir}/batch/launchers/sub_137_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_138_ZJets_AMC.log -e ${out_dir}/err/sub_138_ZJets_AMC.err ${run_dir}/batch/launchers/sub_138_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_139_ZJets_AMC.log -e ${out_dir}/err/sub_139_ZJets_AMC.err ${run_dir}/batch/launchers/sub_139_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_140_ZJets_AMC.log -e ${out_dir}/err/sub_140_ZJets_AMC.err ${run_dir}/batch/launchers/sub_140_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_141_ZJets_AMC.log -e ${out_dir}/err/sub_141_ZJets_AMC.err ${run_dir}/batch/launchers/sub_141_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_142_ZJets_AMC.log -e ${out_dir}/err/sub_142_ZJets_AMC.err ${run_dir}/batch/launchers/sub_142_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_143_ZJets_AMC.log -e ${out_dir}/err/sub_143_ZJets_AMC.err ${run_dir}/batch/launchers/sub_143_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_144_ZJets_AMC.log -e ${out_dir}/err/sub_144_ZJets_AMC.err ${run_dir}/batch/launchers/sub_144_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_145_ZJets_AMC.log -e ${out_dir}/err/sub_145_ZJets_AMC.err ${run_dir}/batch/launchers/sub_145_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_146_ZJets_AMC.log -e ${out_dir}/err/sub_146_ZJets_AMC.err ${run_dir}/batch/launchers/sub_146_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_147_ZJets_AMC.log -e ${out_dir}/err/sub_147_ZJets_AMC.err ${run_dir}/batch/launchers/sub_147_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_148_ZJets_AMC.log -e ${out_dir}/err/sub_148_ZJets_AMC.err ${run_dir}/batch/launchers/sub_148_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_149_ZJets_AMC.log -e ${out_dir}/err/sub_149_ZJets_AMC.err ${run_dir}/batch/launchers/sub_149_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_150_ZJets_AMC.log -e ${out_dir}/err/sub_150_ZJets_AMC.err ${run_dir}/batch/launchers/sub_150_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_151_ZJets_AMC.log -e ${out_dir}/err/sub_151_ZJets_AMC.err ${run_dir}/batch/launchers/sub_151_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_152_ZJets_AMC.log -e ${out_dir}/err/sub_152_ZJets_AMC.err ${run_dir}/batch/launchers/sub_152_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_153_ZJets_AMC.log -e ${out_dir}/err/sub_153_ZJets_AMC.err ${run_dir}/batch/launchers/sub_153_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_154_ZJets_AMC.log -e ${out_dir}/err/sub_154_ZJets_AMC.err ${run_dir}/batch/launchers/sub_154_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_155_ZJets_AMC.log -e ${out_dir}/err/sub_155_ZJets_AMC.err ${run_dir}/batch/launchers/sub_155_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_156_ZJets_AMC.log -e ${out_dir}/err/sub_156_ZJets_AMC.err ${run_dir}/batch/launchers/sub_156_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_157_ZJets_AMC.log -e ${out_dir}/err/sub_157_ZJets_AMC.err ${run_dir}/batch/launchers/sub_157_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_158_ZJets_AMC.log -e ${out_dir}/err/sub_158_ZJets_AMC.err ${run_dir}/batch/launchers/sub_158_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_159_ZJets_AMC.log -e ${out_dir}/err/sub_159_ZJets_AMC.err ${run_dir}/batch/launchers/sub_159_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_160_ZJets_AMC.log -e ${out_dir}/err/sub_160_ZJets_AMC.err ${run_dir}/batch/launchers/sub_160_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_161_ZJets_AMC.log -e ${out_dir}/err/sub_161_ZJets_AMC.err ${run_dir}/batch/launchers/sub_161_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_162_ZJets_AMC.log -e ${out_dir}/err/sub_162_ZJets_AMC.err ${run_dir}/batch/launchers/sub_162_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_163_ZJets_AMC.log -e ${out_dir}/err/sub_163_ZJets_AMC.err ${run_dir}/batch/launchers/sub_163_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_164_ZJets_AMC.log -e ${out_dir}/err/sub_164_ZJets_AMC.err ${run_dir}/batch/launchers/sub_164_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_165_ZJets_AMC.log -e ${out_dir}/err/sub_165_ZJets_AMC.err ${run_dir}/batch/launchers/sub_165_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_166_ZJets_AMC.log -e ${out_dir}/err/sub_166_ZJets_AMC.err ${run_dir}/batch/launchers/sub_166_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_167_ZJets_AMC.log -e ${out_dir}/err/sub_167_ZJets_AMC.err ${run_dir}/batch/launchers/sub_167_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_168_ZJets_AMC.log -e ${out_dir}/err/sub_168_ZJets_AMC.err ${run_dir}/batch/launchers/sub_168_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_169_ZJets_AMC.log -e ${out_dir}/err/sub_169_ZJets_AMC.err ${run_dir}/batch/launchers/sub_169_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_170_ZJets_AMC.log -e ${out_dir}/err/sub_170_ZJets_AMC.err ${run_dir}/batch/launchers/sub_170_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_171_ZJets_AMC.log -e ${out_dir}/err/sub_171_ZJets_AMC.err ${run_dir}/batch/launchers/sub_171_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_172_ZJets_AMC.log -e ${out_dir}/err/sub_172_ZJets_AMC.err ${run_dir}/batch/launchers/sub_172_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_173_ZJets_AMC.log -e ${out_dir}/err/sub_173_ZJets_AMC.err ${run_dir}/batch/launchers/sub_173_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_174_ZJets_AMC.log -e ${out_dir}/err/sub_174_ZJets_AMC.err ${run_dir}/batch/launchers/sub_174_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_175_ZJets_AMC.log -e ${out_dir}/err/sub_175_ZJets_AMC.err ${run_dir}/batch/launchers/sub_175_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_176_ZJets_AMC.log -e ${out_dir}/err/sub_176_ZJets_AMC.err ${run_dir}/batch/launchers/sub_176_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_177_ZJets_AMC.log -e ${out_dir}/err/sub_177_ZJets_AMC.err ${run_dir}/batch/launchers/sub_177_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_178_ZJets_AMC.log -e ${out_dir}/err/sub_178_ZJets_AMC.err ${run_dir}/batch/launchers/sub_178_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_179_ZJets_AMC.log -e ${out_dir}/err/sub_179_ZJets_AMC.err ${run_dir}/batch/launchers/sub_179_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_180_ZJets_AMC.log -e ${out_dir}/err/sub_180_ZJets_AMC.err ${run_dir}/batch/launchers/sub_180_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_181_ZJets_AMC.log -e ${out_dir}/err/sub_181_ZJets_AMC.err ${run_dir}/batch/launchers/sub_181_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_182_ZJets_AMC.log -e ${out_dir}/err/sub_182_ZJets_AMC.err ${run_dir}/batch/launchers/sub_182_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_183_ZJets_AMC.log -e ${out_dir}/err/sub_183_ZJets_AMC.err ${run_dir}/batch/launchers/sub_183_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_184_ZJets_AMC.log -e ${out_dir}/err/sub_184_ZJets_AMC.err ${run_dir}/batch/launchers/sub_184_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_185_ZJets_AMC.log -e ${out_dir}/err/sub_185_ZJets_AMC.err ${run_dir}/batch/launchers/sub_185_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_186_ZJets_AMC.log -e ${out_dir}/err/sub_186_ZJets_AMC.err ${run_dir}/batch/launchers/sub_186_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_187_ZJets_AMC.log -e ${out_dir}/err/sub_187_ZJets_AMC.err ${run_dir}/batch/launchers/sub_187_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_188_ZJets_AMC.log -e ${out_dir}/err/sub_188_ZJets_AMC.err ${run_dir}/batch/launchers/sub_188_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_189_ZJets_AMC.log -e ${out_dir}/err/sub_189_ZJets_AMC.err ${run_dir}/batch/launchers/sub_189_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_190_ZJets_AMC.log -e ${out_dir}/err/sub_190_ZJets_AMC.err ${run_dir}/batch/launchers/sub_190_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_191_ZJets_AMC.log -e ${out_dir}/err/sub_191_ZJets_AMC.err ${run_dir}/batch/launchers/sub_191_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_192_ZJets_AMC.log -e ${out_dir}/err/sub_192_ZJets_AMC.err ${run_dir}/batch/launchers/sub_192_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_193_ZJets_AMC.log -e ${out_dir}/err/sub_193_ZJets_AMC.err ${run_dir}/batch/launchers/sub_193_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_194_ZJets_AMC.log -e ${out_dir}/err/sub_194_ZJets_AMC.err ${run_dir}/batch/launchers/sub_194_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_195_ZJets_AMC.log -e ${out_dir}/err/sub_195_ZJets_AMC.err ${run_dir}/batch/launchers/sub_195_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_196_ZJets_AMC.log -e ${out_dir}/err/sub_196_ZJets_AMC.err ${run_dir}/batch/launchers/sub_196_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_197_ZJets_AMC.log -e ${out_dir}/err/sub_197_ZJets_AMC.err ${run_dir}/batch/launchers/sub_197_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_198_ZJets_AMC.log -e ${out_dir}/err/sub_198_ZJets_AMC.err ${run_dir}/batch/launchers/sub_198_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_199_ZJets_AMC.log -e ${out_dir}/err/sub_199_ZJets_AMC.err ${run_dir}/batch/launchers/sub_199_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_200_ZJets_AMC.log -e ${out_dir}/err/sub_200_ZJets_AMC.err ${run_dir}/batch/launchers/sub_200_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_201_ZJets_AMC.log -e ${out_dir}/err/sub_201_ZJets_AMC.err ${run_dir}/batch/launchers/sub_201_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_202_ZJets_AMC.log -e ${out_dir}/err/sub_202_ZJets_AMC.err ${run_dir}/batch/launchers/sub_202_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_203_ZJets_AMC.log -e ${out_dir}/err/sub_203_ZJets_AMC.err ${run_dir}/batch/launchers/sub_203_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_204_ZJets_AMC.log -e ${out_dir}/err/sub_204_ZJets_AMC.err ${run_dir}/batch/launchers/sub_204_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_205_ZJets_AMC.log -e ${out_dir}/err/sub_205_ZJets_AMC.err ${run_dir}/batch/launchers/sub_205_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_206_ZJets_AMC.log -e ${out_dir}/err/sub_206_ZJets_AMC.err ${run_dir}/batch/launchers/sub_206_ZJets_AMC.sh
bsub -q 1nh -o ${out_dir}/log/sub_207_tt.log -e ${out_dir}/err/sub_207_tt.err ${run_dir}/batch/launchers/sub_207_tt.sh
bsub -q 1nh -o ${out_dir}/log/sub_208_tt.log -e ${out_dir}/err/sub_208_tt.err ${run_dir}/batch/launchers/sub_208_tt.sh
bsub -q 1nh -o ${out_dir}/log/sub_209_tt.log -e ${out_dir}/err/sub_209_tt.err ${run_dir}/batch/launchers/sub_209_tt.sh
bsub -q 1nh -o ${out_dir}/log/sub_210_tt.log -e ${out_dir}/err/sub_210_tt.err ${run_dir}/batch/launchers/sub_210_tt.sh
bsub -q 1nh -o ${out_dir}/log/sub_211_tt.log -e ${out_dir}/err/sub_211_tt.err ${run_dir}/batch/launchers/sub_211_tt.sh
bsub -q 1nh -o ${out_dir}/log/sub_212_tt.log -e ${out_dir}/err/sub_212_tt.err ${run_dir}/batch/launchers/sub_212_tt.sh
bsub -q 1nh -o ${out_dir}/log/sub_213_tt.log -e ${out_dir}/err/sub_213_tt.err ${run_dir}/batch/launchers/sub_213_tt.sh
bsub -q 1nh -o ${out_dir}/log/sub_214_tt.log -e ${out_dir}/err/sub_214_tt.err ${run_dir}/batch/launchers/sub_214_tt.sh
bsub -q 1nh -o ${out_dir}/log/sub_215_tt.log -e ${out_dir}/err/sub_215_tt.err ${run_dir}/batch/launchers/sub_215_tt.sh
bsub -q 1nh -o ${out_dir}/log/sub_216_tt.log -e ${out_dir}/err/sub_216_tt.err ${run_dir}/batch/launchers/sub_216_tt.sh
bsub -q 1nh -o ${out_dir}/log/sub_217_tt.log -e ${out_dir}/err/sub_217_tt.err ${run_dir}/batch/launchers/sub_217_tt.sh
bsub -q 1nh -o ${out_dir}/log/sub_218_tt.log -e ${out_dir}/err/sub_218_tt.err ${run_dir}/batch/launchers/sub_218_tt.sh
bsub -q 1nh -o ${out_dir}/log/sub_219_tt.log -e ${out_dir}/err/sub_219_tt.err ${run_dir}/batch/launchers/sub_219_tt.sh
bsub -q 1nh -o ${out_dir}/log/sub_220_tt.log -e ${out_dir}/err/sub_220_tt.err ${run_dir}/batch/launchers/sub_220_tt.sh
bsub -q 1nh -o ${out_dir}/log/sub_221_tt.log -e ${out_dir}/err/sub_221_tt.err ${run_dir}/batch/launchers/sub_221_tt.sh
bsub -q 1nh -o ${out_dir}/log/sub_222_tt.log -e ${out_dir}/err/sub_222_tt.err ${run_dir}/batch/launchers/sub_222_tt.sh
bsub -q 1nh -o ${out_dir}/log/sub_223_tt.log -e ${out_dir}/err/sub_223_tt.err ${run_dir}/batch/launchers/sub_223_tt.sh
bsub -q 1nh -o ${out_dir}/log/sub_224_tt.log -e ${out_dir}/err/sub_224_tt.err ${run_dir}/batch/launchers/sub_224_tt.sh
bsub -q 1nh -o ${out_dir}/log/sub_225_tt.log -e ${out_dir}/err/sub_225_tt.err ${run_dir}/batch/launchers/sub_225_tt.sh
bsub -q 1nh -o ${out_dir}/log/sub_226_tt.log -e ${out_dir}/err/sub_226_tt.err ${run_dir}/batch/launchers/sub_226_tt.sh
bsub -q 1nh -o ${out_dir}/log/sub_227_tt.log -e ${out_dir}/err/sub_227_tt.err ${run_dir}/batch/launchers/sub_227_tt.sh
bsub -q 1nh -o ${out_dir}/log/sub_228_tt.log -e ${out_dir}/err/sub_228_tt.err ${run_dir}/batch/launchers/sub_228_tt.sh
bsub -q 1nh -o ${out_dir}/log/sub_229_tt.log -e ${out_dir}/err/sub_229_tt.err ${run_dir}/batch/launchers/sub_229_tt.sh
bsub -q 1nh -o ${out_dir}/log/sub_230_tt.log -e ${out_dir}/err/sub_230_tt.err ${run_dir}/batch/launchers/sub_230_tt.sh
echo "Jobs will be output to ${out_dir}"
