// Class: ReadBDTG_AWB_lite
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTG_AWB_lite
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.12/07       [396295]
Creator        : abrinke1
Date           : Thu Jul  4 07:32:31 2019
Host           : Linux cmsbuild92.cern.ch 2.6.32-696.30.1.el6.x86_64 #1 SMP Tue May 22 06:09:36 CEST 2018 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/user/a/abrinke1/HiggsToMuMu/2018/CMSSW_10_2_11_patch1/src/H2MuAnalyzer/TrainMVA
Training events: 154963
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "50" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for GradBoost algorithm]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
H_pair_pt                     H_pair_pt                     H_pair_pt                     H_pair_pt                                                       'F'    [0.174321591854,1592.23571777]
OS_pair_mass                  OS_pair_mass                  OS_pair_mass                  OS_pair_mass                                                    'F'    [12.0022649765,1810.3840332]
nEles                         nEles                         nEles                         Number of electrons                                             'I'    [0,1]
muH1_eta_abs                  muH1_eta_abs                  muH1_eta_abs                  |#eta| #mu1 from Higgs                                          'F'    [4.18702620664e-06,2.39995646477]
muH2_eta_abs                  muH2_eta_abs                  muH2_eta_abs                  |#eta| #mu2 from Higgs                                          'F'    [2.60819365394e-06,2.39999866486]
muSS_muOS_dR                  muSS_muOS_dR                  muSS_muOS_dR                  muSS_muOS_dR                                                    'F'    [0.171248823404,5.13359117508]
muSS_OS_pair_dR               muSS_OS_pair_dR               muSS_OS_pair_dR               muSS_OS_pair_dR                                                 'F'    [0.0193049702793,7.22482681274]
lep_pt                        lep_pt                        lep_pt                        lep_pt                                                          'F'    [10.00050354,1104.6217041]
nJetsCent                     nJetsCent                     nJetsCent                     nJetsCent                                                       'I'    [1,15]
nJetsCent40                   nJetsCent40                   nJetsCent40                   nJetsCent40                                                     'I'    [0,11]
nBJetsLoose                   nBJetsLoose                   nBJetsLoose                   nBJetsLoose                                                     'I'    [1,7]
NSpec 9
samp_ID                       samp_ID                       samp_ID                       Sample ID                                                       'F'    [-26,38]
event                         event                         event                         Event number                                                    'F'    [3,170579920]
event_wgt                     event_wgt                     event_wgt                     Per-event scale factors                                         'F'    [-6.37165927887,18.4841747284]
samp_wgt                      samp_wgt                      samp_wgt                      Xsec x lumi for sample                                          'F'    [2.80000003841e-05,3.92017388344]
lepMVA_wgt                    lepMVA_wgt                    lepMVA_wgt                    lepMVA efficiency SF                                            'F'    [0.416317880154,1.15934419632]
total_wgt                     total_wgt                     total_wgt                     Overall weight                                                  'F'    [-0.412183314562,1.73373699188]
res_wgt                       res_wgt                       res_wgt                       Mass resolution weight                                          'F'    [0.020715624094,1.94245529175]
dimu_mass                     dimu_mass                     dimu_mass                     mass(#mu#mu)                  GeV                               'F'    [105.025375366,159.997497559]
nEles                         nEles                         nEles                         Number of electrons                                             'F'    [0,1]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTG_AWB_liteNode
   
#ifndef BDTG_AWB_liteNode__def
#define BDTG_AWB_liteNode__def
   
class BDTG_AWB_liteNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTG_AWB_liteNode ( BDTG_AWB_liteNode* left,BDTG_AWB_liteNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTG_AWB_liteNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTG_AWB_liteNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTG_AWB_liteNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTG_AWB_liteNode*   fLeft;     // pointer to the left daughter node
   BDTG_AWB_liteNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTG_AWB_liteNode::~BDTG_AWB_liteNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTG_AWB_liteNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTG_AWB_liteNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTG_AWB_lite : public IClassifierReader {

 public:

   // constructor
   ReadBDTG_AWB_lite( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDTG_AWB_lite" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "H_pair_pt", "OS_pair_mass", "nEles", "muH1_eta_abs", "muH2_eta_abs", "muSS_muOS_dR", "muSS_OS_pair_dR", "lep_pt", "nJetsCent", "nJetsCent40", "nBJetsLoose" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'I';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'I';
      fType[9] = 'I';
      fType[10] = 'I';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTG_AWB_lite() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTG_AWB_liteNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTG_AWB_lite::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTG_AWB_liteNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTG_AWB_liteNode*)current->GetRight();
         else current=(BDTG_AWB_liteNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDTG_AWB_lite::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.27557,-0.044886) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.610898,0.0221796) , 
9, 3, 1, 0, 0.322934,-0.178641) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.79519,0.059038) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.614778,0.0229555) , 
5, 1.97991, 1, 0, 0.677762,0.177762) , 
8, 4, 1, 0, 0.513846,0.0141372)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.346247,-0.02852) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.165154,-0.0638585) , 
5, 2.23526, 1, 0, 0.215306,-0.269878) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.42412,-0.0125889) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.693422,0.0350446) , 
8, 4, 1, 0, 0.60282,0.0956329) , 
9, 2, 1, 0, 0.501037,-0.000372196)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.319118,-0.0290865) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.14855,-0.0618474) , 
5, 2.41144, 1, 0, 0.212446,-0.245897) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4753,-0.00348818) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.703108,0.0344929) , 
9, 3, 1, 0, 0.611316,0.0958197) , 
8, 3, 1, 0, 0.520496,0.0177854)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.18701,-0.0500063) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.429657,-0.0121862) , 
8, 3, 1, 0, 0.326491,-0.140138) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.784549,0.0461939) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.608471,0.0132904) , 
5, 2.10062, 1, 0, 0.680783,0.13242) , 
9, 3, 1, 0, 0.485003,-0.0169198)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.1438,-0.0542051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34824,-0.0156341) , 
0, 98.6827, 1, 0, 0.197357,-0.212619) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.77219,0.0441564) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.544834,0.0043088) , 
5, 1.75283, 1, 0, 0.597022,0.0660556) , 
8, 3, 1, 0, 0.501609,-0.000476761)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.60663,0.0251837) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277005,-0.0317311) , 
5, 1.76112, 1, 0, 0.32526,-0.112938) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595289,0.00799641) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.735343,0.0346196) , 
1, 97.6395, 1, 0, 0.665436,0.104391) , 
8, 4, 1, 0, 0.509609,0.00513551)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417919,-0.0074822) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.212522,-0.0402841) , 
5, 2.45204, 1, 0, 0.299847,-0.125633) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72261,0.0308796) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.560075,-0.00130007) , 
3, 0.913948, 1, 0, 0.66265,0.0925596) , 
8, 4, 1, 0, 0.491118,-0.0106278)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549063,0.00876126) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.294495,-0.0301285) , 
5, 2.46092, 1, 0, 0.409293,-0.0594387) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.777229,0.0393473) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.672923,0.0176171) , 
10, 3, 1, 0, 0.741761,0.152531) , 
8, 5, 1, 0, 0.508083,0.00424725)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595392,0.0185482) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.276408,-0.0288894) , 
5, 1.79315, 1, 0, 0.324695,-0.102039) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.634916,0.00959609) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.760454,0.0351184) , 
2, 1, 1, 0, 0.68852,0.0645246) , 
9, 3, 1, 0, 0.484017,-0.0144091)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.145975,-0.0410526) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37525,-0.00686963) , 
0, 98.6827, 1, 0, 0.204022,-0.142725) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.68339,0.0223436) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.490497,-0.00511996) , 
5, 2.54526, 1, 0, 0.602349,0.0513692) , 
8, 3, 1, 0, 0.509516,0.00612399)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.243311,-0.0319012) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.405383,-0.000678214) , 
7, 46.7261, 1, 0, 0.311605,-0.0866129) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.68626,0.018699) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499039,-0.0183843) , 
4, 1.59993, 1, 0, 0.655177,0.0594356) , 
8, 4, 1, 0, 0.495507,-0.00817055)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519,0.0121678) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.264827,-0.0236794) , 
6, 1.88541, 1, 0, 0.312088,-0.076749) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.691401,0.0179996) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.453921,-0.026) , 
3, 1.59972, 1, 0, 0.664983,0.0615559) , 
8, 4, 1, 0, 0.50214,-0.00178362)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.177488,-0.0385444) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37704,-0.00487666) , 
1, 111.602, 1, 0, 0.234665,-0.127346) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.239633,-0.0225543) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.669036,0.0194528) , 
8, 3, 1, 0, 0.613022,0.0673009) , 
9, 2, 1, 0, 0.518427,0.0186695)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.719501,0.0293357) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358057,-0.0162971) , 
5, 1.64688, 1, 0, 0.407661,-0.0455398) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.704876,0.0148478) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.836158,0.0445172) , 
10, 3, 1, 0, 0.741413,0.106298) , 
8, 5, 1, 0, 0.506454,-0.000351081)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.164618,-0.0366807) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.365817,-0.00639452) , 
1, 106.523, 1, 0, 0.227526,-0.115467) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.390711,-0.00565605) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.703292,0.0153916) , 
8, 4, 1, 0, 0.593078,0.036399) , 
9, 2, 1, 0, 0.501861,-0.00153771)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.262583,-0.0252578) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.431362,0.000880443) , 
1, 97.6436, 1, 0, 0.334409,-0.0619543) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.715423,0.016893) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.527255,-0.0172438) , 
4, 1.59999, 1, 0, 0.68558,0.0515993) , 
9, 3, 1, 0, 0.491179,-0.010728)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.251691,-0.0178208) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.629419,0.0115302) , 
9, 2, 1, 0, 0.538638,0.0227662) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.398711,-0.0173052) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.242511,-0.0402415) , 
3, 1.92104, 1, 0, 0.341177,-0.116352) , 
3, 1.48567, 1, 0, 0.506366,-0.000615398)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.645489,0.0142431) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34082,-0.0156268) , 
5, 1.75383, 1, 0, 0.393019,-0.0463029) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.712235,0.0131885) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.813383,0.0334711) , 
8, 6, 1, 0, 0.758353,0.0988251) , 
8, 5, 1, 0, 0.496165,-0.00521947)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.152847,-0.033833) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304401,-0.00976982) , 
10, 2, 1, 0, 0.204042,-0.103477) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620497,0.0105251) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.339417,-0.0329067) , 
3, 1.71408, 1, 0, 0.592756,0.0276515) , 
9, 2, 1, 0, 0.486265,-0.00762291)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.603233,-0.0012644) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.783574,0.0379805) , 
2, 1, 1, 0, 0.675943,0.0626355) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.332516,-0.0203776) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.508741,0.00351604) , 
7, 39.7619, 1, 0, 0.423791,-0.0339906) , 
5, 1.97106, 1, 0, 0.496414,-0.00592338)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.244902,-0.0238753) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.405507,-0.00391963) , 
10, 2, 1, 0, 0.322858,-0.0583415) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.761745,0.0230595) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.613437,-0.00496879) , 
3, 0.685684, 1, 0, 0.68599,0.0378333) , 
9, 3, 1, 0, 0.482648,-0.0168543)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.132275,-0.0308665) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.261487,-0.0125776) , 
1, 105.213, 1, 0, 0.174817,-0.0922978) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.635711,0.0111632) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.329607,-0.0318263) , 
3, 1.82835, 1, 0, 0.613513,0.0357699) , 
8, 3, 1, 0, 0.498822,0.00229307)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596975,0.00714627) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.799428,0.0426637) , 
7, 106.022, 1, 0, 0.621677,0.0497722) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.278547,-0.0196452) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.684559,0.00926683) , 
8, 5, 1, 0, 0.369598,-0.0561606) , 
5, 2.54456, 1, 0, 0.505528,0.00181825)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626424,0.0175589) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462952,-0.00353715) , 
3, 0.685587, 1, 0, 0.539888,0.026935) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.350473,-0.0242261) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.554871,0.00569278) , 
1, 121.77, 1, 0, 0.411063,-0.0661706) , 
4, 1.25715, 1, 0, 0.501412,-0.000873002)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.140955,-0.0314004) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305499,-0.00689186) , 
10, 2, 1, 0, 0.19479,-0.0832775) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.770664,0.0377496) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.575551,0.000583931) , 
3, 0.114291, 1, 0, 0.590066,0.0146098) , 
9, 2, 1, 0, 0.480472,-0.0130445)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.27236,-0.0154312) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475136,0.0129371) , 
7, 58.0104, 1, 0, 0.332694,-0.0265879) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.687527,0.00749086) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.800547,0.0291727) , 
2, 1, 1, 0, 0.736849,0.0574399) , 
9, 3, 1, 0, 0.506903,0.0167856)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.703197,0.0305408) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45231,-0.00187703) , 
3, 0.685552, 1, 0, 0.560532,0.0501698) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.599753,0.00522423) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.395724,-0.0129845) , 
6, 2.16158, 1, 0, 0.4665,-0.027999) , 
4, 0.685716, 1, 0, 0.506294,0.00508141)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530192,0.0043096) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.371219,-0.0168797) , 
3, 0.457057, 1, 0, 0.417374,-0.0442191) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636747,0.0152771) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441509,-0.0144359) , 
6, 3.11041, 1, 0, 0.603204,0.0435918) , 
1, 97.6395, 1, 0, 0.501879,-0.0042876)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359651,-0.019498) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.528113,0.00512998) , 
7, 34.6395, 1, 0, 0.429288,-0.0378872) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549311,0.00462582) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.870967,0.0376118) , 
8, 6, 1, 0, 0.596447,0.0401176) , 
1, 92.4933, 1, 0, 0.5111,-0.000335592)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.792841,0.0250654) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.378874,-0.0131253) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.577501,0.00870095) , 
7, 47.1984, 1, 0, 0.463494,-0.0146358) , 
5, 1.34145, 1, 0, 0.492792,-0.00440928)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.756301,0.0274301) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.560358,-0.000772658) , 
4, 0.914012, 1, 0, 0.66692,0.0605363) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52135,0.00207412) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.368353,-0.0153118) , 
3, 0.457063, 1, 0, 0.412885,-0.0423697) , 
6, 2.08672, 1, 0, 0.493946,-0.00953303)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.364126,-0.0188512) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526607,0.00837556) , 
7, 29.3364, 1, 0, 0.439832,-0.0247978) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55197,0.00208044) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.689528,0.0267386) , 
2, 1, 1, 0, 0.609488,0.035459) , 
7, 50.5989, 1, 0, 0.512224,0.00772927)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.363104,-0.0184026) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.498752,0.00769484) , 
2, 1, 1, 0, 0.418009,-0.0204997) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614465,0.0155564) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.588225,-0.00770747) , 
1, 179.209, 1, 0, 0.605853,0.0334109) , 
1, 97.6484, 1, 0, 0.503944,-0.00203088)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488621,0.00077904) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.823252,0.0240841) , 
9, 4, 1, 0, 0.559843,0.0221758) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.422568,-0.00999098) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.246916,-0.0310347) , 
3, 1.83391, 1, 0, 0.389087,-0.0580785) , 
3, 0.914253, 1, 0, 0.490355,-0.0104518)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.328792,-0.0201577) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.578499,0.00990626) , 
7, 29.0237, 1, 0, 0.493484,0.000145126) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438362,-0.0416806) , 
7, 143.168, 1, 0, 0.48965,-0.0118209)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.687422,0.0296154) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529183,0.0011989) , 
3, 0.114311, 1, 0, 0.541878,0.014576) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293549,-0.0245338) , 
5, 3.1986, 1, 0, 0.516409,0.00293516)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.245779,-0.0172806) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.435524,0.000557932) , 
1, 97.6586, 1, 0, 0.322656,-0.0384488) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724734,0.0136296) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.629622,-0.019024) , 
7, 114.254, 1, 0, 0.711421,0.0387046) , 
9, 3, 1, 0, 0.490048,-0.00526345)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470897,-0.00286125) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457046,-0.0327907) , 
1, 253.475, 1, 0, 0.469999,-0.0199341) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.831576,0.025826) , 
9, 5, 1, 0, 0.49278,-0.0112871)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.271149,-0.0293417) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.523071,0.0014663) , 
7, 17.0033, 1, 0, 0.496979,-0.00635768) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436095,-0.0361225) , 
7, 156.909, 1, 0, 0.493716,-0.0143489)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.71047,-0.00171913) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.738979,0.0224978) , 
3, 0.342857, 1, 0, 0.730375,0.0624938) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.457212,-0.000969586) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30847,-0.0264125) , 
4, 1.71422, 1, 0, 0.433874,-0.0205392) , 
5, 1.82536, 1, 0, 0.501054,-0.00172601)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47927,0.0033864) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.811047,0.0202563) , 
8, 5, 1, 0, 0.585536,0.0340381) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228437,-0.0184363) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.602997,0.0003936) , 
8, 4, 1, 0, 0.399861,-0.0373646) , 
3, 0.914284, 1, 0, 0.508664,0.00455655)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.189902,-0.0117452) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.618364,0.00605646) , 
8, 3, 1, 0, 0.513261,0.0102449) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.283412,-0.0351714) , 
4, 2.05706, 1, 0, 0.500361,0.00112864)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.255102,-0.0207798) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.456101,0.00167188) , 
7, 40.3645, 1, 0, 0.354473,-0.0343793) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614125,0.00906276) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350165,-0.0188679) , 
3, 1.71418, 1, 0, 0.58895,0.026202) , 
10, 2, 1, 0, 0.499646,0.00321952)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.262313,-0.00565902) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.692099,0.010972) , 
8, 3, 1, 0, 0.607071,0.0319781) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.287539,-0.0129094) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.693494,0.00920638) , 
8, 5, 1, 0, 0.380289,-0.0301225) , 
5, 2.65312, 1, 0, 0.516388,0.00712623)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.450767,0.000487463) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.647007,0.0136196) , 
1, 97.6395, 1, 0, 0.540687,0.0261948) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305233,-0.0260626) , 
4, 1.94286, 1, 0, 0.520649,0.0149422)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.864976,0.0380196) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.487242,-0.0014639) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308663,-0.0265814) , 
4, 1.94286, 1, 0, 0.472666,-0.0143769) , 
5, 1.27381, 1, 0, 0.500041,-0.00376484)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440739,-0.00452831) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.645717,0.0128513) , 
1, 109.872, 1, 0, 0.511625,0.00636757) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.488758,-0.0306289) , 
1, 268.914, 1, 0, 0.510398,-0.000723334)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.633589,-0.0109968) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.600009,0.0138317) , 
6, 1.39175, 1, 0, 0.610036,0.0269514) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.382451,-0.00420376) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.451856,-0.0223597) , 
7, 98.2624, 1, 0, 0.39273,-0.0278491) , 
6, 2.42115, 1, 0, 0.493453,-0.00244868)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.652557,0.0251179) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.342584,-0.0147876) , 
3, 1.37137, 1, 0, 0.583204,0.0624648) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.762264,0.0108472) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436266,-0.00769444) , 
5, 1.52111, 1, 0, 0.474528,-0.0229355) , 
4, 0.571439, 1, 0, 0.512195,0.00666404)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.424995,-0.0062209) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.626046,0.00776675) , 
1, 103.994, 1, 0, 0.501571,-0.00339338) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.494744,-0.0309781) , 
1, 253.479, 1, 0, 0.501144,-0.0110487)    );
   return;
};
 
// Clean up
inline void ReadBDTG_AWB_lite::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDTG_AWB_lite::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
