// Class: ReadBDTG_AWB_lite
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTG_AWB_lite
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.12/07       [396295]
Creator        : abrinke1
Date           : Thu Jul  4 08:34:01 2019
Host           : Linux cmsbuild92.cern.ch 2.6.32-696.30.1.el6.x86_64 #1 SMP Tue May 22 06:09:36 CEST 2018 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/user/a/abrinke1/HiggsToMuMu/2018/CMSSW_10_2_11_patch1/src/H2MuAnalyzer/TrainMVA
Training events: 154963
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "50" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for GradBoost algorithm]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "8" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 56
H_pair_mass                   H_pair_mass                   H_pair_mass                   H_pair_mass                                                     'F'    [105.025375366,159.997497559]
H_pair_pt                     H_pair_pt                     H_pair_pt                     H_pair_pt                                                       'F'    [0.174321591854,1592.23571777]
OS_pair_mass                  OS_pair_mass                  OS_pair_mass                  OS_pair_mass                                                    'F'    [12.0022649765,1810.3840332]
OS_pair_pt                    OS_pair_pt                    OS_pair_pt                    OS_pair_pt                                                      'F'    [0.318144977093,1074.16772461]
lep_charge                    lep_charge                    lep_charge                    lep_charge                                                      'I'    [-1,1]
nEles                         nEles                         nEles                         Number of electrons                                             'I'    [0,1]
muH1_eta_abs                  muH1_eta_abs                  muH1_eta_abs                  |#eta| #mu1 from Higgs                                          'F'    [4.18702620664e-06,2.39995646477]
muH2_eta_abs                  muH2_eta_abs                  muH2_eta_abs                  |#eta| #mu2 from Higgs                                          'F'    [2.60819365394e-06,2.39999866486]
lep_H_pair_dEta               lep_H_pair_dEta               lep_H_pair_dEta               lep_H_pair_dEta                                                 'F'    [-4.70963478088,6.87605953217]
lep_H_pair_dR                 lep_H_pair_dR                 lep_H_pair_dR                 lep_H_pair_dR                                                   'F'    [0.00338603439741,7.0466504097]
lep_muOS_dEta                 lep_muOS_dEta                 lep_muOS_dEta                 lep_muOS_dEta                                                   'F'    [-4.72974967957,4.6595864296]
lep_muOS_dR                   lep_muOS_dR                   lep_muOS_dR                   lep_muOS_dR                                                     'F'    [0.0562677830458,5.2764210701]
muSS_muOS_dR                  muSS_muOS_dR                  muSS_muOS_dR                  muSS_muOS_dR                                                    'F'    [0.171248823404,5.13359117508]
muSS_muOS_dEta                muSS_muOS_dEta                muSS_muOS_dEta                muSS_muOS_dEta                                                  'F'    [-4.1203289032,4.38115739822]
muSS_OS_pair_dR               muSS_OS_pair_dR               muSS_OS_pair_dR               muSS_OS_pair_dR                                                 'F'    [0.0193049702793,7.22482681274]
muSS_OS_pair_dEta             muSS_OS_pair_dEta             muSS_OS_pair_dEta             muSS_OS_pair_dEta                                               'F'    [-4.59408426285,7.15338182449]
lep_pt                        lep_pt                        lep_pt                        lep_pt                                                          'F'    [10.00050354,1104.6217041]
muSS_pt                       muSS_pt                       muSS_pt                       muSS_pt                                                         'F'    [10.0215930939,1146.91748047]
nJetsCent                     nJetsCent                     nJetsCent                     nJetsCent                                                       'I'    [1,15]
nJetsCent30                   nJetsCent30                   nJetsCent30                   nJetsCent30                                                     'I'    [0,13]
nJetsCent40                   nJetsCent40                   nJetsCent40                   nJetsCent40                                                     'I'    [0,11]
nJetsCent50                   nJetsCent50                   nJetsCent50                   nJetsCent50                                                     'I'    [0,10]
nBJetsLoose                   nBJetsLoose                   nBJetsLoose                   nBJetsLoose                                                     'I'    [1,7]
nBJetsMed                     nBJetsMed                     nBJetsMed                     nBJetsMed                                                       'I'    [0,6]
nBJetsTight                   nBJetsTight                   nBJetsTight                   nBJetsTight                                                     'I'    [0,5]
MASS                          MASS                          MASS                          MASS                                                            'F'    [176.759963989,7420.69433594]
MET                           MET                           MET                           MET                                                             'F'    [0.358310252428,1206.82897949]
MHT                           MHT                           MHT                           MHT                                                             'F'    [0.139457061887,1201.07519531]
bjet1_muSS_dR                 bjet1_muSS_dR                 bjet1_muSS_dR                 bjet1_muSS_dR                                                   'F'    [-9,5.5970749855]
bjet1_lep_dR                  bjet1_lep_dR                  bjet1_lep_dR                  bjet1_lep_dR                                                    'F'    [-9,5.78883647919]
bjet1_muSS_pt                 bjet1_muSS_pt                 bjet1_muSS_pt                 bjet1_muSS_pt                                                   'F'    [-9,1107.84619141]
bjet1_lep_pt                  bjet1_lep_pt                  bjet1_lep_pt                  bjet1_lep_pt                                                    'F'    [-9,1098.72717285]
bjet1_muSS_mass               bjet1_muSS_mass               bjet1_muSS_mass               bjet1_muSS_mass                                                 'F'    [-9,1385.10180664]
bjet1_lep_mass                bjet1_lep_mass                bjet1_lep_mass                bjet1_lep_mass                                                  'F'    [-9,1373.69287109]
lep_MET_MT                    lep_MET_MT                    lep_MET_MT                    lep_MET_MT                                                      'F'    [0.000542099878658,1189.62780762]
lep_MHT_MT                    lep_MHT_MT                    lep_MHT_MT                    lep_MHT_MT                                                      'F'    [4.15259200963e-05,1138.2109375]
lep_MET_dPhi_abs              lep_MET_dPhi_abs              lep_MET_dPhi_abs              lep_MET_dPhi_abs                                                'F'    [6.43730163574e-06,3.14159250259]
lep_MHT_dPhi_abs              lep_MHT_dPhi_abs              lep_MHT_dPhi_abs              lep_MHT_dPhi_abs                                                'F'    [1.36482071866e-06,3.14159226418]
muSS_MET_MT                   muSS_MET_MT                   muSS_MET_MT                   muSS_MET_MT                                                     'F'    [0.00372117804363,1599.34997559]
muSS_MHT_MT                   muSS_MHT_MT                   muSS_MHT_MT                   muSS_MHT_MT                                                     'F'    [9.12741525099e-05,1757.95397949]
muSS_MET_dPhi_abs             muSS_MET_dPhi_abs             muSS_MET_dPhi_abs             muSS_MET_dPhi_abs                                               'F'    [6.103515625e-05,3.1415913105]
muSS_MHT_dPhi_abs             muSS_MHT_dPhi_abs             muSS_MHT_dPhi_abs             muSS_MHT_dPhi_abs                                               'F'    [1.42623048305e-06,3.1415746212]
MAN_W_jet2_pt                 MAN_W_jet2_pt                 MAN_W_jet2_pt                 MAN_W_jet2_pt                                                   'F'    [-9,569.684753418]
MAN_W_jj_mass                 MAN_W_jj_mass                 MAN_W_jj_mass                 MAN_W_jj_mass                                                   'F'    [-9,2907.10888672]
MAN_W_jj_pt                   MAN_W_jj_pt                   MAN_W_jj_pt                   MAN_W_jj_pt                                                     'F'    [-9,1644.10998535]
MAN_W_jj_dR                   MAN_W_jj_dR                   MAN_W_jj_dR                   MAN_W_jj_dR                                                     'F'    [-9,5.47298955917]
BDT_W_jj_mass                 BDT_W_jj_mass                 BDT_W_jj_mass                 BDT_W_jj_mass                                                   'F'    [-9,4162.35351562]
BDT_W_jj_pt                   BDT_W_jj_pt                   BDT_W_jj_pt                   BDT_W_jj_pt                                                     'F'    [-9,1622.90380859]
BDT_topH_mass                 BDT_topH_mass                 BDT_topH_mass                 BDT_topH_mass                                                   'F'    [-9,4372.21826172]
BDT_topH_pt                   BDT_topH_pt                   BDT_topH_pt                   BDT_topH_pt                                                     'F'    [-9,1561.1817627]
BDT_score_jj_blv              BDT_score_jj_blv              BDT_score_jj_blv              BDT_score_jj_blv                                                'F'    [-1.10000002384,0.994074881077]
BDT_score_bjj_lv              BDT_score_bjj_lv              BDT_score_bjj_lv              BDT_score_bjj_lv                                                'F'    [-1.10000002384,0.992367208004]
BDT_score_bj_blv              BDT_score_bj_blv              BDT_score_bj_blv              BDT_score_bj_blv                                                'F'    [-1.10000002384,0.99651825428]
BDT_score_bjj_blv             BDT_score_bjj_blv             BDT_score_bjj_blv             BDT_score_bjj_blv                                               'F'    [-1.10000002384,0.997210264206]
BDT_score_max                 BDT_score_max                 BDT_score_max                 BDT_score_max                                                   'F'    [-1.10000002384,0.997210264206]
BDT_best_match                BDT_best_match                BDT_best_match                BDT_best_match                                                  'I'    [0,9]
NSpec 9
samp_ID                       samp_ID                       samp_ID                       Sample ID                                                       'F'    [-26,38]
event                         event                         event                         Event number                                                    'F'    [3,170579920]
event_wgt                     event_wgt                     event_wgt                     Per-event scale factors                                         'F'    [-6.37165927887,18.4841747284]
samp_wgt                      samp_wgt                      samp_wgt                      Xsec x lumi for sample                                          'F'    [2.80000003841e-05,3.92017388344]
lepMVA_wgt                    lepMVA_wgt                    lepMVA_wgt                    lepMVA efficiency SF                                            'F'    [0.416317880154,1.15934419632]
total_wgt                     total_wgt                     total_wgt                     Overall weight                                                  'F'    [-0.412183314562,1.73373699188]
res_wgt                       res_wgt                       res_wgt                       Mass resolution weight                                          'F'    [1,1]
dimu_mass                     dimu_mass                     dimu_mass                     mass(#mu#mu)                  GeV                               'F'    [105.025375366,159.997497559]
nEles                         nEles                         nEles                         Number of electrons                                             'F'    [0,1]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTG_AWB_liteNode
   
#ifndef BDTG_AWB_liteNode__def
#define BDTG_AWB_liteNode__def
   
class BDTG_AWB_liteNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTG_AWB_liteNode ( BDTG_AWB_liteNode* left,BDTG_AWB_liteNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTG_AWB_liteNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTG_AWB_liteNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTG_AWB_liteNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTG_AWB_liteNode*   fLeft;     // pointer to the left daughter node
   BDTG_AWB_liteNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTG_AWB_liteNode::~BDTG_AWB_liteNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTG_AWB_liteNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTG_AWB_liteNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTG_AWB_lite : public IClassifierReader {

 public:

   // constructor
   ReadBDTG_AWB_lite( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDTG_AWB_lite" ),
        fNvars( 56 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "H_pair_mass", "H_pair_pt", "OS_pair_mass", "OS_pair_pt", "lep_charge", "nEles", "muH1_eta_abs", "muH2_eta_abs", "lep_H_pair_dEta", "lep_H_pair_dR", "lep_muOS_dEta", "lep_muOS_dR", "muSS_muOS_dR", "muSS_muOS_dEta", "muSS_OS_pair_dR", "muSS_OS_pair_dEta", "lep_pt", "muSS_pt", "nJetsCent", "nJetsCent30", "nJetsCent40", "nJetsCent50", "nBJetsLoose", "nBJetsMed", "nBJetsTight", "MASS", "MET", "MHT", "bjet1_muSS_dR", "bjet1_lep_dR", "bjet1_muSS_pt", "bjet1_lep_pt", "bjet1_muSS_mass", "bjet1_lep_mass", "lep_MET_MT", "lep_MHT_MT", "lep_MET_dPhi_abs", "lep_MHT_dPhi_abs", "muSS_MET_MT", "muSS_MHT_MT", "muSS_MET_dPhi_abs", "muSS_MHT_dPhi_abs", "MAN_W_jet2_pt", "MAN_W_jj_mass", "MAN_W_jj_pt", "MAN_W_jj_dR", "BDT_W_jj_mass", "BDT_W_jj_pt", "BDT_topH_mass", "BDT_topH_pt", "BDT_score_jj_blv", "BDT_score_bjj_lv", "BDT_score_bj_blv", "BDT_score_bjj_blv", "BDT_score_max", "BDT_best_match" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;
      fVmin[18] = 0;
      fVmax[18] = 0;
      fVmin[19] = 0;
      fVmax[19] = 0;
      fVmin[20] = 0;
      fVmax[20] = 0;
      fVmin[21] = 0;
      fVmax[21] = 0;
      fVmin[22] = 0;
      fVmax[22] = 0;
      fVmin[23] = 0;
      fVmax[23] = 0;
      fVmin[24] = 0;
      fVmax[24] = 0;
      fVmin[25] = 0;
      fVmax[25] = 0;
      fVmin[26] = 0;
      fVmax[26] = 0;
      fVmin[27] = 0;
      fVmax[27] = 0;
      fVmin[28] = 0;
      fVmax[28] = 0;
      fVmin[29] = 0;
      fVmax[29] = 0;
      fVmin[30] = 0;
      fVmax[30] = 0;
      fVmin[31] = 0;
      fVmax[31] = 0;
      fVmin[32] = 0;
      fVmax[32] = 0;
      fVmin[33] = 0;
      fVmax[33] = 0;
      fVmin[34] = 0;
      fVmax[34] = 0;
      fVmin[35] = 0;
      fVmax[35] = 0;
      fVmin[36] = 0;
      fVmax[36] = 0;
      fVmin[37] = 0;
      fVmax[37] = 0;
      fVmin[38] = 0;
      fVmax[38] = 0;
      fVmin[39] = 0;
      fVmax[39] = 0;
      fVmin[40] = 0;
      fVmax[40] = 0;
      fVmin[41] = 0;
      fVmax[41] = 0;
      fVmin[42] = 0;
      fVmax[42] = 0;
      fVmin[43] = 0;
      fVmax[43] = 0;
      fVmin[44] = 0;
      fVmax[44] = 0;
      fVmin[45] = 0;
      fVmax[45] = 0;
      fVmin[46] = 0;
      fVmax[46] = 0;
      fVmin[47] = 0;
      fVmax[47] = 0;
      fVmin[48] = 0;
      fVmax[48] = 0;
      fVmin[49] = 0;
      fVmax[49] = 0;
      fVmin[50] = 0;
      fVmax[50] = 0;
      fVmin[51] = 0;
      fVmax[51] = 0;
      fVmin[52] = 0;
      fVmax[52] = 0;
      fVmin[53] = 0;
      fVmax[53] = 0;
      fVmin[54] = 0;
      fVmax[54] = 0;
      fVmin[55] = 0;
      fVmax[55] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'I';
      fType[5] = 'I';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'I';
      fType[19] = 'I';
      fType[20] = 'I';
      fType[21] = 'I';
      fType[22] = 'I';
      fType[23] = 'I';
      fType[24] = 'I';
      fType[25] = 'F';
      fType[26] = 'F';
      fType[27] = 'F';
      fType[28] = 'F';
      fType[29] = 'F';
      fType[30] = 'F';
      fType[31] = 'F';
      fType[32] = 'F';
      fType[33] = 'F';
      fType[34] = 'F';
      fType[35] = 'F';
      fType[36] = 'F';
      fType[37] = 'F';
      fType[38] = 'F';
      fType[39] = 'F';
      fType[40] = 'F';
      fType[41] = 'F';
      fType[42] = 'F';
      fType[43] = 'F';
      fType[44] = 'F';
      fType[45] = 'F';
      fType[46] = 'F';
      fType[47] = 'F';
      fType[48] = 'F';
      fType[49] = 'F';
      fType[50] = 'F';
      fType[51] = 'F';
      fType[52] = 'F';
      fType[53] = 'F';
      fType[54] = 'F';
      fType[55] = 'I';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTG_AWB_lite() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[56];
   double fVmax[56];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[56];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTG_AWB_liteNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTG_AWB_lite::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTG_AWB_liteNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTG_AWB_liteNode*)current->GetRight();
         else current=(BDTG_AWB_liteNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDTG_AWB_lite::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.161676,-0.0676647) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.814623,0.0629247) , 
0, 119.983, 1, 0, 0.662483,0.162483) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0180215,-0.0963957) , 
0, 131.202, 1, 0, 0.51384,0.0138404)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.147449,-0.0640464) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.851928,0.0645031) , 
0, 119.644, 1, 0, 0.680491,0.165492) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.182276,-0.0627534) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00398116,-0.090429) , 
0, 136.086, 1, 0, 0.0678966,-0.399137) , 
0, 128.614, 1, 0, 0.500881,-5.47331e-05)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.154292,-0.057024) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.845383,0.0574863) , 
0, 119.641, 1, 0, 0.683254,0.150772) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.209641,-0.050999) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00334534,-0.0837169) , 
0, 136.075, 1, 0, 0.0750329,-0.351305) , 
0, 128.605, 1, 0, 0.520285,0.0162436)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.142868,-0.0553858) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.835844,0.0508742) , 
0, 119.896, 1, 0, 0.649068,0.107564) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0279879,-0.0755376) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.119619,-0.0575361) , 
54, 0.696761, 1, 0, 0.0598847,-0.326759) , 
0, 128.808, 1, 0, 0.485034,-0.0133555)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.383887,-0.0286739) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.796571,0.0473084) , 
19, 3, 1, 0, 0.644433,-0.0425621) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0199279,-0.0717203) , 
0, 131.228, 1, 0, 0.501825,-0.00312954)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0995953,-0.0602947) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.797175,0.0392904) , 
0, 117.405, 1, 0, 0.672143,0.099686) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.202659,-0.03953) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00310943,-0.0711945) , 
0, 136.09, 1, 0, 0.0711334,-0.261696) , 
0, 128.613, 1, 0, 0.509773,0.00205395)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.260065,-0.0379193) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.850515,0.0447093) , 
0, 121.866, 1, 0, 0.654132,0.0778767) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.136531,-0.0443106) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0255713,-0.066563) , 
12, 2.46345, 1, 0, 0.0674158,-0.244675) , 
0, 128.593, 1, 0, 0.491246,-0.0116709)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.216499,-0.039087) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.836537,0.0426976) , 
0, 121.228, 1, 0, 0.658234,0.0848393) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0195606,-0.0626596) , 
0, 131.202, 1, 0, 0.507833,0.0080368)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461474,-0.00848438) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.173469,-0.0548908) , 
12, 2.01127, 1, 0, 0.231496,-0.188743) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.782534,0.0377012) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.112074,-0.0431163) , 
0, 128.642, 1, 0, 0.633936,0.0900333) , 
54, 0.1982, 1, 0, 0.484216,-0.0136802)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.198802,-0.0371799) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.846156,0.0366843) , 
0, 120.749, 1, 0, 0.672229,0.069786) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.209635,-0.0284078) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.003913,-0.0624376) , 
0, 136.074, 1, 0, 0.0758055,-0.179068) , 
0, 128.598, 1, 0, 0.509697,0.00197072)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.22455,-0.0331543) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.809468,0.0306249) , 
0, 121.247, 1, 0, 0.643636,0.0503583) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0180254,-0.0572982) , 
0, 131.216, 1, 0, 0.495791,-0.00525914)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.51481,0.00745269) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.213546,-0.0443433) , 
12, 1.97277, 1, 0, 0.276366,-0.127445) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.797209,0.0343848) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.116429,-0.0328088) , 
0, 128.637, 1, 0, 0.650035,0.0850791) , 
19, 3, 1, 0, 0.501872,0.0246138)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.212908,-0.0437724) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438733,0.00112355) , 
2, 121.94, 1, 0, 0.27122,-0.122468) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.814034,0.0359885) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.150919,-0.0205636) , 
0, 128.598, 1, 0, 0.695045,0.104623) , 
19, 3, 1, 0, 0.518267,0.028961)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.097329,-0.0478644) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.808389,0.0280067) , 
0, 117.365, 1, 0, 0.680572,0.0560537) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.131105,-0.0268511) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0359966,-0.0532229) , 
14, 2.4422, 1, 0, 0.0719291,-0.133418) , 
0, 128.585, 1, 0, 0.507104,0.00205283)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494167,0.00265913) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.195736,-0.0409484) , 
12, 2.01127, 1, 0, 0.256531,-0.109492) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.806911,0.0327119) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.116756,-0.0276789) , 
0, 128.578, 1, 0, 0.650383,0.0766077) , 
54, 0.29814, 1, 0, 0.501597,0.00630467)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.538325,0.0105169) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.210339,-0.0371691) , 
12, 1.79825, 1, 0, 0.260245,-0.102526) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.798538,0.0254697) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.123029,-0.0229822) , 
0, 128.585, 1, 0, 0.656467,0.0593878) , 
19, 3, 1, 0, 0.491253,0.0108368)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.166308,-0.0434823) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.376343,-0.00417174) , 
2, 113.287, 1, 0, 0.220714,-0.113124) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.77777,0.023775) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.101092,-0.0280201) , 
0, 128.667, 1, 0, 0.622972,0.0492123) , 
54, -0.301063, 1, 0, 0.506799,0.00232902)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.112157,-0.0467279) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374076,-0.0170762) , 
53, -0.700778, 1, 0, 0.178663,-0.155027) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.836153,0.0278769) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0295333,-0.0472457) , 
0, 130.108, 1, 0, 0.584337,0.0340025) , 
0, 120.768, 1, 0, 0.496109,-0.00710821)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596996,0.0167133) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204401,-0.0393891) , 
12, 1.75893, 1, 0, 0.255175,-0.101635) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.808573,0.0417687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.595945,0.00572031) , 
12, 1.7454, 1, 0, 0.654203,0.0531663) , 
51, -0.502181, 1, 0, 0.486185,-0.0120156)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.645003,0.0178417) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.265293,-0.0276535) , 
12, 1.55458, 1, 0, 0.306762,-0.0710464) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.836091,0.0296021) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.110222,-0.0232397) , 
0, 128.579, 1, 0, 0.663116,0.0621997) , 
18, 4, 1, 0, 0.49653,0.0151812)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.103592,-0.0438196) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.780305,0.0169513) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0284131,-0.0450183) , 
0, 130.094, 1, 0, 0.550904,0.0123652) , 
0, 118.133, 1, 0, 0.482405,-0.014252)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.156392,-0.0477863) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.273894,-0.021345) , 
0, 123.378, 1, 0, 0.22778,-0.103219) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.263185,-0.0250428) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.704845,0.0277275) , 
0, 120.749, 1, 0, 0.625767,0.0472341) , 
55, 3, 1, 0, 0.498696,0.0194698)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.112185,-0.0381265) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.796451,0.0194844) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0286728,-0.0433343) , 
0, 130.081, 1, 0, 0.57147,0.0218183) , 
0, 118.114, 1, 0, 0.506104,-0.000391882)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0987947,-0.0383133) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.799188,0.018364) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0307206,-0.042066) , 
0, 130.142, 1, 0, 0.581206,0.0211859) , 
0, 118.197, 1, 0, 0.501257,-0.00347686)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.164356,-0.0480613) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.286887,-0.00976821) , 
3, 93.4427, 1, 0, 0.196163,-0.108003) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.782763,0.0373691) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.54612,-0.00209866) , 
12, 1.50254, 1, 0, 0.590073,0.0162082) , 
20, 2, 1, 0, 0.480724,-0.00240704)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.143657,-0.0340166) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.400278,0.00723766) , 
1, 104.297, 1, 0, 0.203646,-0.0623594) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.731362,0.0289603) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.538153,-0.00150135) , 
12, 2.536, 1, 0, 0.65671,0.0505788) , 
54, -0.201196, 1, 0, 0.507004,0.0132605)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0982902,-0.0359219) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.813932,0.0211017) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0295474,-0.0406125) , 
0, 130.082, 1, 0, 0.587839,0.0282014) , 
0, 118.114, 1, 0, 0.505898,0.00469473)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.604637,-0.00442478) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.786577,0.0398723) , 
10, -0.972963, 1, 0, 0.740168,0.0836767) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.133583,-0.0357728) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499139,-0.00271646) , 
0, 120.749, 1, 0, 0.423555,-0.0294845) , 
12, 1.82536, 1, 0, 0.501861,-0.00149712)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.700029,0.0189949) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.873946,0.0495549) , 
38, 152.34, 1, 0, 0.771501,0.0929406) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.361426,-0.0201029) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.677657,0.0129511) , 
19, 4, 1, 0, 0.460516,-0.0137008) , 
12, 1.52987, 1, 0, 0.510785,-0.00868568)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.759764,0.0316847) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.385899,-0.0157866) , 
12, 1.34145, 1, 0, 0.421573,-0.0305224) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.874277,0.0550527) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.613264,0.00248395) , 
35, 86.1181, 1, 0, 0.782708,0.0980573) , 
52, 0.79685, 1, 0, 0.492913,-0.0051223)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0957529,-0.0343) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.829008,0.0182197) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0928983,-0.0298129) , 
0, 128.117, 1, 0, 0.569742,0.0158699) , 
0, 118.153, 1, 0, 0.494012,-0.00264262)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572492,0.000148599) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.736764,0.0309147) , 
16, 50.6009, 1, 0, 0.649992,0.0410272) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.272413,-0.0248372) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.637633,0.013006) , 
52, 0.496116, 1, 0, 0.376849,-0.0349427) , 
12, 2.42102, 1, 0, 0.51214,0.00268605)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.172869,-0.0271195) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425725,0.00315277) , 
1, 103.792, 1, 0, 0.236173,-0.0481982) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587954,-0.00741609) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.701488,0.0273526) , 
41, 1.49594, 1, 0, 0.648855,0.0290278) , 
54, 0.0983385, 1, 0, 0.504569,0.00202733)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.212322,-0.0273018) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.621588,0.0128476) , 
20, 2, 1, 0, 0.515009,0.0204124) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.29359,-0.0461215) , 
34, 135.08, 1, 0, 0.490397,-0.00676393)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.131186,-0.0370138) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.265489,-0.00917797) , 
16, 50.6127, 1, 0, 0.178758,-0.0831686) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.811061,0.0191583) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.012767,-0.0454499) , 
0, 131.944, 1, 0, 0.573679,0.0210487) , 
0, 120.727, 1, 0, 0.489734,-0.00110399)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.609157,0.00335148) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23934,-0.0266769) , 
0, 126.066, 1, 0, 0.45636,-0.0164434) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.780739,0.0456325) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.6986,-0.0103622) , 
46, 108.525, 1, 0, 0.749873,0.0655976) , 
1, 152.277, 1, 0, 0.516213,0.000286439)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.239179,-0.0324992) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441025,-0.00486651) , 
2, 97.6586, 1, 0, 0.32186,-0.0537916) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661316,0.00292311) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.778245,0.0352778) , 
5, 1, 1, 0, 0.711623,-0.000206176) , 
20, 3, 1, 0, 0.489861,-0.00197158)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.298087,-0.0121362) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.327164,-0.046127) , 
48, 169.871, 1, 0, 0.302995,-0.0468222) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.691799,0.0150606) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.491208,-0.0247663) , 
36, 2.69278, 1, 0, 0.663938,0.0236423) , 
18, 4, 1, 0, 0.492837,-0.00199453)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.339162,-0.0263807) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.696186,0.00392835) , 
53, 0.796739, 1, 0, 0.420862,-0.0602639) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.875007,0.0205715) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.195124,-0.0187159) , 
0, 126.87, 1, 0, 0.528139,0.00872267) , 
0, 123.383, 1, 0, 0.494167,-0.013124)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.711686,0.016184) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.872514,0.0631322) , 
40, 2.54322, 1, 0, 0.75302,0.0710533) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.46105,-0.00100442) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.291222,-0.0293027) , 
34, 102.054, 1, 0, 0.419526,-0.019636) , 
12, 1.82536, 1, 0, 0.501879,0.00275875)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.176038,-0.0308287) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.142073,-0.0234551) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.629176,0.0121955) , 
0, 118.13, 1, 0, 0.56618,0.0164145) , 
19, 2, 1, 0, 0.508699,0.0122522)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.101615,-0.028414) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.804142,0.0147191) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0299479,-0.0333283) , 
0, 130.102, 1, 0, 0.571386,0.0169366) , 
0, 118.149, 1, 0, 0.500303,0.00312068)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421623,0.00588449) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.347823,-0.0244608) , 
4, 0, 1, 0, 0.381703,-0.00586164) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.635876,-0.00877478) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.803099,0.0314015) , 
2, 64.0006, 1, 0, 0.756778,0.0461166) , 
19, 4, 1, 0, 0.499405,0.00304164)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.393324,-0.0116414) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.604396,0.0205328) , 
39, 128.568, 1, 0, 0.443558,-0.00953848) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.884109,0.0578768) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.730853,0.0150223) , 
10, -0.0562496, 1, 0, 0.79429,0.0728974) , 
52, 0.796198, 1, 0, 0.516245,0.00754594)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.257402,-0.0163174) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.796626,0.0187576) , 
0, 121.592, 1, 0, 0.649289,0.0226163) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00659339,-0.0482329) , 
0, 133.897, 1, 0, 0.520925,0.00752236)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.88974,0.0447426) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.155714,-0.023128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.546659,0.00127377) , 
0, 120.835, 1, 0, 0.463072,-0.0107759) , 
12, 1.27381, 1, 0, 0.499565,-0.0010708)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.285514,-0.0311173) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.63182,0.0134441) , 
52, 0.692595, 1, 0, 0.368392,-0.0465365) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.263678,-0.0145278) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.641504,0.0138663) , 
20, 2, 1, 0, 0.552837,0.0241068) , 
13, -1.14189, 1, 0, 0.510464,0.00178003)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.215939,-0.0194548) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.619934,0.00846132) , 
20, 2, 1, 0, 0.514819,0.0111799) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.286959,-0.0376665) , 
35, 143.617, 1, 0, 0.493647,-0.00593193)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499042,0.00801516) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.411579,-0.0129476) , 
26, 62.8771, 1, 0, 0.448081,-0.00996955) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.718344,0.013302) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.927455,0.0963362) , 
40, 2.54319, 1, 0, 0.774002,0.0820573) , 
1, 151.845, 1, 0, 0.512437,0.00820182)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443578,-0.00831804) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.600608,0.014794) , 
16, 54.1258, 1, 0, 0.505957,0.00225575) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.445849,-0.055791) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.517838,-0.00386054) , 
37, 1.3462, 1, 0, 0.473328,-0.081661) , 
48, 316.69, 1, 0, 0.501427,-0.00939457)    );
   return;
};
 
// Clean up
inline void ReadBDTG_AWB_lite::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDTG_AWB_lite::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
