// Class: ReadBDTG_AWB_lite
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTG_AWB_lite
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.12/07       [396295]
Creator        : abrinke1
Date           : Thu Jul  4 07:21:43 2019
Host           : Linux cmsbuild92.cern.ch 2.6.32-696.30.1.el6.x86_64 #1 SMP Tue May 22 06:09:36 CEST 2018 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/user/a/abrinke1/HiggsToMuMu/2018/CMSSW_10_2_11_patch1/src/H2MuAnalyzer/TrainMVA
Training events: 154963
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "50" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for GradBoost algorithm]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 14
H_pair_pt                     H_pair_pt                     H_pair_pt                     H_pair_pt                                                       'F'    [0.174321591854,1592.23571777]
OS_pair_mass                  OS_pair_mass                  OS_pair_mass                  OS_pair_mass                                                    'F'    [12.0022649765,1810.3840332]
nEles                         nEles                         nEles                         Number of electrons                                             'I'    [0,1]
muH1_eta_abs                  muH1_eta_abs                  muH1_eta_abs                  |#eta| #mu1 from Higgs                                          'F'    [4.18702620664e-06,2.39995646477]
muH2_eta_abs                  muH2_eta_abs                  muH2_eta_abs                  |#eta| #mu2 from Higgs                                          'F'    [2.60819365394e-06,2.39999866486]
muSS_muOS_dR                  muSS_muOS_dR                  muSS_muOS_dR                  muSS_muOS_dR                                                    'F'    [0.171248823404,5.13359117508]
muSS_OS_pair_dR               muSS_OS_pair_dR               muSS_OS_pair_dR               muSS_OS_pair_dR                                                 'F'    [0.0193049702793,7.22482681274]
lep_pt                        lep_pt                        lep_pt                        lep_pt                                                          'F'    [10.00050354,1104.6217041]
nJetsCent                     nJetsCent                     nJetsCent                     nJetsCent                                                       'I'    [1,15]
nJetsCent40                   nJetsCent40                   nJetsCent40                   nJetsCent40                                                     'I'    [0,11]
nBJetsLoose                   nBJetsLoose                   nBJetsLoose                   nBJetsLoose                                                     'I'    [1,7]
BDT_score_bjj_lv              BDT_score_bjj_lv              BDT_score_bjj_lv              BDT_score_bjj_lv                                                'F'    [-1.10000002384,0.992367208004]
BDT_score_bj_blv              BDT_score_bj_blv              BDT_score_bj_blv              BDT_score_bj_blv                                                'F'    [-1.10000002384,0.99651825428]
BDT_score_max                 BDT_score_max                 BDT_score_max                 BDT_score_max                                                   'F'    [-1.10000002384,0.997210264206]
NSpec 9
samp_ID                       samp_ID                       samp_ID                       Sample ID                                                       'F'    [-26,38]
event                         event                         event                         Event number                                                    'F'    [3,170579920]
event_wgt                     event_wgt                     event_wgt                     Per-event scale factors                                         'F'    [-6.37165927887,18.4841747284]
samp_wgt                      samp_wgt                      samp_wgt                      Xsec x lumi for sample                                          'F'    [2.80000003841e-05,3.92017388344]
lepMVA_wgt                    lepMVA_wgt                    lepMVA_wgt                    lepMVA efficiency SF                                            'F'    [0.416317880154,1.15934419632]
total_wgt                     total_wgt                     total_wgt                     Overall weight                                                  'F'    [-0.412183314562,1.73373699188]
res_wgt                       res_wgt                       res_wgt                       Mass resolution weight                                          'F'    [0.020715624094,1.94245529175]
dimu_mass                     dimu_mass                     dimu_mass                     mass(#mu#mu)                  GeV                               'F'    [105.025375366,159.997497559]
nEles                         nEles                         nEles                         Number of electrons                                             'F'    [0,1]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTG_AWB_liteNode
   
#ifndef BDTG_AWB_liteNode__def
#define BDTG_AWB_liteNode__def
   
class BDTG_AWB_liteNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTG_AWB_liteNode ( BDTG_AWB_liteNode* left,BDTG_AWB_liteNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTG_AWB_liteNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTG_AWB_liteNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTG_AWB_liteNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTG_AWB_liteNode*   fLeft;     // pointer to the left daughter node
   BDTG_AWB_liteNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTG_AWB_liteNode::~BDTG_AWB_liteNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTG_AWB_liteNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTG_AWB_liteNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTG_AWB_lite : public IClassifierReader {

 public:

   // constructor
   ReadBDTG_AWB_lite( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDTG_AWB_lite" ),
        fNvars( 14 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "H_pair_pt", "OS_pair_mass", "nEles", "muH1_eta_abs", "muH2_eta_abs", "muSS_muOS_dR", "muSS_OS_pair_dR", "lep_pt", "nJetsCent", "nJetsCent40", "nBJetsLoose", "BDT_score_bjj_lv", "BDT_score_bj_blv", "BDT_score_max" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'I';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'I';
      fType[9] = 'I';
      fType[10] = 'I';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTG_AWB_lite() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[14];
   double fVmax[14];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[14];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTG_AWB_liteNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTG_AWB_lite::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTG_AWB_liteNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTG_AWB_liteNode*)current->GetRight();
         else current=(BDTG_AWB_liteNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDTG_AWB_lite::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.349313,-0.0301375) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.176225,-0.0647551) , 
5, 2.46095, 1, 0, 0.246854,-0.253146) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.744907,0.0489813) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.556156,0.0112311) , 
5, 2.30697, 1, 0, 0.647633,0.147633) , 
13, 0.0981698, 1, 0, 0.513846,0.0138456)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.346247,-0.0303521) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.165154,-0.0630747) , 
5, 2.23526, 1, 0, 0.215306,-0.26936) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.42412,-0.0145327) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.693422,0.035888) , 
8, 4, 1, 0, 0.60282,0.0952001) , 
9, 2, 1, 0, 0.501037,-0.000555258)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.174802,-0.0560747) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420729,-0.0101633) , 
0, 104.297, 1, 0, 0.23147,-0.22525) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564268,0.0092157) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.732626,0.0413831) , 
12, 0.597181, 1, 0, 0.642233,0.120088) , 
13, -0.201196, 1, 0, 0.520496,0.0177407)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535625,0.00861104) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.225383,-0.0458792) , 
5, 1.81831, 1, 0, 0.26983,-0.186944) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.508653,-0.00203372) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.701408,0.0318495) , 
9, 3, 1, 0, 0.639094,0.104758) , 
11, -0.402592, 1, 0, 0.485003,-0.0176695)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.152448,-0.0535578) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.316764,-0.0214842) , 
7, 46.7261, 1, 0, 0.210031,-0.204504) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.774574,0.0441089) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.5601,0.00610375) , 
5, 1.75283, 1, 0, 0.610457,0.0741029) , 
13, -0.500797, 1, 0, 0.501609,-0.00163085)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.60663,0.0190702) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277005,-0.0317795) , 
5, 1.76112, 1, 0, 0.32526,-0.1173) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595289,0.00894227) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.735343,0.0348075) , 
1, 97.6395, 1, 0, 0.665436,0.107366) , 
8, 4, 1, 0, 0.509609,0.00474505)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.368601,-0.0138044) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.1588,-0.0480198) , 
5, 2.45204, 1, 0, 0.236831,-0.166512) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659558,0.0205165) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.406726,-0.0303963) , 
3, 1.71396, 1, 0, 0.637257,0.0784466) , 
13, 0.198017, 1, 0, 0.491118,-0.0109531)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549063,0.00712304) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.294495,-0.0300552) , 
5, 2.46092, 1, 0, 0.409293,-0.0625691) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.777229,0.0411597) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.672923,0.0175389) , 
10, 3, 1, 0, 0.741761,0.158423) , 
8, 5, 1, 0, 0.508083,0.00387796)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595392,0.012951) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.276408,-0.0299086) , 
5, 1.79315, 1, 0, 0.324695,-0.109728) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.634916,0.011597) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.760454,0.0366293) , 
2, 1, 1, 0, 0.68852,0.069957) , 
9, 3, 1, 0, 0.484017,-0.014782)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.155513,-0.038867) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39632,-0.00546132) , 
0, 98.0507, 1, 0, 0.217081,-0.133352) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.686825,0.0239557) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.539619,-0.00274469) , 
3, 0.799915, 1, 0, 0.621644,0.058356) , 
13, -0.401016, 1, 0, 0.509516,0.00522271)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461962,0.000427837) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24464,-0.0298166) , 
6, 2.24452, 1, 0, 0.311605,-0.0933424) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.68626,0.0195614) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499039,-0.0178863) , 
4, 1.59993, 1, 0, 0.655177,0.0634241) , 
8, 4, 1, 0, 0.495507,-0.00916679)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.132317,-0.0430491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.287161,-0.0130395) , 
7, 40.9572, 1, 0, 0.196261,-0.131648) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587476,0.0056499) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.859646,0.0504923) , 
8, 7, 1, 0, 0.605777,0.0416817) , 
13, -0.800504, 1, 0, 0.50214,-0.00262427)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.288321,-0.022038) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.637829,0.0145544) , 
9, 3, 1, 0, 0.361703,-0.0642428) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.794301,0.0383399) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526531,-0.0119096) , 
4, 1.59988, 1, 0, 0.747661,0.138307) , 
13, 0.797476, 1, 0, 0.518427,0.0181175)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.719501,0.0283459) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358057,-0.0163796) , 
5, 1.64688, 1, 0, 0.407661,-0.0460526) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.704876,0.0153576) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.836158,0.0432061) , 
10, 3, 1, 0, 0.741413,0.105785) , 
8, 5, 1, 0, 0.506454,-0.00085179)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.211244,-0.0277169) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.383934,0.000815775) , 
1, 119.799, 1, 0, 0.255433,-0.0867326) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688238,0.0170626) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.575451,-0.0025711) , 
4, 1.14282, 1, 0, 0.650993,0.0490293) , 
13, 0.29814, 1, 0, 0.501861,-0.00215499)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.424942,-0.00761265) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.232453,-0.0378826) , 
6, 3.11753, 1, 0, 0.386421,-0.0604016) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.742188,0.029761) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.692383,0.00640914) , 
11, 0.793094, 1, 0, 0.72273,0.0956616) , 
12, 0.597181, 1, 0, 0.491179,-0.0117888)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.163759,-0.0350727) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358521,-0.00475673) , 
1, 98.5292, 1, 0, 0.234928,-0.0976163) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.629419,0.0118228) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416336,-0.0213463) , 
3, 1.48567, 1, 0, 0.596937,0.030734) , 
9, 2, 1, 0, 0.506366,-0.000733261)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.344466,-0.016579) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.691527,0.0189941) , 
12, 0.796249, 1, 0, 0.393019,-0.0508947) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.708673,0.0144665) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.844998,0.0378244) , 
0, 119.006, 1, 0, 0.758353,0.101001) , 
8, 5, 1, 0, 0.496165,-0.00802395)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.326587,-0.00394103) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.140889,-0.0314733) , 
6, 2.16813, 1, 0, 0.182703,-0.0960255) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.657819,0.0119908) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374534,-0.0332397) , 
3, 1.71408, 1, 0, 0.630952,0.0346504) , 
13, -0.301063, 1, 0, 0.486265,-0.00752966)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.197559,-0.0308055) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.266173,-0.0120136) , 
2, 1, 1, 0, 0.224281,-0.0643729) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.606739,0.00792116) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.359423,-0.0318882) , 
4, 1.94258, 1, 0, 0.587243,0.0208995) , 
9, 2, 1, 0, 0.496414,-0.00800269)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.381875,-0.00866919) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.215477,-0.0278067) , 
5, 2.83867, 1, 0, 0.322858,-0.0643669) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.761745,0.0240263) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.613437,-0.00317422) , 
3, 0.685684, 1, 0, 0.68599,0.0442111) , 
9, 3, 1, 0, 0.482648,-0.0166429)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.226571,-0.0196302) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60566,0.00497421) , 
11, -0.900741, 1, 0, 0.460036,-0.0158622) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.758954,0.0210151) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.907054,0.0534955) , 
12, 0.939477, 1, 0, 0.829497,0.157255) , 
12, 0.896684, 1, 0, 0.498822,0.00231173)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596975,0.00760756) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.799428,0.0410965) , 
7, 106.022, 1, 0, 0.621677,0.0507525) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.278547,-0.0208038) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.684559,0.00865778) , 
8, 5, 1, 0, 0.369598,-0.0595561) , 
5, 2.54456, 1, 0, 0.505528,0.000766179)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49014,0.0057265) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.371381,-0.0175592) , 
4, 0.914302, 1, 0, 0.434258,-0.0226205) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.803539,0.0265585) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.645709,0.00116895) , 
6, 2.67589, 1, 0, 0.748856,0.0742394) , 
12, 0.796249, 1, 0, 0.501412,-0.00194492)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.140955,-0.0307656) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305499,-0.00814351) , 
10, 2, 1, 0, 0.19479,-0.082757) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.770664,0.0374241) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.575551,0.000611758) , 
3, 0.114291, 1, 0, 0.590066,0.0145783) , 
9, 2, 1, 0, 0.480472,-0.0128685)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.27236,-0.0157392) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475136,0.0108783) , 
7, 58.0104, 1, 0, 0.332694,-0.0295514) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.771262,0.0337318) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.713118,0.00592263) , 
11, 0.593705, 1, 0, 0.736849,0.0763079) , 
9, 3, 1, 0, 0.506903,0.0167793)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574748,0.0075464) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374412,-0.00923366) , 
6, 2.1598, 1, 0, 0.440224,-0.0146488) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.631448,-0.00799592) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.934615,0.052705) , 
12, 0.596052, 1, 0, 0.787114,0.0892359) , 
9, 4, 1, 0, 0.506294,0.00544685)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512712,0.000655366) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344595,-0.021036) , 
3, 0.685563, 1, 0, 0.417374,-0.0475323) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636747,0.0159152) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441509,-0.0111782) , 
6, 3.11041, 1, 0, 0.603204,0.0478346) , 
1, 97.6395, 1, 0, 0.501879,-0.00416478)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359651,-0.0191006) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.528113,0.00322099) , 
7, 34.6395, 1, 0, 0.429288,-0.0399376) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549311,0.00532203) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.870967,0.0372892) , 
8, 6, 1, 0, 0.596447,0.0420198) , 
1, 92.4933, 1, 0, 0.5111,-0.000439098)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484249,0.00212553) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.333167,-0.0178038) , 
3, 0.914183, 1, 0, 0.421093,-0.0254293) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.723674,0.00943503) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.887357,0.04109) , 
12, 0.920454, 1, 0, 0.783178,0.0825561) , 
12, 0.79685, 1, 0, 0.492792,-0.00404618)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.756301,0.0263924) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.560358,-0.000994791) , 
4, 0.914012, 1, 0, 0.66692,0.0574715) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52135,0.00222547) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.368353,-0.0164154) , 
3, 0.457063, 1, 0, 0.412885,-0.0446005) , 
6, 2.08672, 1, 0, 0.493946,-0.01203)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.364126,-0.0189712) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526607,0.00667427) , 
7, 29.3364, 1, 0, 0.439832,-0.028114) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55926,0.0329085) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.631845,0.00334083) , 
10, 2, 1, 0, 0.609488,0.0503403) , 
7, 50.5989, 1, 0, 0.512224,0.00582266)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.350356,-0.0141352) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.771746,0.021655) , 
12, 0.796198, 1, 0, 0.418009,-0.0331322) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614465,0.0165092) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.588225,-0.00462737) , 
1, 179.209, 1, 0, 0.605853,0.0395521) , 
1, 97.6484, 1, 0, 0.503944,0.000119312)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.61615,0.0172023) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.516893,-0.00256232) , 
4, 0.685723, 1, 0, 0.559843,0.0236038) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.352247,-0.0222568) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.442741,-0.00274992) , 
2, 1, 1, 0, 0.389087,-0.0421148) , 
3, 0.914253, 1, 0, 0.490355,-0.00966874)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.362727,-0.0157609) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.596368,0.0116872) , 
7, 35.3647, 1, 0, 0.493484,-0.000302198) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438362,-0.0404048) , 
7, 143.168, 1, 0, 0.48965,-0.0118768)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.822069,0.04384) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.744836,-0.00124483) , 
11, 0.79286, 1, 0, 0.788724,0.103785) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.658196,0.0276371) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465288,-0.00538929) , 
3, 0.114292, 1, 0, 0.479064,-0.0121507) , 
5, 1.47058, 1, 0, 0.516409,0.00183123)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.245779,-0.018838) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.435524,0.00140505) , 
1, 97.6586, 1, 0, 0.322656,-0.0397934) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724734,0.0138091) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.629622,-0.0182591) , 
7, 114.254, 1, 0, 0.711421,0.0394437) , 
9, 3, 1, 0, 0.490048,-0.00571038)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543388,0.00244743) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.412793,-0.0109164) , 
3, 0.685731, 1, 0, 0.473836,-0.0191973) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.846615,0.0325861) , 
8, 7, 1, 0, 0.49278,-0.0119499)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.271149,-0.0274738) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.523071,0.00136446) , 
7, 17.0033, 1, 0, 0.496979,-0.00576261) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436095,-0.0360163) , 
7, 156.909, 1, 0, 0.493716,-0.0137011)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.757358,0.0286444) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.709811,0.00748229) , 
7, 50.6016, 1, 0, 0.730375,0.0685785) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.457212,-0.0025234) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30847,-0.026717) , 
4, 1.71422, 1, 0, 0.433874,-0.0257096) , 
5, 1.82536, 1, 0, 0.501054,-0.00434631)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552008,0.00517161) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.854324,0.0334429) , 
11, 0.892589, 1, 0, 0.585536,0.0326972) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430272,-0.00457428) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.265619,-0.0269517) , 
3, 1.83404, 1, 0, 0.399861,-0.0348653) , 
3, 0.914284, 1, 0, 0.508664,0.00472539)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.309456,-0.00481933) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.695746,0.00847133) , 
8, 4, 1, 0, 0.513261,0.0102617) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.283412,-0.0334266) , 
4, 2.05706, 1, 0, 0.500361,0.00154107)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.813327,0.0426788) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.754888,-0.0081644) , 
8, 5, 1, 0, 0.784695,0.0850849) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.355158,-0.00806107) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.752563,0.014254) , 
8, 5, 1, 0, 0.457379,-0.00929293) , 
5, 1.52111, 1, 0, 0.499646,0.00255372)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.415416,0.0024238) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.572255,-0.0216697) , 
11, 0.792965, 1, 0, 0.443394,-0.00845135) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.582442,-0.011364) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.865758,0.0319398) , 
9, 3, 1, 0, 0.794813,0.0748327) , 
12, 0.796198, 1, 0, 0.516388,0.00881151)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45333,0.000149446) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.654901,0.0138691) , 
1, 97.6395, 1, 0, 0.545336,0.0256163) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.325606,-0.0196568) , 
4, 1.82857, 1, 0, 0.520649,0.0139347)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.864976,0.0376609) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440989,-0.00939964) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.515119,0.0037909) , 
2, 1, 1, 0, 0.472666,-0.00393881) , 
5, 1.27381, 1, 0, 0.500041,-0.0041925)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440739,-0.00494307) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.645717,0.0139512) , 
1, 109.872, 1, 0, 0.511625,0.00680461) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.488758,-0.0314478) , 
1, 268.914, 1, 0, 0.510398,-0.000469663)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.633589,-0.0104416) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.600009,0.0126704) , 
6, 1.39175, 1, 0, 0.610036,0.0238671) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.365084,-0.0037373) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.553687,-0.0250171) , 
11, 0.793003, 1, 0, 0.39273,-0.0275108) , 
6, 2.42115, 1, 0, 0.493453,-0.00369681)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.652557,0.0248986) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.342584,-0.0178473) , 
3, 1.37137, 1, 0, 0.583204,0.058687) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.762264,0.0123534) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436266,-0.00779357) , 
5, 1.52111, 1, 0, 0.474528,-0.0221446) , 
4, 0.571439, 1, 0, 0.512195,0.00587141)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266828,-0.00608297) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.613696,0.00900314) , 
11, -0.919706, 1, 0, 0.465944,0.0125609) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456128,-0.0398474) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.723471,-0.00529427) , 
12, 0.297679, 1, 0, 0.614467,-0.0827475) , 
11, 0.793094, 1, 0, 0.501144,-0.0100268)    );
   return;
};
 
// Clean up
inline void ReadBDTG_AWB_lite::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDTG_AWB_lite::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
