// Class: ReadBDTG_AWB_lite
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTG_AWB_lite
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.12/07       [396295]
Creator        : abrinke1
Date           : Thu Jul  4 07:44:55 2019
Host           : Linux cmsbuild92.cern.ch 2.6.32-696.30.1.el6.x86_64 #1 SMP Tue May 22 06:09:36 CEST 2018 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/user/a/abrinke1/HiggsToMuMu/2018/CMSSW_10_2_11_patch1/src/H2MuAnalyzer/TrainMVA
Training events: 154963
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "50" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for GradBoost algorithm]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "5" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 25
H_pair_pt                     H_pair_pt                     H_pair_pt                     H_pair_pt                                                       'F'    [0.174321591854,1592.23571777]
OS_pair_mass                  OS_pair_mass                  OS_pair_mass                  OS_pair_mass                                                    'F'    [12.0022649765,1810.3840332]
nEles                         nEles                         nEles                         Number of electrons                                             'I'    [0,1]
muH1_eta_abs                  muH1_eta_abs                  muH1_eta_abs                  |#eta| #mu1 from Higgs                                          'F'    [4.18702620664e-06,2.39995646477]
muH2_eta_abs                  muH2_eta_abs                  muH2_eta_abs                  |#eta| #mu2 from Higgs                                          'F'    [2.60819365394e-06,2.39999866486]
muSS_muOS_dR                  muSS_muOS_dR                  muSS_muOS_dR                  muSS_muOS_dR                                                    'F'    [0.171248823404,5.13359117508]
muSS_OS_pair_dR               muSS_OS_pair_dR               muSS_OS_pair_dR               muSS_OS_pair_dR                                                 'F'    [0.0193049702793,7.22482681274]
lep_pt                        lep_pt                        lep_pt                        lep_pt                                                          'F'    [10.00050354,1104.6217041]
muSS_pt                       muSS_pt                       muSS_pt                       muSS_pt                                                         'F'    [10.0215930939,1146.91748047]
nJetsCent                     nJetsCent                     nJetsCent                     nJetsCent                                                       'I'    [1,15]
nJetsCent30                   nJetsCent30                   nJetsCent30                   nJetsCent30                                                     'I'    [0,13]
nJetsCent40                   nJetsCent40                   nJetsCent40                   nJetsCent40                                                     'I'    [0,11]
nBJetsLoose                   nBJetsLoose                   nBJetsLoose                   nBJetsLoose                                                     'I'    [1,7]
nBJetsMed                     nBJetsMed                     nBJetsMed                     nBJetsMed                                                       'I'    [0,6]
lep_MET_MT                    lep_MET_MT                    lep_MET_MT                    lep_MET_MT                                                      'F'    [0.000542099878658,1189.62780762]
lep_MHT_MT                    lep_MHT_MT                    lep_MHT_MT                    lep_MHT_MT                                                      'F'    [4.15259200963e-05,1138.2109375]
muSS_MET_MT                   muSS_MET_MT                   muSS_MET_MT                   muSS_MET_MT                                                     'F'    [0.00372117804363,1599.34997559]
muSS_MHT_MT                   muSS_MHT_MT                   muSS_MHT_MT                   muSS_MHT_MT                                                     'F'    [9.12741525099e-05,1757.95397949]
BDT_W_jj_mass                 BDT_W_jj_mass                 BDT_W_jj_mass                 BDT_W_jj_mass                                                   'F'    [-9,4162.35351562]
BDT_score_jj_blv              BDT_score_jj_blv              BDT_score_jj_blv              BDT_score_jj_blv                                                'F'    [-1.10000002384,0.994074881077]
BDT_score_bjj_lv              BDT_score_bjj_lv              BDT_score_bjj_lv              BDT_score_bjj_lv                                                'F'    [-1.10000002384,0.992367208004]
BDT_score_bj_blv              BDT_score_bj_blv              BDT_score_bj_blv              BDT_score_bj_blv                                                'F'    [-1.10000002384,0.99651825428]
BDT_score_bjj_blv             BDT_score_bjj_blv             BDT_score_bjj_blv             BDT_score_bjj_blv                                               'F'    [-1.10000002384,0.997210264206]
BDT_score_max                 BDT_score_max                 BDT_score_max                 BDT_score_max                                                   'F'    [-1.10000002384,0.997210264206]
BDT_best_match                BDT_best_match                BDT_best_match                BDT_best_match                                                  'I'    [0,9]
NSpec 9
samp_ID                       samp_ID                       samp_ID                       Sample ID                                                       'F'    [-26,38]
event                         event                         event                         Event number                                                    'F'    [3,170579920]
event_wgt                     event_wgt                     event_wgt                     Per-event scale factors                                         'F'    [-6.37165927887,18.4841747284]
samp_wgt                      samp_wgt                      samp_wgt                      Xsec x lumi for sample                                          'F'    [2.80000003841e-05,3.92017388344]
lepMVA_wgt                    lepMVA_wgt                    lepMVA_wgt                    lepMVA efficiency SF                                            'F'    [0.416317880154,1.15934419632]
total_wgt                     total_wgt                     total_wgt                     Overall weight                                                  'F'    [-0.412183314562,1.73373699188]
res_wgt                       res_wgt                       res_wgt                       Mass resolution weight                                          'F'    [0.020715624094,1.94245529175]
dimu_mass                     dimu_mass                     dimu_mass                     mass(#mu#mu)                  GeV                               'F'    [105.025375366,159.997497559]
nEles                         nEles                         nEles                         Number of electrons                                             'F'    [0,1]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTG_AWB_liteNode
   
#ifndef BDTG_AWB_liteNode__def
#define BDTG_AWB_liteNode__def
   
class BDTG_AWB_liteNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTG_AWB_liteNode ( BDTG_AWB_liteNode* left,BDTG_AWB_liteNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTG_AWB_liteNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTG_AWB_liteNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTG_AWB_liteNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTG_AWB_liteNode*   fLeft;     // pointer to the left daughter node
   BDTG_AWB_liteNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTG_AWB_liteNode::~BDTG_AWB_liteNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTG_AWB_liteNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTG_AWB_liteNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTG_AWB_lite : public IClassifierReader {

 public:

   // constructor
   ReadBDTG_AWB_lite( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDTG_AWB_lite" ),
        fNvars( 25 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "H_pair_pt", "OS_pair_mass", "nEles", "muH1_eta_abs", "muH2_eta_abs", "muSS_muOS_dR", "muSS_OS_pair_dR", "lep_pt", "muSS_pt", "nJetsCent", "nJetsCent30", "nJetsCent40", "nBJetsLoose", "nBJetsMed", "lep_MET_MT", "lep_MHT_MT", "muSS_MET_MT", "muSS_MHT_MT", "BDT_W_jj_mass", "BDT_score_jj_blv", "BDT_score_bjj_lv", "BDT_score_bj_blv", "BDT_score_bjj_blv", "BDT_score_max", "BDT_best_match" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;
      fVmin[18] = 0;
      fVmax[18] = 0;
      fVmin[19] = 0;
      fVmax[19] = 0;
      fVmin[20] = 0;
      fVmax[20] = 0;
      fVmin[21] = 0;
      fVmax[21] = 0;
      fVmin[22] = 0;
      fVmax[22] = 0;
      fVmin[23] = 0;
      fVmax[23] = 0;
      fVmin[24] = 0;
      fVmax[24] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'I';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'I';
      fType[10] = 'I';
      fType[11] = 'I';
      fType[12] = 'I';
      fType[13] = 'I';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';
      fType[20] = 'F';
      fType[21] = 'F';
      fType[22] = 'F';
      fType[23] = 'F';
      fType[24] = 'I';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTG_AWB_lite() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[25];
   double fVmax[25];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[25];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTG_AWB_liteNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTG_AWB_lite::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTG_AWB_liteNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTG_AWB_liteNode*)current->GetRight();
         else current=(BDTG_AWB_liteNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDTG_AWB_lite::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.208815,-0.058237) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.433406,-0.0133187) , 
23, -0.201729, 1, 0, 0.280882,-0.219118) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.756978,0.0513955) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.58303,0.016606) , 
5, 2.30697, 1, 0, 0.668413,0.168413) , 
10, 3, 1, 0, 0.513846,0.0141485)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.577841,0.0190331) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231642,-0.0493725) , 
5, 1.77732, 1, 0, 0.276607,-0.201949) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.579605,0.0125353) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.803176,0.0571288) , 
21, 0.796249, 1, 0, 0.648181,0.130864) , 
10, 3, 1, 0, 0.501037,-0.000410523)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.180924,-0.0552225) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.423388,-0.00943296) , 
0, 104.297, 1, 0, 0.237618,-0.220329) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673234,0.0304279) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388014,-0.02641) , 
14, 135.08, 1, 0, 0.644947,0.123405) , 
23, -0.101328, 1, 0, 0.520496,0.0183839)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.137067,-0.0608794) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335833,-0.0241329) , 
10, 2, 1, 0, 0.252684,-0.187343) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507516,-0.0053084) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.701399,0.0316826) , 
20, -0.0040732, 1, 0, 0.647886,0.106391) , 
10, 3, 1, 0, 0.485003,-0.0169615)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507719,0.00940035) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.211617,-0.0427251) , 
5, 2.02048, 1, 0, 0.271677,-0.155726) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.690064,0.0272998) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393998,-0.0280908) , 
14, 127.972, 1, 0, 0.656461,0.103455) , 
10, 3, 1, 0, 0.501609,-0.000845099)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.60663,0.0195938) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277005,-0.0327341) , 
5, 1.76112, 1, 0, 0.32526,-0.1203) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.699903,0.0281086) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444633,-0.015813) , 
14, 117.55, 1, 0, 0.665436,0.108406) , 
9, 4, 1, 0, 0.509609,0.00392345)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.368601,-0.0143973) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.1588,-0.0495745) , 
5, 2.45204, 1, 0, 0.236831,-0.172337) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659558,0.0211272) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.406726,-0.0300379) , 
3, 1.71396, 1, 0, 0.637257,0.0810598) , 
23, 0.198017, 1, 0, 0.491118,-0.0114194)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528554,0.00597354) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.283718,-0.0315855) , 
5, 2.46092, 1, 0, 0.392833,-0.0697518) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.874641,0.0574589) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.707056,0.0254559) , 
5, 1.54485, 1, 0, 0.740357,0.153384) , 
10, 4, 1, 0, 0.508083,0.0044336)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.181302,-0.0418443) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354987,-0.0112782) , 
1, 109.55, 1, 0, 0.229915,-0.153174) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.668823,0.0192341) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.378866,-0.0248563) , 
14, 127.97, 1, 0, 0.634157,0.0668183) , 
23, 0.1982, 1, 0, 0.484017,-0.0148889)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.155513,-0.0389491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39632,-0.00404677) , 
0, 98.0507, 1, 0, 0.217081,-0.131652) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.680676,0.0213193) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489295,-0.00947426) , 
5, 2.76108, 1, 0, 0.621644,0.0564504) , 
23, -0.401016, 1, 0, 0.509516,0.00431622)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.243311,-0.0332356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.405383,-0.00339865) , 
7, 46.7261, 1, 0, 0.311605,-0.094361) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.68626,0.0197363) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499039,-0.0172612) , 
4, 1.59993, 1, 0, 0.655177,0.0643927) , 
9, 4, 1, 0, 0.495507,-0.00911749)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519,0.00886719) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.264827,-0.024958) , 
6, 1.88541, 1, 0, 0.312088,-0.083547) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.691401,0.0191065) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.453921,-0.0244279) , 
3, 1.59972, 1, 0, 0.664983,0.0669771) , 
9, 4, 1, 0, 0.50214,-0.00201676)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.288321,-0.0213734) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.637829,0.0130842) , 
11, 3, 1, 0, 0.361703,-0.062899) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.794301,0.0380924) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526531,-0.0119457) , 
4, 1.59988, 1, 0, 0.747661,0.136444) , 
23, 0.797476, 1, 0, 0.518427,0.0181632)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.639222,0.00694269) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.777548,0.0388346) , 
17, 83.7122, 1, 0, 0.726641,0.125366) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.342602,-0.018731) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.696814,0.0164033) , 
9, 5, 1, 0, 0.435837,-0.042063) , 
5, 1.86308, 1, 0, 0.506454,-0.00138455)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432081,0.00474521) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.2104,-0.0274686) , 
6, 2.16652, 1, 0, 0.264166,-0.0833773) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.706507,0.0211935) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.577438,-0.0106623) , 
18, 153.845, 1, 0, 0.670256,0.0570805) , 
10, 3, 1, 0, 0.501861,-0.0011862)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.666846,0.0169581) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.349643,-0.0176973) , 
5, 1.53625, 1, 0, 0.386421,-0.0600244) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.745458,0.0276278) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.630642,-0.00509649) , 
18, 153.153, 1, 0, 0.72273,0.0965805) , 
21, 0.597181, 1, 0, 0.491179,-0.0112429)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.268167,-0.0245706) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.64295,0.00319752) , 
11, 3, 1, 0, 0.424042,-0.0552086) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.65087,0.0211081) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.455779,-0.00858962) , 
15, 95.7451, 1, 0, 0.592047,0.0542851) , 
1, 92.5024, 1, 0, 0.506366,-0.00144489)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.344466,-0.0169161) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.691527,0.0170101) , 
21, 0.796249, 1, 0, 0.393019,-0.0533278) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.713429,0.0142936) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.865127,0.0461824) , 
16, 119.515, 1, 0, 0.758353,0.105299) , 
9, 5, 1, 0, 0.496165,-0.00855459)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.56598,0.012505) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.212846,-0.0253876) , 
5, 1.75893, 1, 0, 0.255248,-0.0827526) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.682635,0.0150615) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386194,-0.034746) , 
3, 1.71395, 1, 0, 0.654271,0.0457653) , 
20, -0.502181, 1, 0, 0.486265,-0.0083464)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.153786,-0.0343908) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308304,-0.0133797) , 
7, 40.976, 1, 0, 0.224281,-0.0986546) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543571,-0.00203651) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.699239,0.0226454) , 
1, 134.341, 1, 0, 0.587243,0.0218047) , 
11, 2, 1, 0, 0.496414,-0.00811127)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.323963,-0.0187351) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.531157,0.0185149) , 
17, 161.966, 1, 0, 0.351217,-0.0586387) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.737879,0.0220034) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.610618,-0.00132763) , 
3, 0.685684, 1, 0, 0.673345,0.0446863) , 
21, 0.197845, 1, 0, 0.482648,-0.016481)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.318966,-0.0091495) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.149724,-0.0320342) , 
5, 2.55881, 1, 0, 0.225729,-0.0815434) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649828,0.0127285) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.329929,-0.0324027) , 
3, 1.82835, 1, 0, 0.62637,0.0416975) , 
24, 3, 1, 0, 0.498822,0.00238722)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596975,0.00711581) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.799428,0.0408086) , 
7, 106.022, 1, 0, 0.621677,0.0486943) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.278547,-0.0210131) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.684559,0.00986633) , 
9, 5, 1, 0, 0.369598,-0.0586951) , 
5, 2.54456, 1, 0, 0.505528,9.4532e-05)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447605,-0.00353996) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.81773,0.0314066) , 
21, 0.796249, 1, 0, 0.523047,0.0148011) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.337385,-0.0270178) , 
14, 127.97, 1, 0, 0.501412,-0.00114239)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.222869,-0.0187875) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.628529,0.0100936) , 
11, 2, 1, 0, 0.525043,0.0143876) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485713,-0.00750835) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.194755,-0.0428015) , 
6, 2.14621, 1, 0, 0.279556,-0.133258) , 
14, 117.546, 1, 0, 0.480472,-0.0125675)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.404177,0.00547561) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.184324,-0.0238301) , 
6, 2.03595, 1, 0, 0.225021,-0.0647594) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581415,0.00206656) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.774467,0.0335126) , 
7, 62.1325, 1, 0, 0.642007,0.0518037) , 
24, 3, 1, 0, 0.506903,0.0147405)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.279317,-0.0100122) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.699419,0.0151374) , 
20, -0.50221, 1, 0, 0.526853,0.0229601) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.26229,-0.0442064) , 
15, 154.872, 1, 0, 0.506294,0.00580835)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.355921,-0.0283779) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465973,-0.000415468) , 
15, 51.6252, 1, 0, 0.417374,-0.0514103) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.602191,0.0166686) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.606898,-0.0103698) , 
18, 149.082, 1, 0, 0.603204,0.0450975) , 
1, 97.6395, 1, 0, 0.501879,-0.00752391)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359651,-0.0205098) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.528113,0.00578803) , 
7, 34.6395, 1, 0, 0.429288,-0.038676) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549311,0.00461304) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.870967,0.0399974) , 
9, 6, 1, 0, 0.596447,0.041611) , 
1, 92.4933, 1, 0, 0.5111,4.64633e-06)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518217,0.00465392) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.361073,-0.0177147) , 
3, 0.914178, 1, 0, 0.453466,-0.0185143) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.795811,0.0198974) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.888856,0.0461703) , 
3, 0.570659, 1, 0, 0.8415,0.130951) , 
21, 0.896684, 1, 0, 0.492792,-0.00336656)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.756301,0.0276918) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.560358,-0.00252434) , 
4, 0.914012, 1, 0, 0.66692,0.0581221) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.458981,-0.00453001) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.252132,-0.0333341) , 
14, 106.633, 1, 0, 0.412885,-0.044385) , 
6, 2.08672, 1, 0, 0.493946,-0.0116756)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433414,-0.00149801) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.463839,-0.0320097) , 
18, 129.862, 1, 0, 0.439832,-0.0347391) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.660364,0.0229687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.322942,-0.0272184) , 
15, 153.676, 1, 0, 0.609488,0.06096) , 
7, 50.5989, 1, 0, 0.512224,0.00609563)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.350356,-0.0146053) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.771746,0.0212984) , 
21, 0.796198, 1, 0, 0.418009,-0.0349954) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649901,0.0150462) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438181,-0.00873008) , 
14, 113.299, 1, 0, 0.605853,0.0402519) , 
1, 97.6484, 1, 0, 0.503944,-0.000571396)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.61615,0.0195906) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.516893,-0.00137655) , 
4, 0.685723, 1, 0, 0.559843,0.0303966) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.352247,-0.0246951) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.442741,-0.00288001) , 
2, 1, 1, 0, 0.389087,-0.0440493) , 
3, 0.914253, 1, 0, 0.490355,-0.00777058)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.302508,-0.0094654) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.698961,0.0123282) , 
19, -0.303005, 1, 0, 0.484801,0.00409041) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.662922,0.00223775) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.443253,-0.0329704) , 
4, 0.571304, 1, 0, 0.513195,-0.0980919) , 
18, 169.845, 1, 0, 0.48965,-0.0133609)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.85213,0.0423495) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474082,0.00147503) , 
5, 1.47058, 1, 0, 0.512097,0.0221875) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454329,-0.0272107) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.726385,0.00630328) , 
10, 5, 1, 0, 0.533934,-0.0769826) , 
18, 152.343, 1, 0, 0.516409,0.00223419)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.245779,-0.0199161) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.435524,0.00180097) , 
1, 97.6586, 1, 0, 0.322656,-0.0413365) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.660653,0.00042589) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.778456,0.0234372) , 
2, 1, 1, 0, 0.711421,0.0271507) , 
11, 3, 1, 0, 0.490048,-0.00531432)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.619067,0.0166056) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462477,-0.00850866) , 
4, 1.1425, 1, 0, 0.564808,0.0305872) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45998,-0.00656779) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.295643,-0.029917) , 
15, 110.37, 1, 0, 0.428958,-0.0446297) , 
3, 0.685717, 1, 0, 0.49278,-0.0092929)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527419,0.00216067) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.367404,-0.0219004) , 
4, 1.82857, 1, 0, 0.511677,-0.00131533) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271337,-0.0350432) , 
15, 154.878, 1, 0, 0.493716,-0.0125905)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560623,0.00741587) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.370734,-0.0189713) , 
4, 1.71426, 1, 0, 0.533497,0.0140948) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.292545,-0.0250826) , 
15, 129.174, 1, 0, 0.501054,-0.00163561)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537738,0.0053128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.854267,0.0308818) , 
10, 5, 1, 0, 0.585536,0.0353713) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333949,-0.0256162) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.432166,-0.00406827) , 
15, 40.329, 1, 0, 0.399861,-0.0444144) , 
3, 0.914284, 1, 0, 0.508664,0.00237962)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484907,-0.000529478) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.708582,0.0233853) , 
7, 83.4516, 1, 0, 0.521014,0.0130686) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.262509,-0.0299725) , 
15, 153.678, 1, 0, 0.500361,0.0021927)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.381959,-0.000629593) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37943,-0.0239385) , 
18, 104.861, 1, 0, 0.381502,-0.0215573) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.80558,0.0216912) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.618805,-0.00488004) , 
3, 1.14279, 1, 0, 0.757324,0.0558884) , 
10, 4, 1, 0, 0.499646,0.00318557)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475945,0.00205472) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.695548,0.0363234) , 
17, 140.951, 1, 0, 0.515477,0.0320847) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.618982,-0.00138119) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.468556,-0.0242592) , 
4, 0.571326, 1, 0, 0.520055,-0.0725006) , 
18, 153.845, 1, 0, 0.516388,0.0112775)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45333,-0.000954478) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.654901,0.0153526) , 
1, 97.6395, 1, 0, 0.545336,0.0256) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.325606,-0.0233102) , 
4, 1.82857, 1, 0, 0.520649,0.0122366)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.864976,0.0365232) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550339,0.00448396) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.406306,-0.0112205) , 
3, 0.685631, 1, 0, 0.472666,-0.0158614) , 
5, 1.27381, 1, 0, 0.500041,-0.00548059)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440739,-0.0053838) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.645717,0.0157571) , 
1, 109.872, 1, 0, 0.511625,0.00789914) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.488758,-0.0322048) , 
1, 268.914, 1, 0, 0.510398,0.000687588)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.419769,-0.00562118) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.640887,0.0123042) , 
1, 97.6436, 1, 0, 0.514874,0.00839095) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.283213,-0.0278984) , 
15, 143.617, 1, 0, 0.493453,-0.00301471)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.652557,0.0239889) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.342584,-0.0204867) , 
3, 1.37137, 1, 0, 0.583204,0.0521631) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47271,-0.001895) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484924,-0.0217037) , 
18, 189.636, 1, 0, 0.474528,-0.0204647) , 
4, 0.571439, 1, 0, 0.512195,0.00470791)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.406575,-0.0111631) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.513723,0.0134401) , 
15, 54.2006, 1, 0, 0.465944,0.00980774) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456128,-0.0403178) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.723471,-0.00516974) , 
21, 0.297679, 1, 0, 0.614467,-0.0809596) , 
20, 0.793094, 1, 0, 0.501144,-0.0117038)    );
   return;
};
 
// Clean up
inline void ReadBDTG_AWB_lite::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDTG_AWB_lite::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
