// Class: ReadBDTG_UF_v1
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTG_UF_v1
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.10/09       [395785]
Creator        : xzuo
Date           : Wed May 22 21:43:20 2019
Host           : Linux cmsbuild49.cern.ch 2.6.32-696.10.2.el6.x86_64 #1 SMP Thu Sep 14 16:35:02 CEST 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/x/xzuo/h2mm_944/src/H2MuAnalyzer/TrainMVA
Training events: 65096
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
nCuts: "10" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for GradBoost algorithm]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 19
dimu_mass                     dimu_mass                     dimu_mass                     M(#mu#mu)                     GeV                               'F'    [100.245376587,159.985855103]
dimu_pt                       dimu_pt                       dimu_pt                       p_{T}(#mu#mu)                 GeV                               'F'    [0.199431017041,1447.98535156]
dimu_abs_eta                  dimu_abs_eta                  dimu_abs_eta                  |#eta(#mu#mu)|                                                  'F'    [6.77469688526e-06,9.2078742981]
dimu_abs_dPhi                 dimu_abs_dPhi                 dimu_abs_dPhi                 |d#phi(#mu#mu)|                                                 'F'    [7.05718994141e-05,3.14158463478]
dimu_dR                       dimu_dR                       dimu_dR                       dR(#mu#mu)                                                      'F'    [0.183524668217,5.25127029419]
dilep_mass                    dilep_mass                    dilep_mass                    M(ll)                         GeV                               'F'    [81.0000228882,100.997390747]
dilep_pt                      dilep_pt                      dilep_pt                      P_{T}(ll)                     GeV                               'F'    [0.0361974164844,1245.30322266]
dilep_abs_eta                 dilep_abs_eta                 dilep_abs_eta                 |#eta(ll)|                                                      'F'    [4.93135776196e-05,7.79659891129]
dilep_abs_dPhi                dilep_abs_dPhi                dilep_abs_dPhi                |d#phi(ll)|                                                     'F'    [1.50203704834e-05,3.14156246185]
dilep_dR                      dilep_dR                      dilep_dR                      dR(ll)                                                          'F'    [0.174173697829,5.1896777153]
lep_ID                        lep_ID                        lep_ID                        lep_ID                                                          'I'    [11,13]
dipair_dEta_H                 dipair_dEta_H                 dipair_dEta_H                 d#eta((#mu#mu),(ll))                                            'F'    [-9.73767852783,9.95819950104]
dipair_dPhi_H                 dipair_dPhi_H                 dipair_dPhi_H                 d#phi((#mu#mu),(ll))                                            'F'    [-3.14159107208,3.14159178734]
cts_dipair_H                  cts_dipair_H                  cts_dipair_H                  cos(#theta*)((#mu#mu),(ll))                                     'F'    [-0.99999243021,0.999974668026]
cs_costheta                   cs_costheta                   cs_costheta                   cos(#theta_{CS})                                                'F'    [-0.999996781349,0.999979615211]
met_pt                        met_pt                        met_pt                        p_{T}(met)                    GeV                               'F'    [0.0415822900832,477.782775879]
mht_pt                        mht_pt                        mht_pt                        p_{T}(mht)                    GeV                               'F'    [0.0488994345069,1205.65710449]
mht_Rtrans_4lPt               mht_Rtrans_4lPt               mht_Rtrans_4lPt               (mht/P_{T}(4l))_{T}                                             'F'    [-1.5,2.5]
mht_Rlongi_4lPt               mht_Rlongi_4lPt               mht_Rlongi_4lPt               (mht/P_{T}(4l))_{L}                                             'F'    [-1.5,1.5]
NSpec 5
event_wgt                     event_wgt                     event_wgt                     event weight                                                    'F'    [-1.52057862282,3.92260169983]
xsec_norm                     xsec_norm                     xsec_norm                     xsec normal                                                     'F'    [2.90000007226e-05,0.0557130016387]
Sample_ID                     Sample_ID                     Sample_ID                     Sample ID                                                       'F'    [-23230000,1302325]
lep_ID                        lep_ID                        lep_ID                        the Z decays to                                                 'F'    [11,13]
dimu_mass                     dimu_mass                     dimu_mass                     mass(#mu#mu)                  GeV                               'F'    [100.245376587,159.985855103]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTG_UF_v1Node
   
#ifndef BDTG_UF_v1Node__def
#define BDTG_UF_v1Node__def
   
class BDTG_UF_v1Node {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTG_UF_v1Node ( BDTG_UF_v1Node* left,BDTG_UF_v1Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTG_UF_v1Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTG_UF_v1Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTG_UF_v1Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTG_UF_v1Node*   fLeft;     // pointer to the left daughter node
   BDTG_UF_v1Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTG_UF_v1Node::~BDTG_UF_v1Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTG_UF_v1Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTG_UF_v1Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTG_UF_v1 : public IClassifierReader {

 public:

   // constructor
   ReadBDTG_UF_v1( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDTG_UF_v1" ),
        fNvars( 19 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "dimu_mass", "dimu_pt", "dimu_abs_eta", "dimu_abs_dPhi", "dimu_dR", "dilep_mass", "dilep_pt", "dilep_abs_eta", "dilep_abs_dPhi", "dilep_dR", "lep_ID", "dipair_dEta_H", "dipair_dPhi_H", "cts_dipair_H", "cs_costheta", "met_pt", "mht_pt", "mht_Rtrans_4lPt", "mht_Rlongi_4lPt" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;
      fVmin[18] = 0;
      fVmax[18] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'I';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTG_UF_v1() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[19];
   double fVmax[19];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[19];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTG_UF_v1Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTG_UF_v1::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTG_UF_v1Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTG_UF_v1Node*)current->GetRight();
         else current=(BDTG_UF_v1Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDTG_UF_v1::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.117685,-0.0422846) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00332247,-0.071037) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0498189,-0.0757592) , 
0, 110.61, 1, 0, 0.0229168,-0.477083) , 
8, 1.71455, 1, 0, 0.0533103,-0.44669) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.32484,-0.00341283) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.864267,0.0186629) , 
0, 120.844, 1, 0, 0.787574,0.287574) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.299195,-0.0100801) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0122677,-0.0212116) , 
0, 134.128, 1, 0, 0.103702,-0.396298) , 
0, 128.384, 1, 0, 0.624295,0.124295) , 
0, 116.535, 1, 0, 0.49507,-0.00492964)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0142794,-0.0512372) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.049452,-0.0562619) , 
17, 0.318182, 1, 0, 0.0345354,-0.434076) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.125648,-0.0401226) , 
0, 112.09, 1, 0, 0.0639278,-0.404461) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.348533,-0.0133957) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.868024,0.0184701) , 
0, 120.847, 1, 0, 0.80303,0.295081) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333333,-0.0082315) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0086174,-0.0681163) , 
0, 134.137, 1, 0, 0.117411,-0.373847) , 
0, 128.388, 1, 0, 0.637399,0.133483) , 
0, 116.538, 1, 0, 0.503778,0.00813975)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0444669,-0.0404014) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00459359,-0.0914442) , 
9, 2.29816, 1, 0, 0.0209015,-0.421054) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0529343,-0.0417796) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.158803,-0.0366354) , 
0, 114.172, 1, 0, 0.0978148,-0.353552) , 
0, 110.219, 1, 0, 0.0591858,-0.387455) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.337646,-0.0140576) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.860388,0.0188759) , 
0, 120.629, 1, 0, 0.809843,0.294807) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.198566,-0.00692421) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0117299,-0.0162445) , 
0, 134.684, 1, 0, 0.0737682,-0.392691) , 
0, 129.062, 1, 0, 0.635213,0.131702) , 
0, 117.466, 1, 0, 0.493564,0.00403714)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0233383,-0.011233) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0541381,-0.0611522) , 
17, 0.318182, 1, 0, 0.0414362,-0.371029) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.156375,-0.0363244) , 
0, 113.326, 1, 0, 0.0731532,-0.347389) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.46029,-0.00127584) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.864848,0.0164641) , 
0, 121.859, 1, 0, 0.798686,0.276441) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.232064,-0.0118268) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00745734,-0.0147148) , 
0, 134.805, 1, 0, 0.0728707,-0.385393) , 
0, 129.205, 1, 0, 0.635476,0.127618) , 
0, 117.658, 1, 0, 0.500643,0.0137217)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0476544,-0.0327995) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.194689,-0.0280479) , 
0, 114.785, 1, 0, 0.0797028,-0.324776) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47422,-0.000853886) , 
0, 118.016, 1, 0, 0.181261,-0.248113) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.827796,0.0134115) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.929384,0.0204597) , 
1, 78.8732, 1, 0, 0.874729,0.339133) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.262544,-0.0221227) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00699922,-0.0183432) , 
0, 134.539, 1, 0, 0.0859346,-0.367326) , 
0, 128.883, 1, 0, 0.672302,0.157836) , 
0, 121.969, 1, 0, 0.502436,0.0174059)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0165112,-0.077154) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0406811,-0.051795) , 
17, 0.318182, 1, 0, 0.0303201,-0.345293) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.124311,-0.0402252) , 
0, 112.091, 1, 0, 0.0594013,-0.322371) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.444395,-0.00368588) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.880605,0.0173625) , 
0, 121.918, 1, 0, 0.798581,0.264259) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.31732,-0.00813967) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0114993,-0.01819) , 
0, 134.125, 1, 0, 0.114536,-0.333378) , 
0, 128.38, 1, 0, 0.634162,0.120609) , 
0, 116.534, 1, 0, 0.502597,0.0192095)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0229489,-0.00513257) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0404672,-0.0484733) , 
17, 0.318182, 1, 0, 0.032924,-0.317018) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.15747,-0.0299331) , 
0, 113.329, 1, 0, 0.068134,-0.29464) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.376786,-0.00267805) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.856112,0.0153585) , 
0, 120.813, 1, 0, 0.80588,0.263447) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.167268,-0.0358186) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00495814,-0.0121591) , 
0, 137.605, 1, 0, 0.0681648,-0.365617) , 
0, 129.208, 1, 0, 0.642793,0.12438) , 
0, 117.658, 1, 0, 0.503583,0.022873)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0288223,-0.0501359) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0411086,-0.0545967) , 
17, 0.318182, 1, 0, 0.035731,-0.301314) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.163407,-0.0295226) , 
0, 113.329, 1, 0, 0.0713034,-0.277815) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333446,-0.00234833) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.855873,0.0150474) , 
0, 120.81, 1, 0, 0.798769,0.2498) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.223349,-0.010958) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0143404,-0.0544687) , 
0, 134.805, 1, 0, 0.0788217,-0.345459) , 
0, 129.205, 1, 0, 0.641542,0.119804) , 
0, 117.658, 1, 0, 0.503666,0.0236652)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.148003,-0.0104092) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0309995,-0.0510435) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0508473,-0.0512385) , 
17, 0.681818, 1, 0, 0.040784,-0.280767) , 
9, 1.91992, 1, 0, 0.0696627,-0.25741) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.384645,-0.00727358) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.863606,0.0166581) , 
0, 120.629, 1, 0, 0.814577,0.25911) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.190741,-0.0284077) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.000943814,-0.0119769) , 
0, 137.49, 1, 0, 0.0757792,-0.328925) , 
0, 129.059, 1, 0, 0.648682,0.127068) , 
0, 117.464, 1, 0, 0.506385,0.0325811)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.128519,-0.0279697) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0298456,-0.0270128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0355942,-0.0450522) , 
17, 0.318182, 1, 0, 0.0334431,-0.269511) , 
4, 2.31691, 1, 0, 0.0654361,-0.244867) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.422645,-0.00141052) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.870026,0.0164389) , 
0, 121.684, 1, 0, 0.799022,0.237711) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.239105,-0.0133751) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0102915,-0.0161806) , 
0, 134.687, 1, 0, 0.078273,-0.317597) , 
0, 129.064, 1, 0, 0.633405,0.11011) , 
0, 117.468, 1, 0, 0.494644,0.0233847)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.151718,-0.020448) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0630783,-0.0303907) , 
8, 1.42803, 1, 0, 0.0839577,-0.226656) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.839911,0.0141895) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.361447,-0.00681882) , 
0, 128.283, 1, 0, 0.79337,0.229359) , 
0, 119.1, 1, 0, 0.572476,0.0873669) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0306642,-0.0511487) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.0540957) , 
0, 143.152, 1, 0, 0.0139836,-0.362163) , 
0, 133.531, 1, 0, 0.501505,0.0302428)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0629074,-0.0447359) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.152308,-0.0112276) , 
17, 1.04545, 1, 0, 0.0859293,-0.212939) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.831298,0.012113) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.382423,-0.00610137) , 
0, 128.279, 1, 0, 0.786869,0.217517) , 
0, 119.097, 1, 0, 0.568652,0.0835071) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0270004,-0.0532838) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.0476911) , 
0, 143.144, 1, 0, 0.012134,-0.339431) , 
0, 133.525, 1, 0, 0.497767,0.0296365)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00863185,-0.0598433) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0261165,-0.0242523) , 
17, 0.318182, 1, 0, 0.0187095,-0.234859) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.163912,-0.019717) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0518032,-0.04876) , 
8, 2.28476, 1, 0, 0.114292,-0.178152) , 
0, 110.569, 1, 0, 0.0640365,-0.207967) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469913,-0.00277697) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.863762,0.0141892) , 
0, 121.952, 1, 0, 0.80086,0.221073) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.160228,-0.0280665) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00398271,-0.0319929) , 
0, 137.652, 1, 0, 0.0649485,-0.28447) , 
0, 129.279, 1, 0, 0.633172,0.105878) , 
0, 117.765, 1, 0, 0.487268,0.0254202)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.251876,-0.00902942) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0884838,-0.0114557) , 
9, 1.88706, 1, 0, 0.130344,-0.172174) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.922087,0.0152057) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.807261,0.0121895) , 
8, 1.71368, 1, 0, 0.863892,0.262554) , 
0, 121.023, 1, 0, 0.574928,0.0913035) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.279983,-0.0103632) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0278277,-0.0189915) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0014138,-0.0493501) , 
0, 143.455, 1, 0, 0.0136318,-0.301166) , 
0, 134.01, 1, 0, 0.105011,-0.251442) , 
0, 128.238, 1, 0, 0.488355,0.0281595)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.31045,-0.00189025) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.087585,-0.0232635) , 
8, 1.14333, 1, 0, 0.13098,-0.165247) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.875212,0.0142386) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.514566,0.000904097) , 
0, 127.437, 1, 0, 0.82273,0.23089) , 
0, 120.975, 1, 0, 0.574243,0.088591) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00278518,-0.0319009) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0346688,-0.0167628) , 
6, 64.0746, 1, 0, 0.0166637,-0.287802) , 
0, 132.828, 1, 0, 0.500156,0.0385785)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.332463,-0.000507874) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.100236,-0.00925497) , 
8, 1.14241, 1, 0, 0.143679,-0.150614) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.874325,0.0149226) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.503588,0.000581943) , 
0, 127.44, 1, 0, 0.820206,0.223298) , 
0, 120.978, 1, 0, 0.569466,0.0847156) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00175226,-0.0484955) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0284975,-0.0171777) , 
2, 1.22295, 1, 0, 0.0183738,-0.275926) , 
0, 132.825, 1, 0, 0.495785,0.0364981)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0162439,-0.0547892) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0287117,-0.0223597) , 
17, 0.318182, 1, 0, 0.023544,-0.201214) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.185978,-0.0126065) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.057369,-0.0412145) , 
8, 1.99921, 1, 0, 0.112823,-0.145593) , 
0, 110.219, 1, 0, 0.0681293,-0.173437) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.308205,-0.0034836) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.854177,0.0138758) , 
0, 120.63, 1, 0, 0.798659,0.199431) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.21718,-0.00927443) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00785386,-0.0459031) , 
0, 134.687, 1, 0, 0.0732376,-0.236626) , 
0, 129.064, 1, 0, 0.637833,0.102757) , 
0, 117.468, 1, 0, 0.496392,0.0341861)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0193638,-0.00784761) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0518239,-0.0218899) , 
17, 0.318182, 1, 0, 0.0385564,-0.179936) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.147935,-0.0183701) , 
0, 113.113, 1, 0, 0.0703434,-0.160635) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440946,-0.00135916) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.868209,0.0140713) , 
0, 121.678, 1, 0, 0.801961,0.197339) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.193204,-0.00875884) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0372838,-0.0300598) , 
8, 1.71508, 1, 0, 0.0919485,-0.206969) , 
0, 129.056, 1, 0, 0.637844,0.103884) , 
0, 117.463, 1, 0, 0.500125,0.0396916)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0257969,-0.0134529) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0390383,-0.0243245) , 
17, 0.318182, 1, 0, 0.0334522,-0.179712) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.151461,-0.0180861) , 
0, 113.329, 1, 0, 0.0674234,-0.159189) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461246,-0.00111126) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.871807,0.0141157) , 
0, 121.863, 1, 0, 0.804262,0.194387) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.150062,-0.0189347) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0259853,-0.0273735) , 
8, 1.71354, 1, 0, 0.0688354,-0.215545) , 
0, 129.208, 1, 0, 0.636924,0.101112) , 
0, 117.658, 1, 0, 0.491457,0.0346235)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0435722,-0.0135092) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.1736,-0.0155964) , 
0, 114.784, 1, 0, 0.0706674,-0.154705) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.510087,0.000283294) , 
0, 118.018, 1, 0, 0.189911,-0.111699) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.924716,0.0159218) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.81295,0.010859) , 
9, 2.28941, 1, 0, 0.876584,0.235746) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0396983,-0.0324687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.17594,-0.0134527) , 
6, 81.5036, 1, 0, 0.0851507,-0.19876) , 
0, 128.88, 1, 0, 0.665625,0.119927) , 
0, 121.967, 1, 0, 0.500627,0.0395893)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.250393,-0.00256535) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.100589,-0.0226626) , 
4, 2.1182, 1, 0, 0.139975,-0.122975) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.817208,0.00806059) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.935798,0.0163037) , 
1, 89.9952, 1, 0, 0.864493,0.218921) , 
0, 121.021, 1, 0, 0.585815,0.0874146) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.336769,-0.00679004) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0300731,-0.0390046) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.00656223) , 
17, 0.681818, 1, 0, 0.0156848,-0.218668) , 
0, 134.01, 1, 0, 0.120106,-0.173657) , 
0, 128.238, 1, 0, 0.495215,0.0366252)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.413755,0.00215471) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.166118,-0.0163755) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0821082,-0.00195577) , 
5, 93.7173, 1, 0, 0.151277,-0.132334) , 
9, 1.48846, 1, 0, 0.192174,-0.104388) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.927292,0.0154302) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.825169,0.0110286) , 
8, 1.7136, 1, 0, 0.875189,0.222894) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.272245,-0.00814159) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00778218,-0.0299084) , 
0, 134.536, 1, 0, 0.0947733,-0.172491) , 
0, 128.88, 1, 0, 0.666891,0.117364) , 
0, 121.967, 1, 0, 0.500323,0.0395558)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.158981,-0.0117077) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0428908,-0.0158793) , 
9, 1.84748, 1, 0, 0.070296,-0.138193) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.514434,0.00150995) , 
0, 118.014, 1, 0, 0.187197,-0.0962925) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.831816,0.0100865) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943972,0.0159824) , 
6, 82.798, 1, 0, 0.881952,0.223581) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.187047,-0.00459106) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0369861,-0.0382182) , 
4, 2.42138, 1, 0, 0.084091,-0.173451) , 
0, 128.875, 1, 0, 0.673295,0.119749) , 
0, 121.964, 1, 0, 0.511391,0.047792)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417643,0.00448275) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.185108,-0.00553336) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0984469,-0.0121408) , 
10, 12, 1, 0, 0.12597,-0.0131062) , 
8, 1.14254, 1, 0, 0.184462,-0.100306) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.917481,0.0132139) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.807244,0.00943917) , 
8, 1.99922, 1, 0, 0.873396,0.209508) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.216981,-0.0111582) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00219825,-0.009783) , 
0, 137.355, 1, 0, 0.0863862,-0.156873) , 
0, 128.874, 1, 0, 0.654611,0.107656) , 
0, 121.964, 1, 0, 0.490271,0.0349632)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0270996,-0.0162932) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0373034,-0.0360478) , 
17, 0.318182, 1, 0, 0.0328291,-0.154267) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520243,0.00723686) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.253833,-0.0042989) , 
8, 1.71361, 1, 0, 0.359913,-0.0290007) , 
0, 114.066, 1, 0, 0.177464,-0.0988748) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.930852,0.0153026) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.840014,0.0108407) , 
10, 12, 1, 0, 0.878314,0.0528546) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.269153,-0.00564934) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00783577,-0.0303545) , 
0, 134.532, 1, 0, 0.0907353,-0.153195) , 
0, 128.874, 1, 0, 0.672045,0.114231) , 
0, 121.964, 1, 0, 0.501316,0.0406669)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.028112,-0.0177665) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0486583,-0.0300834) , 
17, 0.318182, 1, 0, 0.0399148,-0.138131) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.139084,-0.014287) , 
0, 113.119, 1, 0, 0.0682005,-0.122413) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574043,0.00269261) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.87799,0.0119431) , 
0, 122.738, 1, 0, 0.806072,0.164763) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.196514,-0.0112476) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00405034,-0.0444484) , 
0, 137.499, 1, 0, 0.0812831,-0.147879) , 
0, 129.065, 1, 0, 0.643577,0.0946701) , 
0, 117.468, 1, 0, 0.497154,0.0394262)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0189542,-0.0173892) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0387895,-0.0195416) , 
17, 0.318182, 1, 0, 0.0302093,-0.141998) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.184415,-0.00716525) , 
0, 113.326, 1, 0, 0.0760892,-0.11167) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396456,-0.00326656) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.852317,0.00956445) , 
0, 120.809, 1, 0, 0.80565,0.158486) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0202319,-0.0298657) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.145416,-0.00799393) , 
1, 75.5285, 1, 0, 0.0694887,-0.148669) , 
0, 129.204, 1, 0, 0.643461,0.0908144) , 
0, 117.657, 1, 0, 0.501275,0.0400712)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0173915,-0.0379168) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0440292,-0.032811) , 
17, 0.318182, 1, 0, 0.0321093,-0.13525) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.158045,-0.0104958) , 
0, 113.448, 1, 0, 0.0678387,-0.11578) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501694,0.000422934) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.874106,0.012104) , 
0, 121.957, 1, 0, 0.814869,0.163953) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0157312,-0.0240174) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0962137,-0.021064) , 
13, -0.272751, 1, 0, 0.0653618,-0.146038) , 
0, 129.285, 1, 0, 0.648732,0.0952401) , 
0, 117.767, 1, 0, 0.50323,0.0423839)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501467,0.00440224) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0669703,-0.0185375) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.551825,-0.000507076) , 
0, 119.519, 1, 0, 0.192194,-0.0977058) , 
9, 1.48846, 1, 0, 0.243093,-0.0653954) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.936357,0.0149099) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.826007,0.00966445) , 
8, 1.42805, 1, 0, 0.867573,0.185555) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.155113,-0.00548056) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0266586,-0.023994) , 
8, 1.7138, 1, 0, 0.0720852,-0.130432) , 
0, 129.545, 1, 0, 0.649201,0.0988125) , 
0, 122.781, 1, 0, 0.485397,0.0325791)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.442671,0.0065871) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.191269,-0.00844084) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.121403,-0.00791161) , 
10, 12, 1, 0, 0.141985,-0.0106967) , 
9, 1.45571, 1, 0, 0.186247,-0.0741757) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.913332,0.0133043) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.819517,0.00664645) , 
4, 2.56353, 1, 0, 0.868294,0.17482) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.281457,-0.00307943) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00856068,-0.0126731) , 
0, 134.54, 1, 0, 0.0917345,-0.115774) , 
0, 128.885, 1, 0, 0.661192,0.0973209) , 
0, 121.969, 1, 0, 0.492714,0.0364854)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.102714,-0.0222301) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270762,-0.000411845) , 
6, 88.0176, 1, 0, 0.151384,-0.0752957) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.925352,0.0136971) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.821529,0.00884544) , 
8, 1.71368, 1, 0, 0.872818,0.179047) , 
0, 121.12, 1, 0, 0.5869,0.0782462) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.216387,-0.00472503) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0415354,-0.00654004) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0829984,-0.0280675) , 
13, -0.0907572, 1, 0, 0.0635813,-0.152954) , 
8, 1.71412, 1, 0, 0.116441,-0.117994) , 
0, 128.319, 1, 0, 0.498082,0.041198)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.103996,-0.00351338) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.536124,0.0084961) , 
0, 114.533, 1, 0, 0.322518,0.0161857) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0581995,-0.0410196) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.126407,-0.0149056) , 
13, -0.454554, 1, 0, 0.106551,-0.113893) , 
8, 1.71432, 1, 0, 0.181516,-0.0687412) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.921036,0.0134374) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.817419,0.00836597) , 
8, 1.99954, 1, 0, 0.87896,0.176802) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266135,-0.00491261) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00823614,-0.0405194) , 
0, 134.537, 1, 0, 0.0909299,-0.113245) , 
0, 128.882, 1, 0, 0.671007,0.100262) , 
0, 121.969, 1, 0, 0.503366,0.0423814)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405073,0.00513079) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.111828,-0.00957122) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.196021,-0.00313863) , 
16, 56.4374, 1, 0, 0.129275,-0.0960192) , 
9, 1.51896, 1, 0, 0.170224,-0.0715788) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.938304,0.0153167) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.806495,0.00921321) , 
9, 1.59484, 1, 0, 0.842716,0.163291) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0397698,-0.0314817) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00964069,-0.0096797) , 
17, 0.318182, 1, 0, 0.0222635,-0.132529) , 
0, 132.334, 1, 0, 0.671266,0.101474) , 
0, 121.965, 1, 0, 0.498631,0.0418482)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44736,0.00778797) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.108744,-0.0248523) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.219479,-0.00222397) , 
16, 52.7075, 1, 0, 0.135792,-0.089506) , 
9, 1.4954, 1, 0, 0.182131,-0.0627124) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.909075,0.0126894) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.790833,0.00528653) , 
8, 2.28405, 1, 0, 0.873361,0.162584) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0462401,-0.0334572) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.199511,-0.00383244) , 
1, 86.4341, 1, 0, 0.0939044,-0.0986559) , 
0, 128.883, 1, 0, 0.664325,0.0925246) , 
0, 121.969, 1, 0, 0.496505,0.0384969)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.127552,-0.00925251) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0370797,-0.0247977) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0362402,-0.0154875) , 
8, 2.2848, 1, 0, 0.0365706,-0.098193) , 
4, 2.31691, 1, 0, 0.0667911,-0.0815203) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.875684,0.0127471) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.713281,0.0064646) , 
9, 1.88088, 1, 0, 0.774733,0.133331) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0265025,-0.0347195) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00451257,-0.0143768) , 
17, 0.681818, 1, 0, 0.0163974,-0.130588) , 
0, 132.338, 1, 0, 0.64278,0.0874083) , 
0, 116.538, 1, 0, 0.509668,0.0483686)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385168,0.00452114) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.192672,-0.00219761) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.105668,-0.0191934) , 
10, 12, 1, 0, 0.135979,-0.00883003) , 
8, 1.14259, 1, 0, 0.184851,-0.0551369) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.924479,0.013002) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.843273,0.00866962) , 
10, 12, 1, 0, 0.877606,0.0350608) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0298454,-0.0114637) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.207571,-0.000362936) , 
1, 86.0401, 1, 0, 0.0901244,-0.0931335) , 
0, 128.88, 1, 0, 0.663733,0.0901675) , 
0, 121.967, 1, 0, 0.499203,0.0402449)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385747,0.00423944) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.150789,-0.00847865) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0649843,-0.00253846) , 
5, 93.7183, 1, 0, 0.134225,-0.0811075) , 
8, 1.14243, 1, 0, 0.181666,-0.05651) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.899487,0.011716) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.790432,0.00301818) , 
4, 2.96019, 1, 0, 0.871851,0.148483) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0355743,-0.0157999) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.201069,-0.00218203) , 
1, 86.368, 1, 0, 0.0858766,-0.0927414) , 
0, 128.874, 1, 0, 0.671713,0.0870583) , 
0, 121.963, 1, 0, 0.500723,0.0369636)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.350107,0.00280716) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.18129,-0.00555725) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0923781,-0.00721095) , 
10, 12, 1, 0, 0.119226,-0.00748794) , 
9, 1.87018, 1, 0, 0.184899,-0.0490526) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.922852,0.0125134) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.815333,0.00622309) , 
8, 1.99917, 1, 0, 0.878753,0.151463) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0422359,-0.0366825) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.209259,-0.00109912) , 
6, 81.8672, 1, 0, 0.0958568,-0.0821816) , 
0, 128.873, 1, 0, 0.675904,0.0909252) , 
0, 121.963, 1, 0, 0.5086,0.0432293)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0164856,-0.0463073) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0986283,-0.0106523) , 
0, 110.22, 1, 0, 0.0576754,-0.0938964) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0499568,-0.0185154) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.144405,-0.00286201) , 
0, 110.338, 1, 0, 0.095149,-0.0435114) , 
17, 0.681818, 1, 0, 0.0759189,-0.0693673) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.337292,-0.00138519) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.866539,0.0102685) , 
0, 120.63, 1, 0, 0.812419,0.128954) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.168823,-0.00281986) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0339128,-0.0179905) , 
8, 1.71366, 1, 0, 0.0817998,-0.0806049) , 
0, 129.064, 1, 0, 0.647563,0.0816696) , 
0, 117.468, 1, 0, 0.505456,0.0441228)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0486613,-0.021998) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.174916,-0.0014784) , 
0, 113.119, 1, 0, 0.0849133,-0.0581087) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0223526,-0.0265414) , 
13, 0.636125, 1, 0, 0.0708444,-0.0691044) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.881876,0.0119307) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.747481,0.00532591) , 
9, 2.0442, 1, 0, 0.806314,0.120385) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.194105,-0.00520654) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00602876,-0.0145703) , 
0, 137.498, 1, 0, 0.0811606,-0.0778057) , 
0, 129.064, 1, 0, 0.641138,0.0752406) , 
0, 117.468, 1, 0, 0.500853,0.0397335)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.255738,-0.000292588) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0856786,-0.0222506) , 
8, 1.71361, 1, 0, 0.141863,-0.0537902) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661539,-0.00103561) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.838756,0.00919796) , 
5, 86.4602, 1, 0, 0.817334,0.118638) , 
0, 120.973, 1, 0, 0.575669,0.0569476) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0217551,-0.0351786) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00823369,-0.00599802) , 
17, 0.318182, 1, 0, 0.0138267,-0.107905) , 
0, 132.823, 1, 0, 0.499421,0.0345755)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418682,0.00338003) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.114519,-0.0172692) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.216585,-0.00130086) , 
16, 56.3777, 1, 0, 0.136681,-0.0667804) , 
9, 1.49616, 1, 0, 0.180792,-0.0466681) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.931264,0.0127098) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.844111,0.00692838) , 
10, 12, 1, 0, 0.880323,0.0287415) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.168211,-0.00344146) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0312819,-0.0138643) , 
8, 1.7139, 1, 0, 0.0809105,-0.0809927) , 
0, 128.879, 1, 0, 0.668145,0.0805908) , 
0, 121.965, 1, 0, 0.501122,0.0369774)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0251438,-0.0114319) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0498655,-0.0198606) , 
17, 0.318182, 1, 0, 0.0390453,-0.0767569) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191277,0.00158951) , 
0, 113.444, 1, 0, 0.0819979,-0.0526274) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.864341,0.00943696) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.708854,0.00230588) , 
8, 1.99886, 1, 0, 0.800156,0.105488) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0142413,-0.0326606) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.10277,-0.00938942) , 
13, -0.272579, 1, 0, 0.0699303,-0.0796288) , 
0, 129.277, 1, 0, 0.644123,0.0659332) , 
0, 117.764, 1, 0, 0.500692,0.0356813)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0458254,-0.00590122) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0325072,-0.0238217) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.13424,-0.000122391) , 
0, 110.609, 1, 0, 0.076986,-0.0396448) , 
17, 0.318182, 1, 0, 0.0640091,-0.059308) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.655465,-0.000502623) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.813584,0.00899437) , 
14, -0.636352, 1, 0, 0.788743,0.10217) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0604681,-0.0132695) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.244122,0.000698284) , 
1, 86.0401, 1, 0, 0.119772,-0.0653814) , 
0, 128.387, 1, 0, 0.627258,0.0617245) , 
0, 116.537, 1, 0, 0.499362,0.0342418)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0134474,-0.00429931) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0372808,-0.0129549) , 
17, 0.318182, 1, 0, 0.0275678,-0.0771285) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0801613,-0.0176737) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.150545,-0.0010802) , 
13, -0.0906965, 1, 0, 0.119218,-0.0341178) , 
0, 110.442, 1, 0, 0.0728997,-0.0558546) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.627096,-0.00280578) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.82752,0.00833859) , 
5, 86.4499, 1, 0, 0.80512,0.103325) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0111739,-0.0180106) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0916469,-0.0143315) , 
13, -0.272664, 1, 0, 0.0624015,-0.0789782) , 
0, 129.2, 1, 0, 0.642974,0.0635253) , 
0, 117.657, 1, 0, 0.498654,0.0333031)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.049196,-0.0147425) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0489349,-0.00432572) , 
17, -0.178072, 1, 0, 0.0490664,-0.0853777) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.131409,-0.00215815) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0428282,-0.0261228) , 
3, 2.28481, 1, 0, 0.0793561,-0.0407497) , 
17, 0.318182, 1, 0, 0.0667146,-0.0593752) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.884817,0.0101701) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.756037,0.00375204) , 
10, 12, 1, 0, 0.807935,-0.00137088) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.168585,-0.00312812) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00421544,-0.0380961) , 
0, 137.651, 1, 0, 0.0708511,-0.0668681) , 
0, 129.276, 1, 0, 0.64686,0.0674359) , 
0, 117.764, 1, 0, 0.502492,0.0358793)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.162817,-0.00143089) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.711914,0.00682142) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.851748,0.0139603) , 
1, 134.375, 1, 0, 0.773139,0.13465) , 
0, 117.464, 1, 0, 0.657367,0.106371) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0705657,-0.0139467) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.72964,0.00923933) , 
0, 116.534, 1, 0, 0.56443,0.0765659) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.178033,-0.0262618) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.395848,-0.00104383) , 
5, 86.4566, 1, 0, 0.358266,-0.0323752) , 
10, 12, 1, 0, 0.424939,-0.0125709) , 
9, 1.86741, 1, 0, 0.500592,0.0365491)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.293635,0.00128695) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0859256,-0.00428544) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.14146,-0.0110646) , 
13, -0.454449, 1, 0, 0.122849,-0.0728117) , 
4, 2.11201, 1, 0, 0.166462,-0.0518207) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.910825,0.00975575) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.802905,0.00495333) , 
8, 2.28479, 1, 0, 0.878208,0.121277) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0129256,-0.00762276) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.103805,-0.010873) , 
13, -0.454585, 1, 0, 0.0758485,-0.070394) , 
0, 128.885, 1, 0, 0.661026,0.0693961) , 
0, 121.967, 1, 0, 0.492203,0.0280178)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.103914,-0.0126216) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.200924,-0.000768293) , 
2, 2.3744, 1, 0, 0.128257,-0.0615844) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.347435,0.00226979) , 
1, 96.8161, 1, 0, 0.182119,-0.0371405) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.890677,0.00878931) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.485619,0.000115805) , 
0, 127.614, 1, 0, 0.838809,0.11164) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.031126,-0.0269333) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00846305,-0.0388236) , 
17, 0.318182, 1, 0, 0.0187186,-0.0842576) , 
0, 132.33, 1, 0, 0.673869,0.0722407) , 
0, 121.964, 1, 0, 0.502774,0.0341836)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0535282,-0.0194867) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.839227,0.0120917) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505024,0.00585543) , 
0, 126.419, 1, 0, 0.752412,0.135843) , 
0, 113.847, 1, 0, 0.636489,0.103835) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.69489,0.00973248) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.400519,-0.00108993) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.176496,-0.00952506) , 
5, 95.5425, 1, 0, 0.375475,-0.025502) , 
9, 1.56977, 1, 0, 0.434266,0.00150649) , 
10, 12, 1, 0, 0.507009,-0.0103715)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.370342,-0.00240752) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.488224,0.00576501) , 
17, 0.318182, 1, 0, 0.439698,0.0398582) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.263408,0.000411241) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.139149,-0.00672) , 
10, 12, 1, 0, 0.175642,-0.0115994) , 
9, 1.92058, 1, 0, 0.259179,-0.0296333) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.932581,0.0126297) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.836419,0.00714678) , 
10, 12, 1, 0, 0.87564,0.0564476) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00873435,-0.0304696) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0791327,-0.0075576) , 
13, -0.0908857, 1, 0, 0.0495171,-0.0694828) , 
0, 129.677, 1, 0, 0.648109,0.07105) , 
0, 122.944, 1, 0, 0.490904,0.0303539)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0106753,-0.0454885) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.100204,-0.0130949) , 
0, 110.22, 1, 0, 0.0554147,-0.0687339) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.127063,-0.00196275) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0460479,-0.018434) , 
3, 2.28484, 1, 0, 0.0784767,-0.0309342) , 
17, 0.318182, 1, 0, 0.068781,-0.0468258) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.718932,0.00214786) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.867187,0.00992814) , 
1, 63.8576, 1, 0, 0.806262,0.0905662) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00488445,-0.00710589) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.104458,-0.00478835) , 
13, -0.454365, 1, 0, 0.0759916,-0.0525647) , 
0, 129.065, 1, 0, 0.633889,0.0567816) , 
0, 117.468, 1, 0, 0.49388,0.0311123)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00606898,-0.0476664) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0331556,-0.00802031) , 
17, 0.318182, 1, 0, 0.02235,-0.069067) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.104041,-0.0121517) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.142092,0.00306209) , 
2, 1.68349, 1, 0, 0.120104,-0.0215826) , 
0, 110.442, 1, 0, 0.0699013,-0.0459687) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.361888,-0.00112414) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.861204,0.00815156) , 
0, 120.809, 1, 0, 0.806692,0.0910382) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0152171,-0.0300411) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0874118,-0.0110532) , 
13, -0.272508, 1, 0, 0.0609324,-0.06032) , 
0, 129.205, 1, 0, 0.647904,0.0588108) , 
0, 117.658, 1, 0, 0.502266,0.0324098)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0840342,-0.0116019) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0430215,-0.0174408) , 
10, 12, 1, 0, 0.0550447,-0.0126555) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.793776,0.00459312) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.285928,-0.00471909) , 
0, 126.238, 1, 0, 0.585539,0.0287341) , 
0, 118.737, 1, 0, 0.43191,0.00311072) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.760144,0.0122713) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510583,0.00184693) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.542737,0.00534387) , 
12, 0.285577, 1, 0, 0.527163,0.034551) , 
9, 1.58959, 1, 0, 0.66665,0.100305) , 
1, 100.329, 1, 0, 0.497231,0.0301567)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0608249,-0.00558263) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.517311,0.00920388) , 
0, 112.667, 1, 0, 0.298387,0.0245406) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.198375,-0.00133485) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.101221,-0.00465613) , 
10, 12, 1, 0, 0.130985,-0.00404456) , 
4, 2.23612, 1, 0, 0.182998,-0.0319547) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.766726,0.00326445) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.896015,0.0102798) , 
1, 78.3792, 1, 0, 0.829025,0.0921391) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0193442,-0.00734548) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00464423,-0.0214702) , 
17, 0.681818, 1, 0, 0.012546,-0.0761912) , 
0, 132.33, 1, 0, 0.658988,0.0570833) , 
0, 121.963, 1, 0, 0.493994,0.0262198)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0450653,-0.0170031) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0589379,-0.0146814) , 
17, 0.351004, 1, 0, 0.0507615,-0.0589108) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.121223,2.17728e-05) , 
17, 1.04545, 1, 0, 0.0683821,-0.0441396) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.376937,-0.00373942) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.858513,0.00717531) , 
0, 121.03, 1, 0, 0.81104,0.0829818) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0220631,-0.036553) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.145103,-0.000892514) , 
6, 81.6803, 1, 0, 0.0614679,-0.0534697) , 
0, 129.378, 1, 0, 0.64487,0.0527325) , 
0, 117.9, 1, 0, 0.496875,0.0278635)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.150987,-0.00176935) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.714752,0.00488747) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.857272,0.0132161) , 
1, 127.483, 1, 0, 0.782558,0.116093) , 
0, 117.76, 1, 0, 0.660666,0.0908473) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0771448,-0.0166072) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.747291,0.00876954) , 
0, 119.963, 1, 0, 0.560469,0.0633411) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.370394,-0.00157331) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.145478,-0.00462882) , 
5, 95.5446, 1, 0, 0.342235,-0.0322124) , 
10, 12, 1, 0, 0.412231,-0.0203433) , 
9, 1.88772, 1, 0, 0.490514,0.0275547)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.137787,-0.00587551) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.633113,0.00364024) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.827011,0.0104299) , 
1, 88.5515, 1, 0, 0.781487,0.113919) , 
0, 117.464, 1, 0, 0.665922,0.0885278) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.104995,-0.00691274) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.760476,0.00886009) , 
0, 119.995, 1, 0, 0.567598,0.0676444) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.383085,-0.00156736) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.121539,-0.00503952) , 
5, 95.5432, 1, 0, 0.350716,-0.0329884) , 
10, 12, 1, 0, 0.420261,-0.0149621) , 
9, 1.89776, 1, 0, 0.502511,0.0291615)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0966313,-0.00309763) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.838889,0.00864584) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0218834,-0.0103258) , 
0, 132.924, 1, 0, 0.726112,0.0864065) , 
0, 117.465, 1, 0, 0.606052,0.0620215) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0662993,-0.0183655) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.720481,0.00775649) , 
0, 119.963, 1, 0, 0.504351,0.0425068) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.130991,-0.00886827) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344724,-0.00201721) , 
5, 86.4535, 1, 0, 0.306838,-0.0435922) , 
10, 12, 1, 0, 0.369789,-0.011714) , 
8, 1.99917, 1, 0, 0.493193,0.0246798)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.148457,-0.0011352) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.877241,0.0122454) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.723047,0.00655021) , 
4, 1.86184, 1, 0, 0.792205,0.113586) , 
0, 117.462, 1, 0, 0.673978,0.0903421) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.110659,-0.00343611) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.734623,0.00695003) , 
0, 119.997, 1, 0, 0.556165,0.0616927) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.160267,-0.0112678) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.383277,-0.000994727) , 
5, 84.6384, 1, 0, 0.358529,-0.0252722) , 
10, 12, 1, 0, 0.42318,-0.0126671) , 
9, 1.88099, 1, 0, 0.505074,0.0316385)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0881584,-0.0127818) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.254044,0.00126166) , 
6, 78.0622, 1, 0, 0.144264,-0.0259552) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.818656,0.00418427) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.919421,0.0100891) , 
1, 69.5893, 1, 0, 0.872968,0.0944279) , 
0, 121.121, 1, 0, 0.586677,0.0471322) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0471196,-0.00908704) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.344029,0.00478346) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0114265,-0.0173188) , 
0, 136.947, 1, 0, 0.161481,-0.0175585) , 
13, -0.272628, 1, 0, 0.120118,-0.0464675) , 
0, 128.322, 1, 0, 0.499203,0.0295834)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.80893,0.0134477) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.646643,0.00304993) , 
4, 1.67744, 1, 0, 0.728521,0.110319) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0460806,-0.0206342) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.712466,0.00776914) , 
0, 114.996, 1, 0, 0.574777,0.0660054) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.403669,-0.000834344) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.17219,-0.00372405) , 
5, 95.5438, 1, 0, 0.377249,-0.0224063) , 
10, 12, 1, 0, 0.443993,-0.0115635) , 
9, 1.48846, 1, 0, 0.497547,0.0268264)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.341511,0.0037892) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.203671,0.00120117) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.117991,-0.012684) , 
10, 12, 1, 0, 0.143589,-0.00540764) , 
4, 1.97765, 1, 0, 0.185365,-0.0232533) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.893476,0.00828262) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499582,-0.000408577) , 
0, 127.617, 1, 0, 0.841256,0.0873482) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0433677,-0.0160553) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0115938,-0.0147849) , 
14, -0.0909893, 1, 0, 0.0258438,-0.0578191) , 
0, 132.329, 1, 0, 0.67225,0.0572601) , 
0, 121.963, 1, 0, 0.504846,0.0295775)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.130409,-0.00259064) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.657915,0.00461739) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.834595,0.011698) , 
1, 88.5515, 1, 0, 0.792028,0.112307) , 
0, 117.451, 1, 0, 0.668637,0.0860829) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.159929,-0.00286193) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.766742,0.00836613) , 
0, 121.964, 1, 0, 0.561192,0.0546749) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.384827,-0.00141051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.128005,-0.00487724) , 
5, 95.5385, 1, 0, 0.354039,-0.0300872) , 
10, 12, 1, 0, 0.419728,-0.0093119) , 
9, 1.89842, 1, 0, 0.501765,0.0262205)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0776011,-0.00593148) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.79252,0.0107918) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.763989,0.0076981) , 
17, 0.318182, 1, 0, 0.776967,0.101484) , 
0, 116.503, 1, 0, 0.635389,0.0763123) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.147208,-0.012172) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.2907,-0.0101359) , 
5, 83.9824, 1, 0, 0.22011,-0.101817) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.50089,0.00381343) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.220876,-0.0218226) , 
5, 95.7061, 1, 0, 0.467074,0.0159869) , 
5, 86.4593, 1, 0, 0.427368,-0.00295307) , 
10, 12, 1, 0, 0.500608,-0.00963358)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.628142,0.0038895) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.778588,0.0114857) , 
1, 127.673, 1, 0, 0.726502,0.101575) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0989157,-0.00815573) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.776508,0.00808251) , 
0, 119.995, 1, 0, 0.595796,0.0650196) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.169618,-0.00769677) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392432,-0.000651686) , 
5, 84.6366, 1, 0, 0.368297,-0.0233232) , 
10, 12, 1, 0, 0.443502,-0.0122243) , 
9, 1.54204, 1, 0, 0.500571,0.0251778)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.775209,0.00989159) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.630025,0.00376079) , 
8, 0.998052, 1, 0, 0.725669,0.0974381) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0558472,-0.0120134) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.739159,0.00858254) , 
0, 114.996, 1, 0, 0.596625,0.0671453) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.390509,-0.000746295) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.136298,-0.00506363) , 
5, 95.5383, 1, 0, 0.360895,-0.0220167) , 
10, 12, 1, 0, 0.438281,-0.00984427) , 
9, 1.56977, 1, 0, 0.499533,0.0264752)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.781331,0.0117395) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51758,0.00412705) , 
9, 1.64984, 1, 0, 0.703878,0.0974527) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.110329,-0.00856684) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.847803,0.00520881) , 
0, 121.12, 1, 0, 0.550174,0.0253182) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0354861,-0.00465094) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.118765,-0.00358209) , 
2, 1.33771, 1, 0, 0.0849325,-0.0633707) , 
0, 128.319, 1, 0, 0.450535,0.00632396) , 
4, 1.87282, 1, 0, 0.496223,0.0227583)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.79997,0.0122589) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.638881,0.0034855) , 
3, 1.43034, 1, 0, 0.731642,0.101531) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.193803,-0.0032034) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.866098,0.00572283) , 
0, 122.461, 1, 0, 0.53696,0.0277065) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0988695,-0.0296522) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191831,-0.00964312) , 
13, -0.0908857, 1, 0, 0.152333,-0.0676411) , 
0, 127.4, 1, 0, 0.453071,0.00691077) , 
9, 1.46072, 1, 0, 0.504371,0.0243353)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0896345,-0.0076806) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.155816,0.00138609) , 
18, 0.681818, 1, 0, 0.102532,-0.0380901) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.889086,0.00855405) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.759727,0.0012333) , 
8, 2.57036, 1, 0, 0.862893,0.0856984) , 
0, 119.993, 1, 0, 0.594232,0.0419597) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0762242,-0.00767271) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572406,0.00442124) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0144737,-0.0205488) , 
0, 133.326, 1, 0, 0.257627,-0.014749) , 
13, -0.454319, 1, 0, 0.208339,-0.040398) , 
0, 127.4, 1, 0, 0.509732,0.0239255)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.28936,-0.00599605) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0845224,-0.00180166) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.787425,0.00854059) , 
0, 116.488, 1, 0, 0.645577,0.072397) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.240116,-0.00946722) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.477156,0.0018889) , 
5, 86.4534, 1, 0, 0.440193,0.000124108) , 
10, 12, 1, 0, 0.514291,-0.00772959) , 
13, -0.818161, 1, 0, 0.494138,0.0139939)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.206837,-0.00963346) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.290876,-0.00802376) , 
5, 83.9743, 1, 0, 0.251095,-0.0840536) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0770285,-0.00383853) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.647272,0.00389526) , 
0, 119.889, 1, 0, 0.47256,0.0160229) , 
5, 86.4525, 1, 0, 0.438375,0.000575351) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.807105,0.0118575) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.685007,0.0055244) , 
8, 0.934385, 1, 0, 0.753966,0.106755) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436897,-0.000271328) , 
8, 1.71324, 1, 0, 0.688687,0.0843481) , 
1, 100.328, 1, 0, 0.508395,0.0240092)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.147686,-0.00145184) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.863571,0.00871193) , 
0, 118.912, 1, 0, 0.685677,0.0720781) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0300661,-0.0195897) , 
0, 133.406, 1, 0, 0.619524,0.0590234) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.234491,-0.00709878) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.431656,0.00127046) , 
5, 84.9637, 1, 0, 0.407641,-0.00331859) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.184346,-0.00385527) , 
5, 95.5385, 1, 0, 0.383915,-0.0165872) , 
8, 1.99921, 1, 0, 0.506931,0.0228907)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.771999,0.0094999) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.621532,0.00287949) , 
8, 0.981017, 1, 0, 0.722367,0.0845887) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0591406,-0.010237) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.741342,0.00678756) , 
0, 116.517, 1, 0, 0.583534,0.0489938) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.397536,-0.00133814) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.132378,-0.00538586) , 
5, 95.5403, 1, 0, 0.367545,-0.0261346) , 
10, 12, 1, 0, 0.438714,-0.00893197) , 
9, 1.54204, 1, 0, 0.495702,0.015892)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.245107,-0.0034019) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.159082,-0.0209201) , 
5, 93.7216, 1, 0, 0.23003,-0.0342236) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413881,0.0083153) , 
17, 2.13636, 1, 0, 0.258044,-0.0193696) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.911184,0.00885741) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.782968,0.00301175) , 
0, 126.469, 1, 0, 0.881273,0.084604) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0125073,-0.00898871) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0883955,-0.00842343) , 
13, -0.272789, 1, 0, 0.0587852,-0.049047) , 
0, 129.545, 1, 0, 0.657608,0.0482593) , 
0, 122.781, 1, 0, 0.503051,0.0220994)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.081858,-0.000693902) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.824666,0.00849292) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502408,0.00336878) , 
0, 126.371, 1, 0, 0.734926,0.0741824) , 
0, 113.828, 1, 0, 0.623667,0.0612568) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.749528,0.00922758) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.477994,0.00184924) , 
8, 1.14245, 1, 0, 0.616367,0.0569) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.394239,-0.00168819) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.170368,-0.0097365) , 
5, 95.5436, 1, 0, 0.370385,-0.0252083) , 
4, 2.14392, 1, 0, 0.435307,-0.00353744) , 
10, 12, 1, 0, 0.500663,-0.00603521)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.252716,-0.00787796) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476394,0.000287122) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37738,-0.00264127) , 
2, 0.95083, 1, 0, 0.429183,-0.0279559) , 
13, -0.867759, 1, 0, 0.364539,-0.0575648) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0217882,-0.00674176) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.123986,-0.000486013) , 
0, 110.441, 1, 0, 0.0725624,-0.0289778) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.797453,0.0060795) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0188761,-0.0253611) , 
0, 133.042, 1, 0, 0.67077,0.047093) , 
0, 117.654, 1, 0, 0.530383,0.0292406) , 
13, -0.636343, 1, 0, 0.501472,0.0141083)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.14947,-0.00124932) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.716668,0.00471164) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.858366,0.0101857) , 
1, 134.076, 1, 0, 0.775228,0.07042) , 
0, 117.897, 1, 0, 0.649105,0.0544994) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.195375,-0.00645935) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.596057,0.00319629) , 
0, 122.947, 1, 0, 0.423465,0.00159786) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208138,-0.0239099) , 
5, 95.5385, 1, 0, 0.401726,-0.00964443) , 
9, 2.0392, 1, 0, 0.499636,0.0157429)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.2834,-0.00578525) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.809714,0.0114635) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.700685,0.00698983) , 
9, 1.1689, 1, 0, 0.755776,0.097454) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622723,0.00712386) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391404,-0.000960395) , 
10, 12, 1, 0, 0.469665,-0.00777752) , 
9, 1.54204, 1, 0, 0.530062,0.0321637) , 
13, -0.818161, 1, 0, 0.507057,0.021671)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.097922,-0.0211365) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.19013,-0.00443015) , 
5, 88.2671, 1, 0, 0.166235,-0.0384243) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.257607,0.0037692) , 
17, 1.04545, 1, 0, 0.189862,-0.0221421) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.895014,0.00662151) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.636065,0.000947018) , 
0, 126.676, 1, 0, 0.837543,0.0632121) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0145527,-0.0311632) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0392687,-0.00963755) , 
2, 1.60206, 1, 0, 0.0265119,-0.0479281) , 
0, 132.33, 1, 0, 0.67498,0.0409353) , 
0, 121.964, 1, 0, 0.508731,0.0193187)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.450126,0.0035138) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.202966,-0.00508056) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.126431,-0.00381798) , 
5, 93.7216, 1, 0, 0.188068,-0.0456355) , 
8, 1.14244, 1, 0, 0.240977,-0.0292732) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.869469,0.00635716) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.946519,0.00998214) , 
6, 68.2017, 1, 0, 0.910707,0.0902078) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.181876,-0.00716491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413577,0.000139459) , 
13, -0.454558, 1, 0, 0.350032,-0.0231678) , 
0, 126.166, 1, 0, 0.650008,0.037491) , 
0, 122.783, 1, 0, 0.490052,0.0113822)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.247733,-0.021068) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393577,-0.00404984) , 
5, 83.704, 1, 0, 0.346906,-0.0499676) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626643,0.00486073) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.138933,-0.003137) , 
0, 128.315, 1, 0, 0.54381,0.032716) , 
5, 86.9495, 1, 0, 0.51034,0.0186616) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.222476,-0.0016483) , 
5, 97.3615, 1, 0, 0.493566,0.010385)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0816932,-0.00456025) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.804262,0.00963071) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.742738,0.00531694) , 
14, 0.272191, 1, 0, 0.7831,0.0819912) , 
0, 116.534, 1, 0, 0.63492,0.0618227) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.236539,-0.00763499) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24677,-0.0156462) , 
12, -0.285513, 1, 0, 0.241707,-0.0892408) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502148,0.00271846) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208311,-0.00636319) , 
5, 95.709, 1, 0, 0.470972,0.00942936) , 
5, 86.4538, 1, 0, 0.433362,-0.00675719) , 
10, 12, 1, 0, 0.505905,-0.00716455)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.108088,-0.00477449) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.803359,0.00558879) , 
0, 119.202, 1, 0, 0.584426,0.0369741) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00813968,-0.0320292) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0234204,-0.0113091) , 
12, 0.285315, 1, 0, 0.0157831,-0.0496352) , 
0, 133.596, 1, 0, 0.518212,0.026889) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.306827,-0.00226092) , 
5, 95.5425, 1, 0, 0.497564,0.0160094)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0845037,-0.0126901) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.205282,0.00270409) , 
16, 63.8145, 1, 0, 0.112123,-0.02612) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.898049,0.00827556) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.75574,0.000146363) , 
8, 2.57025, 1, 0, 0.868781,0.0721574) , 
0, 119.986, 1, 0, 0.595847,0.0367078) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.129531,-0.00898917) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.472628,0.00275155) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00435318,-0.0168734) , 
0, 136.275, 1, 0, 0.246426,-0.0148731) , 
13, -0.0909471, 1, 0, 0.197029,-0.042526) , 
0, 127.39, 1, 0, 0.511707,0.0199915)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.297912,-0.00256045) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.869432,0.00520205) , 
0, 123.517, 1, 0, 0.543079,0.014122) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0364091,-0.0297888) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.088767,-0.00470752) , 
2, 1.29567, 1, 0, 0.0699078,-0.0603197) , 
0, 128.319, 1, 0, 0.451924,-0.000218855) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.793172,0.0116643) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505793,0.000408393) , 
8, 1.14161, 1, 0, 0.70358,0.0806983) , 
1, 131.816, 1, 0, 0.4975,0.0144355)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0927043,-0.02108) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.179801,-0.00450563) , 
5, 88.2728, 1, 0, 0.157836,-0.03862) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305843,0.00798682) , 
17, 2.13636, 1, 0, 0.18018,-0.0244295) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.76056,0.000516634) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.857709,0.00668956) , 
5, 88.2486, 1, 0, 0.837493,0.0580609) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00267222,-0.0320225) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0244956,-0.00934545) , 
2, 1.33706, 1, 0, 0.0153386,-0.0502798) , 
0, 132.335, 1, 0, 0.662947,0.0350599) , 
0, 121.967, 1, 0, 0.494891,0.0143511)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0966254,0.000837614) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.792952,0.00709191) , 
0, 116.538, 1, 0, 0.660838,0.0575204) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.721446,0.0071583) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.385185,-0.00205023) , 
9, 1.48673, 1, 0, 0.446888,0.000963363) , 
10, 12, 1, 0, 0.523554,-0.00493885) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.26126,-0.0109876) , 
14, 0.818114, 1, 0, 0.499083,0.0120578)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433129,-0.0025518) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.329114,-0.00308943) , 
12, -1.99924, 1, 0, 0.371401,-0.0512197) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0426363,-0.00526674) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649275,0.00651817) , 
0, 111.104, 1, 0, 0.575985,0.0461504) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.427531,-0.00156237) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.269318,-0.0109203) , 
14, 0.834673, 1, 0, 0.354683,-0.0354239) , 
14, 0.636329, 1, 0, 0.528763,0.028744) , 
11, -1.28032, 1, 0, 0.50407,0.0161962)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.110756,-0.00313579) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0188677,-0.00750253) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.301507,0.00208206) , 
0, 110.12, 1, 0, 0.207276,-0.00654988) , 
13, -0.454547, 1, 0, 0.179289,-0.0223483) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.916371,0.00924102) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.797198,0.00323129) , 
10, 12, 1, 0, 0.845601,0.0280086) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.051119,-0.0112835) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00518396,-0.0090474) , 
3, 2.28551, 1, 0, 0.0234546,-0.0409093) , 
0, 132.339, 1, 0, 0.678438,0.0379136) , 
0, 121.969, 1, 0, 0.509369,0.017502)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.243642,-0.007869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.365853,-0.00572016) , 
5, 83.4743, 1, 0, 0.320813,-0.0596203) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0391352,-0.0110246) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.642132,0.00431068) , 
0, 112.367, 1, 0, 0.550545,0.0312608) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.26451,-0.00349532) , 
5, 97.006, 1, 0, 0.531436,0.0227335) , 
5, 86.4453, 1, 0, 0.502943,0.0115924)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.257623,-0.0110657) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.627522,0.00393403) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.129066,-0.00728798) , 
0, 128.233, 1, 0, 0.540757,0.0288545) , 
14, -0.834711, 1, 0, 0.51433,0.0203296) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.259145,-0.00633377) , 
14, 0.818153, 1, 0, 0.490085,0.0118419)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.193015,-0.00271195) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.881639,0.00568617) , 
0, 122.459, 1, 0, 0.547369,0.0222309) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.16327,-0.00807877) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0807237,-0.00977237) , 
14, 0.45429, 1, 0, 0.137178,-0.0573999) , 
0, 127.398, 1, 0, 0.4572,0.00472616) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.825841,0.0121805) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.569694,0.00279248) , 
9, 1.24779, 1, 0, 0.718619,0.0749219) , 
1, 131.862, 1, 0, 0.502484,0.0168858)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.309312,-0.00271767) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0411815,-0.0111977) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649965,0.00548841) , 
0, 112.15, 1, 0, 0.565298,0.0364491) , 
11, -1.80082, 1, 0, 0.537829,0.0265704) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440717,-0.00115677) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.342153,-0.00812885) , 
14, 0.78058, 1, 0, 0.395161,-0.0253003) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.195002,-0.00867764) , 
14, 0.900806, 1, 0, 0.334504,-0.0434714) , 
14, 0.636341, 1, 0, 0.501664,0.0141122)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.279257,-0.0077989) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.394075,-0.00381761) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.613936,0.00518706) , 
14, -0.553733, 1, 0, 0.555358,0.0279526) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.399719,-0.00242272) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.297206,-0.0134338) , 
11, 1.69077, 1, 0, 0.350594,-0.0430904) , 
14, 0.636341, 1, 0, 0.520209,0.0157577) , 
5, 84.6359, 1, 0, 0.50117,0.00806845)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.773873,0.00808579) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.127731,-0.0019164) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.780788,0.00683618) , 
0, 119.993, 1, 0, 0.593371,0.0409169) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.439671,0.000395975) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.198111,-0.00449518) , 
5, 95.5438, 1, 0, 0.411128,-0.00975859) , 
10, 12, 1, 0, 0.472607,-0.0064578) , 
9, 1.1251, 1, 0, 0.500804,0.015205)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.154079,-0.0216948) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.346409,-0.00921313) , 
0, 123.864, 1, 0, 0.248705,-0.068485) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492006,0.00205986) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.224635,-0.017184) , 
5, 95.7102, 1, 0, 0.463648,0.00580491) , 
5, 86.4538, 1, 0, 0.430624,-0.00560897) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.771735,0.00883679) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518766,-0.000999456) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497315,0.001406) , 
2, 1.01411, 1, 0, 0.507912,-0.00216744) , 
9, 1.56958, 1, 0, 0.672362,0.0530798) , 
1, 100.659, 1, 0, 0.49848,0.0108649)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.291402,-0.00472916) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.381553,-0.00351922) , 
14, -0.636188, 1, 0, 0.343429,-0.0689921) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459175,0.00185886) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278063,-0.0155171) , 
5, 93.7224, 1, 0, 0.430262,0.000108364) , 
13, -0.636378, 1, 0, 0.409452,-0.0164517) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.127178,-0.00430244) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.832837,0.00940585) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.53558,-0.000265639) , 
9, 2.04568, 1, 0, 0.768599,0.0664274) , 
0, 117.763, 1, 0, 0.649473,0.0499091) , 
1, 89.5011, 1, 0, 0.492673,0.00655718)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.29384,-0.00764818) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438181,-0.000613249) , 
14, -0.801659, 1, 0, 0.354668,-0.0412286) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.038871,-0.0106237) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.645701,0.00445749) , 
0, 112.489, 1, 0, 0.55764,0.0294227) , 
14, -0.636381, 1, 0, 0.517572,0.0154757) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.275735,-0.00730618) , 
11, 1.63147, 1, 0, 0.493456,0.00728287)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421518,-0.000601709) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.24703,-0.00229011) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.368874,-0.00661441) , 
12, 2.20661, 1, 0, 0.30826,-0.0763951) , 
12, -1.99914, 1, 0, 0.3496,-0.0499196) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0270901,-0.0189028) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0141912,-0.0107346) , 
8, 2.28506, 1, 0, 0.0212246,-0.0474566) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.682618,0.00446427) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0065334,-0.0314111) , 
0, 137.759, 1, 0, 0.608752,0.0315035) , 
0, 111.104, 1, 0, 0.527791,0.0206228) , 
13, -0.636362, 1, 0, 0.494567,0.00747001)    );
   return;
};
 
// Clean up
inline void ReadBDTG_UF_v1::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDTG_UF_v1::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
